In [2]:
import pandas as pd
import os
from tqdm import tqdm

In [3]:
preprocessed_ad_single_sample_network_dir_path = '/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/grn_output/ad_nci_seperate_network/lioness/ad_preprocessed/'
preprocessed_nci_single_sample_network_dir_path = '/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/grn_output/ad_nci_seperate_network/lioness/nci_preprocessed/'

In [4]:
AD_data = pd.read_csv(preprocessed_ad_single_sample_network_dir_path +'lioness.427_120507.58.csv').rename(columns={'2':'lioness.427_120507.58.csv'.split('.')[1]})

for i in tqdm(os.listdir(preprocessed_ad_single_sample_network_dir_path)):
    if i.split('.')[1] in AD_data.columns:
        continue
    if 'csv' in i:
        df = pd.read_csv(preprocessed_ad_single_sample_network_dir_path + i).rename(columns={'2':i.split('.')[1]})
        AD_data = pd.merge(AD_data,df, on=['0','1'])

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 87/87 [00:33<00:00,  2.59it/s]

In [5]:
NCI_data = pd.read_csv(preprocessed_nci_single_sample_network_dir_path +'lioness.713_120531.47.csv').rename(columns={'2':'lioness.713_120531.47.csv'.split('.')[1]})

for i in tqdm(os.listdir(preprocessed_nci_single_sample_network_dir_path)):
    if i.split('.')[1] in NCI_data.columns:
        continue
    if 'csv' in i:
        df = pd.read_csv(preprocessed_nci_single_sample_network_dir_path + i).rename(columns={'2':i.split('.')[1]})
        NCI_data = pd.merge(NCI_data,df, on=['0','1'])

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [00:25<00:00,  2.60it/s]

In [6]:
AD_data.index = AD_data['0'] + '_' + AD_data['1']
AD_data.drop(columns=['0','1'],inplace = True)
AD_data

,427_120507,350_120501,497_120515,231_120425,24_120411,520_120515,202_120424,429_120507,568_120521,237_120426,...,34_120416,323_120501,384_120503,630_120524,708_120531,77_120417,23_120411,715_120531,420_120507,689_120604
ENSG00000001167_ENSG00000109685,5.422789,5.582590,5.550316,5.436518,5.477918,5.548920,6.046489,7.273255,5.856410,5.458538,...,7.035479,4.978047,5.226350,5.794004,5.773878,6.562551,5.389306,5.295861,5.771548,5.458670
ENSG00000001167_ENSG00000107362,5.349803,5.752049,5.402732,5.970177,5.579969,5.545492,5.524647,7.371541,6.909634,5.208306,...,6.190164,5.540829,5.583583,5.759652,5.260326,5.617084,5.433905,5.406885,6.530646,6.094826
ENSG00000001167_ENSG00000159423,6.944132,6.990538,6.876413,6.901820,7.081787,6.839790,6.660703,4.564330,6.687014,7.031452,...,5.906971,7.367776,7.354607,6.683811,6.306993,5.897600,7.140654,7.122604,8.000273,6.676154
ENSG00000001167_ENSG00000187187,7.422239,7.454585,7.505677,7.496206,7.481783,7.508017,8.091021,5.815734,6.816783,7.498840,...,6.295673,7.262532,8.275199,7.424579,7.459808,6.719548,7.478677,7.982371,8.699310,7.352844
ENSG00000001167_ENSG00000082701,5.269524,5.272363,5.310407,5.199323,5.234593,5.347205,4.991966,6.463328,4.880796,5.210510,...,6.167558,5.164574,5.143659,5.702611,5.787845,5.607147,5.211411,4.986887,4.633950,5.299784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278129_ENSG00000149311,13.323806,13.551514,13.455582,13.484518,13.782081,13.830250,13.832985,12.696918,13.087175,12.987033,...,13.643625,13.820091,14.347983,13.649700,13.699755,13.901009,13.704960,13.691899,13.739728,13.844341
ENSG00000278129_ENSG00000149308,13.651741,13.384342,13.417867,13.138848,14.043145,13.598172,13.447751,13.050427,13.273157,13.042831,...,13.304772,13.365571,13.219922,13.502602,13.330046,14.842179,13.335939,13.413799,13.165613,13.400331
ENSG00000278129_ENSG00000259291,13.322590,13.217686,13.624116,13.552711,13.314662,13.600096,13.381757,13.938124,13.432308,13.487628,...,13.579048,13.126054,11.702317,13.902514,13.227954,12.306634,13.353002,13.559723,13.362870,13.377070
ENSG00000278129_ENSG00000075826,15.400658,15.185094,15.313141,15.302828,15.520248,15.504817,15.394125,15.222350,15.275454,15.302409,...,14.903426,15.765718,14.325750,15.746934,15.301823,16.321014,15.159812,14.998269,15.219113,15.219156
ENSG00000278129_ENSG00000101040,13.149005,13.433854,13.069732,13.260914,13.235256,13.224622,13.269111,13.468500,13.284884,13.084374,...,13.431703,13.556180,14.903238,13.070853,14.047822,12.450501,13.362226,12.999160,13.549021,13.116372

In [7]:
NCI_data.index = NCI_data['0'] + '_' + NCI_data['1']
NCI_data.drop(columns=['0','1'],inplace = True)
NCI_data

,713_120531,951_131107,534_120516,950_131107,298_120430,508_120515,567_120521,408_120503,340_120501,290_120430,...,45_120416,677_120604,65_120417,680_120604,74_120417,152_120419,360_120502,72_120417,470_120514,386_120503
ENSG00000001167_ENSG00000176261,5.482700,5.559684,5.328263,5.558828,5.234112,5.764225,4.958463,5.549492,5.142077,5.423955,...,5.539045,5.486246,5.495824,5.509237,5.682126,5.939890,5.470133,5.919201,5.088127,5.487017
ENSG00000001167_ENSG00000140350,4.982475,5.268472,5.056994,4.951359,4.641155,4.781434,3.728474,5.032809,4.849961,5.066636,...,4.641848,4.917301,4.860898,4.327789,4.937663,7.987460,4.933812,4.901850,5.088763,4.872469
ENSG00000001167_ENSG00000139517,4.670906,5.577982,4.541473,5.160953,5.674692,4.282357,5.061684,5.294319,5.333695,5.182849,...,5.138902,5.051557,5.169504,5.097622,5.208951,6.057974,4.922699,5.388184,5.884548,5.224092
ENSG00000001167_ENSG00000130175,5.404625,5.039784,5.966988,5.429527,5.448997,5.461276,4.730063,5.469214,6.011928,5.213447,...,5.310032,5.421357,5.611544,5.238567,5.591549,5.091609,5.426514,5.538087,4.533787,5.320011
ENSG00000001167_ENSG00000132763,6.668552,7.620014,6.928177,6.414171,5.395703,6.557029,6.610947,6.684681,6.723611,6.637750,...,6.582676,6.368325,5.864250,6.331151,6.526524,5.654648,6.704224,6.709261,7.736940,6.620601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278129_ENSG00000146281,13.407919,13.608027,13.227907,14.391915,13.549009,12.006405,13.739711,13.870628,13.617681,14.556836,...,13.815204,13.900298,14.238177,13.738605,13.644225,12.071337,13.669115,13.824280,14.036683,14.066838
ENSG00000278129_ENSG00000149311,13.579513,13.506464,13.196193,13.461399,13.766703,12.441919,13.481220,13.682145,14.360163,13.905794,...,13.861326,13.678813,14.054400,13.978881,13.474053,12.636080,13.386020,12.389482,13.614431,13.592434
ENSG00000278129_ENSG00000149308,13.468954,13.396475,13.954026,13.570598,13.515806,12.230682,13.424496,13.456604,13.519724,13.709119,...,13.383097,13.604407,13.267566,13.527308,13.619648,14.694977,13.298863,13.189243,13.487149,13.202929
ENSG00000278129_ENSG00000259291,13.402257,13.593209,13.433287,13.741236,13.459474,13.860608,13.401375,13.013666,12.994866,13.598956,...,13.947162,13.491532,13.561849,12.852991,13.357489,17.289715,13.600090,14.106542,13.737192,13.276627
ENSG00000278129_ENSG00000075826,15.274045,15.282260,15.514377,15.448710,15.023314,16.028995,15.476839,15.216776,15.439769,15.468871,...,15.915617,15.433889,15.464810,15.220469,14.878867,19.255064,15.356346,15.681196,15.719278,14.963361

In [8]:
common_edge = set(NCI_data.index).intersection(set(AD_data.index))
AD_data = AD_data.loc[list(common_edge),:]
NCI_data = NCI_data.loc[list(common_edge),:]

In [9]:
clinical_data_ad_nci  = pd.read_csv('/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/count_matrix_preprocessed/final_clinical_data.csv')
clinical_data_ad_nci

,specimenID,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label
0,23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1
1,591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1
2,691_120605,5,14.0,1.0,1.0,4.833333,90.000000,4.0,3.0,0.0,NCI with No Plaques,0
3,588_120522,1,18.0,1.0,1.0,4.400000,90.000000,4.0,4.0,0.0,NCI with No Plaques,0
4,604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1
...,...,...,...,...,...,...,...,...,...,...,...,...
149,677_120604,4,23.0,1.0,1.0,18.666667,71.720739,4.0,3.0,0.0,NCI with No Plaques,0
150,142_120419,6,23.0,1.0,1.0,7.000000,71.603012,4.0,2.0,1.0,NCI with No Plaques,0
151,120_120418,5,26.0,1.0,1.0,4.083333,71.482546,4.0,1.0,1.0,NCI with No Plaques,0
152,483_120515,1,10.0,1.0,1.0,5.433333,70.510609,4.0,0.0,1.0,NCI with No Plaques,0
153,174_120424,5,12.0,1.0,1.0,5.000000,66.959617,4.0,1.0,1.0,NCI with No Plaques,0

In [10]:
clinical_data_ad_nci.set_index('specimenID', inplace = True)
clinical_data_ad_nci

,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label
specimenID,,,,,,,,,,,
23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1
591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1
691_120605,5,14.0,1.0,1.0,4.833333,90.000000,4.0,3.0,0.0,NCI with No Plaques,0
588_120522,1,18.0,1.0,1.0,4.400000,90.000000,4.0,4.0,0.0,NCI with No Plaques,0
604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1
...,...,...,...,...,...,...,...,...,...,...,...
677_120604,4,23.0,1.0,1.0,18.666667,71.720739,4.0,3.0,0.0,NCI with No Plaques,0
142_120419,6,23.0,1.0,1.0,7.000000,71.603012,4.0,2.0,1.0,NCI with No Plaques,0
120_120418,5,26.0,1.0,1.0,4.083333,71.482546,4.0,1.0,1.0,NCI with No Plaques,0
483_120515,1,10.0,1.0,1.0,5.433333,70.510609,4.0,0.0,1.0,NCI with No Plaques,0
174_120424,5,12.0,1.0,1.0,5.000000,66.959617,4.0,1.0,1.0,NCI with No Plaques,0

In [11]:
data = AD_data.T
data

,ENSG00000171223_ENSG00000184220,ENSG00000135547_ENSG00000141294,ENSG00000175322_ENSG00000103494,ENSG00000001167_ENSG00000082701,ENSG00000157429_ENSG00000174099,ENSG00000137166_ENSG00000266538,ENSG00000114439_ENSG00000140694,ENSG00000196724_ENSG00000147535,ENSG00000196724_ENSG00000198898,ENSG00000084093_ENSG00000266288,...,ENSG00000151702_ENSG00000196290,ENSG00000173875_ENSG00000163322,ENSG00000134954_ENSG00000140527,ENSG00000119508_ENSG00000274883,ENSG00000143257_ENSG00000186314,ENSG00000198517_ENSG00000184371,ENSG00000087903_ENSG00000153291,ENSG00000196418_ENSG00000159346,ENSG00000136870_ENSG00000145214,ENSG00000118620_ENSG00000196440
427_120507,9.443989,7.185674,8.040801,5.269524,4.960755,7.836717,10.714769,6.972014,10.235373,7.101051,...,8.816952,5.841268,7.094962,7.124828,11.656094,9.168869,7.506477,7.275976,4.227300,5.680127
350_120501,9.413617,7.463234,7.967795,5.272363,5.357647,7.704178,10.741457,7.030173,10.073023,7.150779,...,8.722103,5.719176,7.301489,7.637214,11.779794,8.103213,5.949257,7.373672,4.523423,5.729680
497_120515,9.719083,7.045903,7.976471,5.310407,6.068983,7.810524,11.039240,6.855860,10.399716,6.755334,...,8.872031,5.171358,7.230190,6.753523,11.978010,8.993892,6.251823,7.436752,4.639233,5.898398
231_120425,9.174838,6.599088,7.719327,5.199323,5.309197,7.643198,10.743094,6.958033,10.483172,7.564552,...,8.668667,5.556910,7.077002,7.413375,11.559420,8.413566,5.677077,7.279398,3.980771,5.583886
24_120411,9.705553,7.132675,7.751084,5.234593,5.265660,7.735825,10.672632,6.662770,10.147814,6.966940,...,8.916390,6.443676,7.424808,7.451631,11.563697,8.652156,6.544835,7.619023,4.580935,5.771361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77_120417,8.439892,7.094968,7.418164,5.607147,4.935909,6.963483,11.125221,7.556838,10.781777,6.606859,...,9.012045,5.524465,6.484281,7.444778,11.208596,8.263253,5.348885,6.355831,5.021499,5.269912
23_120411,9.482359,7.189752,7.786940,5.211411,5.314689,7.999123,10.755895,7.314649,10.287642,6.544743,...,8.725415,5.772510,7.123397,7.336773,12.068184,8.982147,6.393553,7.055690,4.572947,5.791409
715_120531,9.581262,6.941100,7.830096,4.986887,5.211034,7.549988,10.867949,6.976938,10.465707,6.513224,...,9.078636,5.677853,7.147028,7.202617,12.196899,9.030092,6.316832,7.653728,4.398479,5.770434
420_120507,9.540484,7.227752,8.186509,4.633950,5.408013,7.392242,10.887107,6.370762,10.709567,7.099786,...,8.683528,5.691333,7.235624,7.461346,11.769213,8.646359,6.882122,7.366403,4.587850,5.738590
689_120604,9.320226,7.224274,8.004755,5.299784,5.292631,7.433991,10.750896,7.165254,10.424176,6.467351,...,8.680684,5.569188,7.384559,7.487978,11.808771,8.983763,6.498269,7.619295,4.520037,5.797376

In [12]:
cross = pd.read_csv('/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/count_matrix_preprocessed/cross_section.csv')
long = pd.read_csv('/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/count_matrix_preprocessed/longn.csv')

In [13]:
biospecimen_metadata = pd.read_csv('/12tb_dsk2/common_data/ROSMAP_DATA/ROSMAP_biospecimen_metadata.csv')
clinical_data = pd.read_csv('/12tb_dsk2/common_data/ROSMAP_DATA/RSP_CL.csv')
rna_seq_metadata = pd.read_csv('/12tb_dsk2/common_data/ROSMAP_DATA/ROSMAP_assay_rnaSeq_metadata.csv')

In [14]:
biospecimen_metadata = biospecimen_metadata[biospecimen_metadata.assay == 'rnaSeq' ]
biospecimen_metadata = biospecimen_metadata[biospecimen_metadata.nucleicAcidSource == 'bulk cell' ]
biospecimen_metadata = biospecimen_metadata[biospecimen_metadata.tissue == 'dorsolateral prefrontal cortex' ]
biospecimen_metadata = biospecimen_metadata[~biospecimen_metadata.individualID.isna()  ]
biospecimen_metadata

,individualID,specimenID,specimenIdSource,organ,tissue,BrodmannArea,sampleStatus,tissueWeight,tissueVolume,nucleicAcidSource,cellType,fastingState,isPostMortem,samplingAge,samplingAgeUnits,visitNumber,assay,exclude,excludeReason,samplingDate
1916,R9976232,510_120515,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1917,R9936070,207_120424,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1918,R9907075,81_120417,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1919,R9905342,649_120529,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1920,R9904978,487_120515,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10157,R6796261,Sample_R6796261-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10158,R7310856,Sample_200r1-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10159,R3824126,Sample_R3824126-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10160,R7559268,Sample_R7559268-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10161,R3505473,Sample_R3505473-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN

In [15]:
import numpy as np
def return_specimenid(indvidualid):
    
    x = biospecimen_metadata[biospecimen_metadata.individualID == indvidualid]['specimenID'].values
    try:
        return x[0]
    except:
        return np.nan

In [16]:
clinical_data['specimenID'] = clinical_data.individualID.apply(return_specimenid)
clinical_data

,projid,Study,msex,educ,race,spanish,apoe_genotype,age_at_visit_max,age_first_ad_dx,age_death,cts_mmse30_first_ad_dx,cts_mmse30_lv,pmi,braaksc,ceradsc,cogdx,dcfdx_lv,individualID,specimenID
0,10101589,ROS,1.0,20.0,1.0,2.0,34.0,90+,90+,90+,18.0,5.0,9.916667,4.0,2.0,4.0,4.0,R6939144,594_120522
1,86767530,MAP,0.0,10.0,1.0,2.0,33.0,90+,90+,90+,18.0,10.0,6.500000,4.0,2.0,4.0,4.0,R3893503,NaN
2,9650662,MAP,0.0,15.0,1.0,2.0,23.0,90+,90+,90+,0.0,0.0,3.850000,3.0,2.0,4.0,4.0,R8937093,565_120517
3,50402855,MAP,0.0,21.0,1.0,2.0,33.0,90+,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R7139444,NaN
4,20544321,ROS,0.0,16.0,1.0,2.0,23.0,90+,90+,NaN,13.0,14.0,NaN,NaN,NaN,NaN,4.0,R4971237,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579,22207815,ROS,0.0,18.0,2.0,2.0,23.0,57.653661875427787,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R5306025,NaN
3580,22207941,ROS,0.0,16.0,2.0,2.0,34.0,56.651608487337441,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R6142763,NaN
3581,49333806,MAP,0.0,12.0,2.0,2.0,NaN,56.599589322381931,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,1.0,R4468842,NaN
3582,59720188,MAP,0.0,13.0,1.0,1.0,NaN,54.622861054072551,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R9446033,NaN
3583,90214403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R5615105,NaN

In [17]:
biospecimen_metadata[biospecimen_metadata.individualID == 'R8937093']['specimenID'].values

array(['565_120517'], dtype=object)

In [18]:
def return_projid(specimenID):
    
    x = clinical_data[clinical_data.specimenID== specimenID]['projid'].values
    try:
        return x[0]
    except:
        return np.nan

In [19]:
proj_ids_list  = clinical_data_ad_nci.reset_index().specimenID.apply(return_projid)

In [20]:
clinical_data_ad_nci['projid'] = proj_ids_list.tolist()

In [21]:
clinical_data_ad_nci

,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label,projid
specimenID,,,,,,,,,,,,
23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1,50305165
591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1,7287209
691_120605,5,14.0,1.0,1.0,4.833333,90.000000,4.0,3.0,0.0,NCI with No Plaques,0,2525608
588_120522,1,18.0,1.0,1.0,4.400000,90.000000,4.0,4.0,0.0,NCI with No Plaques,0,20280666
604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1,20120255
...,...,...,...,...,...,...,...,...,...,...,...,...
677_120604,4,23.0,1.0,1.0,18.666667,71.720739,4.0,3.0,0.0,NCI with No Plaques,0,20254164
142_120419,6,23.0,1.0,1.0,7.000000,71.603012,4.0,2.0,1.0,NCI with No Plaques,0,15712086
120_120418,5,26.0,1.0,1.0,4.083333,71.482546,4.0,1.0,1.0,NCI with No Plaques,0,10850171
483_120515,1,10.0,1.0,1.0,5.433333,70.510609,4.0,0.0,1.0,NCI with No Plaques,0,11615242
174_120424,5,12.0,1.0,1.0,5.000000,66.959617,4.0,1.0,1.0,NCI with No Plaques,0,11631558

In [22]:
keep_projids = clinical_data_ad_nci.projid.tolist()

In [23]:
cross_ad_nci = cross[cross.projid.isin(keep_projids)]
cross_ad_nci

,projid,study,scaled_to,apoe_genotype,tomm40_hap,synap_6_complex1,synap_6_complex2,synap_6_snap25,synap_6_synaptophys,synap_6_syntaxin,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
14,482428,MAP,ROSMAP,23.0,6.0,1.237661,1.625262,1.439554,1.290091,1.256545,...,83.690623,4.0,0.288440,0.000000,0.063814,0.000000,0.801505,1.126262,1.0,2.0
28,1243685,MAP,ROSMAP,33.0,1.0,-0.310333,-0.885603,-0.760926,-0.501402,-0.396581,...,90.384668,2.0,0.955066,0.887281,1.007557,1.402597,0.455045,1.357190,1.0,1.0
51,2525608,MAP,ROSMAP,33.0,3.0,-0.191097,-1.307052,0.560709,0.444140,0.498696,...,101.190965,1.0,0.082848,0.000000,0.010854,0.000000,0.237691,0.676926,0.0,1.0
86,4127190,MAP,ROSMAP,23.0,3.0,-0.874412,-0.628507,-1.105788,-0.873418,-1.119047,...,88.637919,3.0,0.018012,0.000000,0.000000,0.000000,0.054037,0.208106,1.0,2.0
130,6107196,MAP,ROSMAP,33.0,6.0,1.356037,1.023536,0.661170,0.615141,0.562103,...,94.069815,0.0,1.150062,1.482179,0.879952,1.167937,1.402297,1.884515,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3436,85171938,MAP,ROSMAP,33.0,1.0,-0.249525,-0.699091,0.323486,0.318941,0.250118,...,94.587269,1.0,1.913206,2.097811,1.094365,1.309735,3.335517,3.686204,2.0,2.0
3456,85666580,MAP,ROSMAP,33.0,3.0,0.152136,-0.414558,0.713983,0.646937,0.703197,...,85.278576,0.0,1.624258,1.844629,1.356655,1.743439,1.772680,2.908767,1.0,2.0
3516,87779516,MAP,ROSMAP,33.0,1.0,0.905939,1.173079,1.280469,1.253568,1.237589,...,91.917864,2.0,0.100507,0.043460,0.000000,0.062790,0.238732,1.084628,0.0,3.0
3689,94092977,MAP,ROSMAP,24.0,2.0,0.505018,0.286759,0.644773,0.742954,0.706626,...,82.713210,0.0,1.104523,1.309622,1.588728,1.468640,0.256201,1.184133,2.0,3.0
3712,94828877,MAP,ROSMAP,33.0,5.0,0.792032,0.992865,0.961411,0.844815,0.816245,...,82.770705,1.0,1.592491,1.645525,0.557751,2.180445,2.039276,3.913996,1.0,2.0

In [24]:
clinical_data_ad_nci.reset_index(inplace=True)
clinical_data_ad_nci = clinical_data_ad_nci[['specimenID',
 
 'educ',
 'cogdx',
 'race',
 'pmi',
 'ceradsc',
 'braaksc',
 'msex',
 'Category',
 'Label',
 'projid']]

In [25]:
merge_data = pd.merge(clinical_data_ad_nci,cross_ad_nci, on = 'projid')

In [26]:
merge_data

,specimenID,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,Label,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
0,23_120411,18.0,4.0,1.0,6.416667,1.0,4.0,0.0,AD with Plaques,1,...,101.998631,0.0,1.069731,0.648951,0.605607,1.212379,1.391206,1.639377,1.0,2.0
1,591_120522,12.0,4.0,1.0,5.200000,1.0,4.0,0.0,AD with Plaques,1,...,101.472964,3.0,0.926817,1.831791,0.255506,2.019769,0.505175,1.834671,1.0,1.0
2,691_120605,14.0,1.0,1.0,4.833333,4.0,3.0,0.0,NCI with No Plaques,0,...,101.190965,1.0,0.082848,0.000000,0.010854,0.000000,0.237691,0.676926,0.0,1.0
3,588_120522,18.0,1.0,1.0,4.400000,4.0,4.0,0.0,NCI with No Plaques,0,...,101.089665,0.0,0.704864,1.272550,1.424990,0.191199,0.498402,1.304210,3.0,3.0
4,604_120523,20.0,4.0,1.0,17.833333,1.0,5.0,0.0,AD with Plaques,1,...,99.696099,1.0,1.549014,1.175537,0.958724,1.664274,2.024042,2.217816,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,677_120604,23.0,1.0,1.0,18.666667,4.0,3.0,0.0,NCI with No Plaques,0,...,71.958932,0.0,0.124224,0.000000,0.025775,0.000000,0.346897,1.160054,0.0,0.0
150,142_120419,23.0,1.0,1.0,7.000000,4.0,2.0,1.0,NCI with No Plaques,0,...,72.429843,5.0,0.024499,0.000000,0.000000,0.000000,0.073498,0.160236,NaN,0.0
151,120_120418,26.0,1.0,1.0,4.083333,4.0,1.0,1.0,NCI with No Plaques,0,...,71.624914,0.0,0.009730,0.293077,0.000000,0.000000,0.029191,0.319598,0.0,1.0
152,483_120515,10.0,1.0,1.0,5.433333,4.0,0.0,1.0,NCI with No Plaques,0,...,71.660507,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.317621,1.0,2.0
153,174_120424,12.0,1.0,1.0,5.000000,4.0,1.0,1.0,NCI with No Plaques,0,...,67.370294,3.0,0.006487,0.120482,0.000000,0.000000,0.019461,0.185859,0.0,2.0

In [27]:
AD_df = merge_data[merge_data.Category == 'AD with Plaques']
AD_df

,specimenID,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,Label,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
0,23_120411,18.0,4.0,1.0,6.416667,1.0,4.0,0.0,AD with Plaques,1,...,101.998631,0.0,1.069731,0.648951,0.605607,1.212379,1.391206,1.639377,1.0,2.0
1,591_120522,12.0,4.0,1.0,5.200000,1.0,4.0,0.0,AD with Plaques,1,...,101.472964,3.0,0.926817,1.831791,0.255506,2.019769,0.505175,1.834671,1.0,1.0
4,604_120523,20.0,4.0,1.0,17.833333,1.0,5.0,0.0,AD with Plaques,1,...,99.696099,1.0,1.549014,1.175537,0.958724,1.664274,2.024042,2.217816,3.0,2.0
5,545_120516,16.0,4.0,1.0,7.750000,1.0,3.0,1.0,AD with Plaques,1,...,100.542094,0.0,0.727593,1.631315,0.593186,1.470877,0.118717,1.529590,2.0,3.0
6,364_120502,16.0,4.0,1.0,19.000000,1.0,5.0,0.0,AD with Plaques,1,...,98.852841,1.0,1.198759,1.164589,0.470473,1.970883,1.154920,1.812797,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,649_120529,21.0,4.0,1.0,6.750000,1.0,3.0,0.0,AD with Plaques,1,...,80.687201,0.0,0.883564,1.908817,1.307345,1.238923,0.104423,1.327859,1.0,1.0
129,689_120604,16.0,4.0,1.0,6.000000,1.0,5.0,0.0,AD with Plaques,1,...,80.736482,1.0,2.375138,1.712075,2.218073,3.372463,1.534877,2.976579,3.0,1.0
131,942_131101,16.0,4.0,1.0,5.950000,1.0,4.0,1.0,AD with Plaques,1,...,79.200548,1.0,1.294964,1.867472,0.951585,2.221625,0.711683,3.898150,3.0,1.0
145,628_120524,16.0,4.0,1.0,6.083333,1.0,5.0,1.0,AD with Plaques,1,...,75.978097,0.0,1.907649,1.963961,0.597990,3.621776,1.503180,3.999719,2.0,0.0
148,721_120531,13.0,4.0,1.0,3.000000,1.0,5.0,0.0,AD with Plaques,1,...,72.399726,0.0,2.312114,1.349242,0.360288,5.146106,1.429948,3.098522,1.0,0.0

In [28]:
NCI_df = merge_data[merge_data.Category == 'NCI with No Plaques']
NCI_df

,specimenID,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,Label,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
2,691_120605,14.0,1.0,1.0,4.833333,4.0,3.0,0.0,NCI with No Plaques,0,...,101.190965,1.0,0.082848,0.000000,0.010854,0.000000,0.237691,0.676926,0.0,1.0
3,588_120522,18.0,1.0,1.0,4.400000,4.0,4.0,0.0,NCI with No Plaques,0,...,101.089665,0.0,0.704864,1.272550,1.424990,0.191199,0.498402,1.304210,3.0,3.0
13,680_120604,23.0,1.0,1.0,4.166667,4.0,1.0,0.0,NCI with No Plaques,0,...,96.016427,1.0,0.018239,0.000000,0.025526,0.000000,0.029191,0.268311,0.0,1.0
15,274_120430,12.0,1.0,1.0,9.833333,4.0,4.0,1.0,NCI with No Plaques,0,...,95.627652,2.0,0.140478,0.050278,0.000000,0.000000,0.421435,0.938784,0.0,1.0
21,713_120531,14.0,1.0,1.0,7.483333,4.0,3.0,1.0,NCI with No Plaques,0,...,94.275154,0.0,0.194404,0.063582,0.010854,0.000000,0.572357,0.919638,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,677_120604,23.0,1.0,1.0,18.666667,4.0,3.0,0.0,NCI with No Plaques,0,...,71.958932,0.0,0.124224,0.000000,0.025775,0.000000,0.346897,1.160054,0.0,0.0
150,142_120419,23.0,1.0,1.0,7.000000,4.0,2.0,1.0,NCI with No Plaques,0,...,72.429843,5.0,0.024499,0.000000,0.000000,0.000000,0.073498,0.160236,NaN,0.0
151,120_120418,26.0,1.0,1.0,4.083333,4.0,1.0,1.0,NCI with No Plaques,0,...,71.624914,0.0,0.009730,0.293077,0.000000,0.000000,0.029191,0.319598,0.0,1.0
152,483_120515,10.0,1.0,1.0,5.433333,4.0,0.0,1.0,NCI with No Plaques,0,...,71.660507,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.317621,1.0,2.0
153,174_120424,12.0,1.0,1.0,5.000000,4.0,1.0,1.0,NCI with No Plaques,0,...,67.370294,3.0,0.006487,0.120482,0.000000,0.000000,0.019461,0.185859,0.0,2.0

In [29]:
NCI_df.columns

Index(['specimenID', 'educ', 'cogdx', 'race', 'pmi', 'ceradsc', 'braaksc',
       'msex', 'Category', 'Label', 'projid', 'study', 'scaled_to',
       'apoe_genotype', 'tomm40_hap', 'synap_6_complex1', 'synap_6_complex2',
       'synap_6_snap25', 'synap_6_synaptophys', 'synap_6_syntaxin',
       'synap_6_vamp', 'zcapture_syn_6', 'zcomplexin_6', 'zsnare_6',
       'cognep_demog_slope', 'cognep_path_slope', 'cogng_demog_slope',
       'cogng_path_slope', 'cognpo_demog_slope', 'cognpo_path_slope',
       'cognps_demog_slope', 'cognps_path_slope', 'cognse_demog_slope',
       'cognse_path_slope', 'cognwo_demog_slope', 'cognwo_path_slope',
       'age_bl', 'age_death', 'med_con_sum_bl', 'gpath', 'amylsqrt_est_8reg',
       'plaq_d', 'plaq_n', 'nft', 'tangsqrt_est_8reg', 'caa_4gp', 'cvda_4gp2'],
      dtype='object')

# Age of Death

In [30]:
import numpy as np
mean_AD_age = np.mean(AD_df.age_death)
std_AD_age = np.std(AD_df.age_death)
print("mean AD age ", mean_AD_age)
print("SD AD age ", std_AD_age)

mean AD age  89.79895678444144
SD AD age  5.577050150348457

In [32]:
import numpy as np
mean_NCI_age = np.mean(NCI_df.age_death)
std_NCI_age = np.std(NCI_df.age_death)
print("mean AD age ", mean_NCI_age)
print("SD AD age ", std_NCI_age)

mean AD age  84.32118667443072
SD AD age  7.168324768472602

In [33]:
from scipy import stats
t_stat, p_value = stats.ttest_ind(NCI_df.age_death, AD_df.age_death, equal_var=False)  # Welch's t-test

# Print results
print("Mean AD age:", mean_AD_age, "| SD AD age:", std_AD_age)
print("Mean NCI age:", mean_NCI_age, "| SD NCI age:", std_NCI_age)
print("T-statistic:", t_stat)
print("P-value:", p_value)

Mean AD age: 89.79895678444144 | SD AD age: 5.577050150348457
Mean NCI age: 84.32118667443072 | SD NCI age: 7.168324768472602
T-statistic: -5.129890471838927
P-value: 1.1123452428026477e-06

In [45]:
age = AD_df.age_death.tolist() + NCI_df.age_death.tolist()

In [46]:
len(age)

154

In [49]:
mean_age = np.mean(age)
std_age = np.std(age)
print("mean age ", mean_age)
print("SD age ", std_age )

mean age  87.41577108722899
SD age  6.877658032596304

# Sex

In [41]:
AD_df.msex.value_counts()

msex
0.0    56
1.0    31
Name: count, dtype: int64

In [37]:
NCI_df.msex.value_counts()

msex
0.0    36
1.0    31
Name: count, dtype: int64

In [38]:
NCI_df.msex.value_counts().tolist()

[36, 31]

In [39]:
AD_df.msex.value_counts().tolist()

[56, 31]

In [ ]:
from scipy import stats
t_stat, p_value = stats.ttest_ind(NCI_df.age_death, AD_df.age_death, equal_var=False)  # Welch's t-test

# Print results
print("Mean AD age:", mean_AD_age, "| SD AD age:", std_AD_age)
print("Mean NCI age:", mean_NCI_age, "| SD NCI age:", std_NCI_age)
print("T-statistic:", t_stat)
print("P-value:", p_value)

In [40]:
contingency_table = pd.DataFrame([AD_df.msex.value_counts().tolist(), NCI_df.msex.value_counts().tolist()], columns=["Female", "Male"], index=["AD", "NCI"])

In [41]:
contingency_table

     Female  Male
AD       56    31
NCI      36    31

In [43]:
from scipy.stats import chi2_contingency


# Perform Chi-square test
chi2_stat, p_val, dof, expected = chi2_contingency(contingency_table)

print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_val}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies: \n{expected}")

Chi-square statistic: 1.3656732659187965
P-value: 0.24255666977975898
Degrees of freedom: 1
Expected frequencies:
[[51.97402597 35.02597403]
 [40.02597403 26.97402597]]

# Apoe Genotype

In [59]:
AD_df.sort_values(by = 'apoe_genotype', inplace=True)

/tmp/ipykernel_93039/672007534.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AD_df.sort_values(by = 'apoe_genotype', inplace=True)

In [71]:
AD_df.apoe_genotype.value_counts()

apoe_genotype
33.0    42
34.0    37
23.0     4
24.0     3
44.0     1
Name: count, dtype: int64

In [69]:
ad_apoe = pd.DataFrame(AD_df.apoe_genotype.value_counts()).sort_index()

In [70]:
ad_apoe

               count
apoe_genotype
23.0               4
24.0               3
33.0              42
34.0              37
44.0               1

In [85]:
NCI_df.apoe_genotype.value_counts()

apoe_genotype
33.0    47
23.0    15
34.0     3
22.0     1
24.0     1
Name: count, dtype: int64

In [74]:
nci_apoe = pd.DataFrame(NCI_df.apoe_genotype.value_counts()).sort_index()

In [75]:
nci_apoe

               count
apoe_genotype
22.0               1
23.0              15
24.0               1
33.0              47
34.0               3

In [82]:
nci_apoe['count'].tolist()

[1, 15, 1, 47, 3]

In [83]:
contingency_table = pd.DataFrame([ad_apoe['count'].tolist(), nci_apoe['count'].tolist()], columns=[ "22.0", "23.0","24.0","33.0", "34.0"], index=["AD", "NCI"])

In [84]:
contingency_table

     22.0  23.0  24.0  33.0  34.0
AD      4     3    42    37     1
NCI     1    15     1    47     3

In [86]:
chi2_stat, p_val, dof, expected = chi2_contingency(contingency_table)

print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_val}")
print(f"Degrees of freedom: {dof}")
print(f"Expected frequencies: \n{expected}")

Chi-square statistic: 49.31790499520573
P-value: 5.011779132407404e-10
Degrees of freedom: 4
Expected frequencies:
[[ 2.82467532 10.16883117 24.29220779 47.45454545  2.25974026]
 [ 2.17532468  7.83116883 18.70779221 36.54545455  1.74025974]]

# Diffuse Plaques

In [37]:
AD_df.plaq_d

import numpy as np
mean_AD_plaq_d = np.mean(AD_df.plaq_d)
std_AD_plaq_d = np.std(AD_df.plaq_d)
print("mean AD diffused plaques", mean_AD_plaq_d)
print("SD AD diffused plaques ", std_AD_plaq_d)

mean AD diffused plaques 1.1162626957229538
SD AD diffused plaques  0.6678463805630345

In [38]:
AD_df.plaq_d

import numpy as np
mean_NCI_plaq_d = np.mean(NCI_df.plaq_d)
std_NCI_plaq_d = np.std(NCI_df.plaq_d)
print("mean NCI diffused plaques", mean_NCI_plaq_d)
print("SD NCI diffused plaques ", std_NCI_plaq_d)

mean NCI diffused plaques 0.08588807629014307
SD NCI diffused plaques  0.2570951370288391

# gpath

In [39]:
import numpy as np
mean_AD_gpath = np.mean(AD_df.gpath)
std_AD_gpath = np.std(AD_df.gpath)
print("mean AD gpath", mean_AD_gpath)
print("SD AD gpath", std_AD_gpath)

mean AD gpath 1.4787303493085293
SD AD gpath 0.5892799734223984

In [40]:
import numpy as np
mean_NCI_gpath = np.mean(NCI_df.gpath)
std_NCI_gpath = np.std(NCI_df.gpath)
print("mean NCI gpath", mean_NCI_gpath)
print("SD NCI gpath", std_NCI_gpath)

mean NCI gpath 0.1100438003846545
SD NCI gpath 0.14205759633435586

In [88]:
from scipy import stats
t_stat, p_value = stats.ttest_ind(NCI_df.gpath, AD_df.gpath, equal_var=False)  # Welch's t-test

# Print results

print("T-statistic:", t_stat)
print("P-value:", p_value)

T-statistic: -20.76734051812046
P-value: 8.119658031856853e-38