In [1]:
rm(list=ls())
BiocManager::install("RUVSeq")
sapply(c("sva", "dplyr", "DESeq2", "ggplot2", "reshape2", "gridExtra", "scales", 
         "RUVSeq", "ggpubr", "BatchQC"), require, character.only=TRUE)

## Parameters (change paths when necessary)
data_dir <- "./"  # path to the signature data (.rds)
source("./combat_seq_file/gfrn_helpers.R")  # path to gfrn_helpers.R
source("./combat_seq_file/ComBat_seq.R"); 
source("./combat_seq_file/helper_seq.R")   
# path to the combat-seq scripts (or use the sva package on github, in which case comment out the above line)

pathway_regex <- c("her2", "^egfr", "kraswt")  
set.seed(1)

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org

Bioconductor version 3.18 (BiocManager 1.30.25), R 4.3.3 (2024-02-29)

Warning message:
“package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'RUVSeq'”
Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    class, cluster, foreign, KernSmooth, nlme, nnet, rpart, spatial, survival
  path: /usr/local/lib/R/site-library
  packages:
    askpass, BH, bit, bit64, bitops, broom, commonmark, cpp11, credentials,
    data.table, dotCall64, evaluate, fastDummies, fitdistrplus, FNN,
    fontawesome, fs, future.apply, gert, glue, gplots, gtable, igraph, knitr,
    later, matrixStats, pillar, progressr, promises, Rcpp, reticulate, rlang,
    rmarkdown, rstudioapi, spam, spatstat.data, spatstat.univar,
    spatstat.utils, sys, systemfonts, textshaping, waldo, withr

Old packages: 'bslib', 'caret', 'cli', 'clock', 'clue', 'curl', 'doBy',
  'fastmatch', 'gower', 'hardhat', 'harmony', 'hdf5r', 'Hmisc', 'httr2',
  'jsonlite', 'lava', 'locfit', 'lubridate', 'mvtnorm', 'openssl',
  'parallelly', 'pkgbuild', 'poweRlaw', 'processx', 'ps', 'purrr', 'R6',
  'RcppArmadillo', 'Rdpack', 'recipes', 'renv', 'RSQLite', 'sessioninfo',
  'Seurat', 'shiny', 'sp', 'spatstat.explore', 'spatstat.geom', 'testthat',
  'tinytex', 'TMB', 'usethis', 'xfun', 'XML', 'zip'

Loading required package: sva

Loading required package: mgcv

Loading required package: nlme

This is mgcv 1.9-1. For overview type 'help("mgcv-package")'.

Loading required package: genefilter

Loading required package: BiocParallel

Loading required package: dplyr


Attaching package: ‘dplyr’


The following object is masked from ‘package:nlme’:

    collapse


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Loading required package: DESeq2

Loading required package: S4Vectors

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min



Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:dplyr’:

    first, rename


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges


Attaching package: ‘IRanges’


The following objects are masked from ‘package:dplyr’:

    collapse, desc, slice


The following object is masked from ‘package:nlme’:

    collapse


Loading required package: GenomicRanges

Loading required package: GenomeInfoDb

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘matrixStats’


The following object is masked from ‘package:dplyr’:

    count


The following objects are masked from ‘package:genefilter’:

    rowSds, rowVars



Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


The following objects are masked from ‘package:genefilter’:

    rowSds, rowVars


Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians


Loading required package: ggplot2

Loading required package: reshape2

Loading required package: gridExtra


Attaching package: ‘gridExtra’


The following object is masked from ‘package:Biobase’:

    combine


The following object is masked from ‘package:BiocGenerics’:

    combine


The following object is masked from ‘package:dplyr’:

    combine


Loading required package: scales

Loading required package: RUVSeq

Loading required package: EDASeq

Loading required package: ShortRead

Loading required package: Biostrings

Loading required package: XVector


Attaching package: ‘Biostrings’


The following object is masked from ‘package:base’:

    strsplit


Loading required package: Rsamtools

Loading required package: GenomicAlignments


Attaching package: ‘GenomicAlignments’


The following object is masked from ‘package:dplyr’:

    last



Attaching package: ‘ShortRead’


The following object is masked from ‘package:dplyr’:

    id


Loading required package: edgeR

Loading required package: limma


Attaching package: ‘limma’


The following object is masked from ‘package:DESeq2’:

    plotMA


The following object is masked from ‘package:BiocGenerics’:

    plotMA


Loading required package: ggpubr

Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘ggpubr’”
Loading required package: BatchQC

      sva     dplyr    DESeq2   ggplot2  reshape2 gridExtra    scales    RUVSeq
     TRUE      TRUE      TRUE      TRUE      TRUE      TRUE      TRUE      TRUE
   ggpubr   BatchQC
    FALSE      TRUE

In [17]:
file_path <- "data_preprocessed/temp_count_matrix_covariates_removal/count_matrix_raw_without_batch_7.csv"

# Read the CSV file into a data frame
count_matrix <- read.csv(file_path, row.names = 1)

# Display the structure of the loaded data frame

count_matrix <- t(count_matrix)

# Display the first few rows of the data frame
head(count_matrix)

                23_120411 591_120522 691_120605 588_120522 604_120523
ENSG00000101901 471       536         474        494        636
ENSG00000174839 355       477         460        478        588
ENSG00000151466 223       299         249        245        446
ENSG00000168288 313       492         465        464        660
ENSG00000112343 102       160         191        107        151
ENSG00000172890 841       916        1193       1028       1154
                545_120516 364_120502 705_120605 711_120531 602_120523 ⋯
ENSG00000101901 155        340        255        316         663       ⋯
ENSG00000174839 218        379        296        298         676       ⋯
ENSG00000151466 163        265        204        229         330       ⋯
ENSG00000168288 148        281        319        348         642       ⋯
ENSG00000112343 139        126        115        143         191       ⋯
ENSG00000172890 587        915        721        757        1287       ⋯
                628_120524 587_120522 168_120423 283_120430 721_120531
ENSG00000101901 146        279        552        288        197
ENSG00000174839 192        270        333        239        180
ENSG00000151466  84        190        279        219         94
ENSG00000168288 131        184        435        283        152
ENSG00000112343  82         89         50         62        140
ENSG00000172890 434        772        892        645        633
                677_120604 142_120419 120_120418 483_120515 174_120424
ENSG00000101901 235        334         311       667        307
ENSG00000174839 245        260         374       432        393
ENSG00000151466 121        174         255       234        271
ENSG00000168288 198        301         180       633        266
ENSG00000112343 159         98         194       102        287
ENSG00000172890 576        686        1000       978        826

In [18]:
# Replace "your_file.csv" with the actual path or URL of your CSV file
file_path <- "data_preprocessed/temp_count_matrix_covariates_removal/covariates_clinical_data_AD_NCI_without_batch_7.csv"

# Read the CSV file into a data frame
clinical_data <- read.csv(file_path, row.names = 1)

# Display the structure of the loaded data frame


# Display the first few rows of the data frame
head(clinical_data)

           Batch educ cogdx race pmi       age_at_visit_max ceradsc braaksc
23_120411  6     18   4     1     6.416667 90               1       4
591_120522 2     12   4     1     5.200000 90               1       4
691_120605 5     14   1     1     4.833333 90               4       3
588_120522 1     18   1     1     4.400000 90               4       4
604_120523 2     20   4     1    17.833333 90               1       5
545_120516 4     16   4     1     7.750000 90               1       3
           msex Category
23_120411  0    AD with Plaques
591_120522 0    AD with Plaques
691_120605 0    NCI with No Plaques
588_120522 0    NCI with No Plaques
604_120523 0    AD with Plaques
545_120516 1    AD with Plaques

In [19]:
tail(clinical_data)

           Batch educ cogdx race pmi       age_at_visit_max ceradsc braaksc
721_120531 4     13   4     1     3.000000 72.04381         1       5
677_120604 4     23   1     1    18.666667 71.72074         4       3
142_120419 6     23   1     1     7.000000 71.60301         4       2
120_120418 5     26   1     1     4.083333 71.48255         4       1
483_120515 1     10   1     1     5.433333 70.51061         4       0
174_120424 5     12   1     1     5.000000 66.95962         4       1
           msex Category
721_120531 0    AD with Plaques
677_120604 0    NCI with No Plaques
142_120419 1    NCI with No Plaques
120_120418 1    NCI with No Plaques
483_120515 1    NCI with No Plaques
174_120424 1    NCI with No Plaques

In [20]:
batch_sub <- clinical_data[, 'Batch']

In [21]:
group_sub <- clinical_data[, 'Category']
group_sub

  [1] "AD with Plaques"     "AD with Plaques"     "NCI with No Plaques"
  [4] "NCI with No Plaques" "AD with Plaques"     "AD with Plaques"
  [7] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [10] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [13] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [16] "NCI with No Plaques" "AD with Plaques"     "AD with Plaques"
 [19] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [22] "NCI with No Plaques" "AD with Plaques"     "NCI with No Plaques"
 [25] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [28] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [31] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [34] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [37] "AD with Plaques"     "AD with Plaques"     "NCI with No Plaques"
 [40] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [43] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [46] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [49] "AD with Plaques"     "NCI with No Plaques" "NCI with No Plaques"
 [52] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [55] "NCI with No Plaques" "AD with Plaques"     "AD with Plaques"
 [58] "NCI with No Plaques" "AD with Plaques"     "AD with Plaques"
 [61] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [64] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
 [67] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [70] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [73] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [76] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [79] "AD with Plaques"     "NCI with No Plaques" "NCI with No Plaques"
 [82] "AD with Plaques"     "AD with Plaques"     "NCI with No Plaques"
 [85] "AD with Plaques"     "AD with Plaques"     "AD with Plaques"
 [88] "NCI with No Plaques" "AD with Plaques"     "NCI with No Plaques"
 [91] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
 [94] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
 [97] "AD with Plaques"     "AD with Plaques"     "NCI with No Plaques"
[100] "AD with Plaques"     "NCI with No Plaques" "AD with Plaques"
[103] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
[106] "AD with Plaques"     "AD with Plaques"     "NCI with No Plaques"
[109] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
[112] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
[115] "AD with Plaques"     "AD with Plaques"     "NCI with No Plaques"
[118] "AD with Plaques"     "NCI with No Plaques" "NCI with No Plaques"
[121] "AD with Plaques"     "NCI with No Plaques" "NCI with No Plaques"
[124] "NCI with No Plaques" "AD with Plaques"     "AD with Plaques"
[127] "NCI with No Plaques" "AD with Plaques"     "AD with Plaques"
[130] "AD with Plaques"     "AD with Plaques"     "NCI with No Plaques"
[133] "AD with Plaques"     "NCI with No Plaques" "NCI with No Plaques"
[136] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
[139] "NCI with No Plaques" "AD with Plaques"     "AD with Plaques"
[142] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
[145] "NCI with No Plaques" "AD with Plaques"     "NCI with No Plaques"
[148] "NCI with No Plaques" "AD with Plaques"     "NCI with No Plaques"
[151] "NCI with No Plaques" "NCI with No Plaques" "NCI with No Plaques"
[154] "NCI with No Plaques" "NCI with No Plaques" "NCI with No Plaques"
[157] "NCI with No Plaques" "NCI with No Plaques" "NCI with No Plaques"
[160] "NCI with No Plaques" "AD with Plaques"     "NCI with No Plaques"
[163] "NCI with No Plaques" "NCI with No Plaques" "AD with Plaques"
[166] "NCI with No Plaques" "NCI with No Plaques" "NCI with No Plaques"
[169] "NCI with No Plaques" "NCI with No Plaques"

In [22]:
colnames(clinical_data)

 [1] "Batch"            "educ"             "cogdx"            "race"
 [5] "pmi"              "age_at_visit_max" "ceradsc"          "braaksc"
 [9] "msex"             "Category"

In [23]:
clinical_data

           Batch educ cogdx race pmi       age_at_visit_max ceradsc braaksc
23_120411  6     18   4     1     6.416667 90               1       4
591_120522 2     12   4     1     5.200000 90               1       4
691_120605 5     14   1     1     4.833333 90               4       3
588_120522 1     18   1     1     4.400000 90               4       4
604_120523 2     20   4     1    17.833333 90               1       5
545_120516 4     16   4     1     7.750000 90               1       3
364_120502 5     16   4     1    19.000000 90               1       5
705_120605 3     16   4     1     7.083333 90               1       5
711_120531 3     14   4     1     8.166667 90               1       3
602_120523 2     18   4     1     3.833333 90               1       5
229_120425 4     16   4     1    12.750000 90               1       4
708_120531 3      7   4     1     6.866667 90               1       5
28_120411  2     16   4     1    18.500000 90               1       5
680_120604 2     23   1     1     4.166667 90               4       1
706_120605 4     12   4     1     7.000000 90               1       5
274_120430 1     12   1     1     9.833333 90               4       4
280_120430 1     12   4     1    13.500000 90               1       5
24_120411  6     16   4     1    12.383333 90               1       4
663_120530 1     12   4     1     5.183333 90               1       6
637_120524 6     16   4     1     6.100000 90               1       3
444_120507 2     18   4     1     4.866667 90               1       4
713_120531 2     14   1     1     7.483333 90               4       3
292_120430 3     12   4     1    11.916667 90               1       6
460_120514 5     12   1     1     3.666667 90               4       4
309_120430 5     15   4     1     4.166667 90               1       5
04_120405  1     18   1     1     3.250000 90               4       4
186_120424 4     16   4     1     3.083333 90               1       5
703_120605 5     21   4     1    18.166667 90               1       4
355_120501 6     22   4     1     5.833333 90               1       5
310_120430 5     17   4     1     4.466667 90               1       5
⋮          ⋮     ⋮    ⋮     ⋮    ⋮         ⋮                ⋮       ⋮
649_120529 3     21   4     1     6.750000 80.55852         1       3
182_120424 6     22   1     1    16.000000 80.31759         4       0
951_131107 8     12   1     1    10.900000 80.05749         4       3
689_120604 5     16   4     1     6.000000 79.96167         1       5
72_120417  6     15   1     1     7.833333 79.58932         4       3
942_131101 8     16   4     1     5.950000 78.85558         1       4
290_120430 5     18   1     1    18.216667 78.77344         4       3
470_120514 1     16   1     1     4.516667 78.21218         4       1
929_131031 8     16   4     1     7.450000 77.60712         1       5
298_120430 3     12   1     1     7.916667 77.52498         4       1
551_120517 2     12   1     1     9.833333 77.47023         4       3
82_120417  5     12   1     1     2.500000 77.11157         4       1
386_120503 3     16   1     1    16.250000 77.07871         4       4
329_120501 4     20   1     1    10.083333 76.79945         4       1
456_120507 2     12   1     1     7.000000 76.59959         4       1
122_120418 2     16   1     1     3.750000 76.46543         4       1
245_120426 5     20   1     1     8.000000 76.40246         4       3
213_120425 2     12   1     1     5.916667 75.77823         4       0
564_120517 1     12   1     1     4.833333 75.77002         4       0
65_120417  6     13   1     1    13.750000 75.72895         4       3
628_120524 4     16   4     1     6.083333 75.49350         1       5
587_120522 3     14   1     1     3.000000 75.29363         4       1
168_120423 6     19   1     1    10.250000 73.61807         4       0
283_120430 3     18   1     1    14.966667 72.55852         4       3
721_120531 4     13   4     1     3.000000 72.04381         1       5
677_120604 4     23   1     1    18.666667 71.72074         4       3
142_120419 6     23   1     1     7.000000 71.60301         4       2
120_120418 5     26   1     1     4.083333 71.48255         4       1
483_120515 1     10   1     1     5.433333 70.51061         4       0
174_120424 5     12   1     1     5.000000 66.95962         4       1
           msex Category
23_120411  0    AD with Plaques
591_120522 0    AD with Plaques
691_120605 0    NCI with No Plaques
588_120522 0    NCI with No Plaques
604_120523 0    AD with Plaques
545_120516 1    AD with Plaques
364_120502 0    AD with Plaques
705_120605 0    AD with Plaques
711_120531 0    AD with Plaques
602_120523 0    AD with Plaques
229_120425 0    AD with Plaques
708_120531 0    AD with Plaques
28_120411  0    AD with Plaques
680_120604 0    NCI with No Plaques
706_120605 0    AD with Plaques
274_120430 1    NCI with No Plaques
280_120430 0    AD with Plaques
24_120411  0    AD with Plaques
663_120530 0    AD with Plaques
637_120524 1    AD with Plaques
444_120507 0    AD with Plaques
713_120531 1    NCI with No Plaques
292_120430 0    AD with Plaques
460_120514 0    NCI with No Plaques
309_120430 1    AD with Plaques
04_120405  0    NCI with No Plaques
186_120424 0    AD with Plaques
703_120605 0    AD with Plaques
355_120501 1    AD with Plaques
310_120430 0    AD with Plaques
⋮          ⋮    ⋮
649_120529 0    AD with Plaques
182_120424 1    NCI with No Plaques
951_131107 1    NCI with No Plaques
689_120604 0    AD with Plaques
72_120417  0    NCI with No Plaques
942_131101 1    AD with Plaques
290_120430 0    NCI with No Plaques
470_120514 1    NCI with No Plaques
929_131031 0    AD with Plaques
298_120430 1    NCI with No Plaques
551_120517 0    NCI with No Plaques
82_120417  1    NCI with No Plaques
386_120503 0    NCI with No Plaques
329_120501 1    NCI with No Plaques
456_120507 1    NCI with No Plaques
122_120418 0    NCI with No Plaques
245_120426 1    NCI with No Plaques
213_120425 0    NCI with No Plaques
564_120517 1    NCI with No Plaques
65_120417  1    NCI with No Plaques
628_120524 1    AD with Plaques
587_120522 0    NCI with No Plaques
168_120423 1    NCI with No Plaques
283_120430 0    NCI with No Plaques
721_120531 0    AD with Plaques
677_120604 0    NCI with No Plaques
142_120419 1    NCI with No Plaques
120_120418 1    NCI with No Plaques
483_120515 1    NCI with No Plaques
174_120424 1    NCI with No Plaques

In [24]:
count_matrix

                23_120411 591_120522 691_120605 588_120522 604_120523
ENSG00000101901  471       536        474        494         636
ENSG00000174839  355       477        460        478         588
ENSG00000151466  223       299        249        245         446
ENSG00000168288  313       492        465        464         660
ENSG00000112343  102       160        191        107         151
ENSG00000172890  841       916       1193       1028        1154
ENSG00000150991 4471      7503       7709       7994       10102
ENSG00000100029  733       902        778        950        1315
ENSG00000181894  366       582        454        524         637
ENSG00000206560  707       951       1019        986        1307
ENSG00000089486 4516      7129       6273       6915        8546
ENSG00000272971   45        98         84         79         125
ENSG00000181396  592       623        554        749        1116
ENSG00000150630   40        38         49         33          35
ENSG00000139908  111       132         97        135         158
ENSG00000163781  335       410        450        422         628
ENSG00000115084  223       299        291        337         325
ENSG00000110881 1076      1232        941       1150        1334
ENSG00000163517 2099      2229       2710       2184        2478
ENSG00000186297  806       949       1008        764        1448
ENSG00000157168   80       202        164        122         208
ENSG00000109790  466       700        674        529         982
ENSG00000160741  765       920        918        913        1021
ENSG00000119844  417       717        770        617         860
ENSG00000241258  724      1234       1118       1252        1679
ENSG00000042429  290       399        493        422         474
ENSG00000141968   62        73        147        120         134
ENSG00000159784 1994      2844       2260       2754        3833
ENSG00000166225  434       604        461        494         742
ENSG00000231889  194       229        246        265         276
⋮               ⋮         ⋮          ⋮          ⋮          ⋮
ENSG00000140519  167       200        190        210         225
ENSG00000265579  347       533        439        508         863
ENSG00000179476   93       121        110         90         177
ENSG00000169189  550       723        739        724         806
ENSG00000270419   75       116        118        110         127
ENSG00000152137 2755      3327       3758       4274        3638
ENSG00000140259  453       611        598        586         736
ENSG00000276250   22        30         39         25          30
ENSG00000137876  699      1014       1189        900        1683
ENSG00000131061  293       425        280        326         399
ENSG00000135837  596      1171       1181       1162        1159
ENSG00000070601  132       149        131         95         161
ENSG00000245958  244       272        268        410         491
ENSG00000165997  250       449        324        390         476
ENSG00000167619 1480      1736       1782       2025        2453
ENSG00000215788 1681      2065       1652       2726        2243
ENSG00000035928  588       968       1020        825        1184
ENSG00000138092  115       129        122         89         152
ENSG00000160888  471       530        492        560         470
ENSG00000182372  627       912        858       1074        1259
ENSG00000039560  117       191        183        110         224
ENSG00000223496 1637      3427       2515       2461        4763
ENSG00000166681 6480      9256       8837       7819       14071
ENSG00000078061  395       434        530        537         554
ENSG00000272143   43        56         75         88          78
ENSG00000120457   50        32         93         24          79
ENSG00000100528  662       969       1230        890        1195
ENSG00000116205  373       549        487        402         575
ENSG00000100603  521       695        717        678         925
ENSG00000114933  362       489        467        422         588
                545_120516 364_120502 705_120605 711_120531 602_120523 ⋯
ENSG00000101901  155        340        255        316        663       ⋯
ENSG00000174839  218        379        296        298        676       ⋯
ENSG00000151466  163        265        204        229        330       ⋯
ENSG00000168288  148        281        319        348        642       ⋯
ENSG00000112343  139        126        115        143        191       ⋯
ENSG00000172890  587        915        721        757       1287       ⋯
ENSG00000150991 2263       4308       4956       4054       9490       ⋯
ENSG00000100029  500        686        714        666       1254       ⋯
ENSG00000181894  202        288        331        262        632       ⋯
ENSG00000206560  402        672        617        730       1153       ⋯
ENSG00000089486 2824       4602       5810       4640       8807       ⋯
ENSG00000272971   38         63         36         47        102       ⋯
ENSG00000181396  405        558        490        402        904       ⋯
ENSG00000150630   14         20         32         35         32       ⋯
ENSG00000139908   47        110        121         83        184       ⋯
ENSG00000163781  127        315        246        286        583       ⋯
ENSG00000115084   85        240        175        257        441       ⋯
ENSG00000110881  643        907       1127        915       1642       ⋯
ENSG00000163517 1396       2153       1580       1803       2528       ⋯
ENSG00000186297  280        499        626        370       1840       ⋯
ENSG00000157168   48         86        108         75        272       ⋯
ENSG00000109790  256        563        477        748        815       ⋯
ENSG00000160741  450        751        639        622       1050       ⋯
ENSG00000119844  340        438        468        430       1020       ⋯
ENSG00000241258  429        676        719        596       1503       ⋯
ENSG00000042429  193        332        268        290        617       ⋯
ENSG00000141968   53         38         44         53        152       ⋯
ENSG00000159784  909       1476       1787       1390       4362       ⋯
ENSG00000166225  161        450        437        565        739       ⋯
ENSG00000231889  104        162        144        176        324       ⋯
⋮               ⋮          ⋮          ⋮          ⋮          ⋮          ⋱
ENSG00000140519   77        175        128        141         304      ⋯
ENSG00000265579  181        303        315        256         768      ⋯
ENSG00000179476   47         78         59         75         148      ⋯
ENSG00000169189  356        531        471        540         848      ⋯
ENSG00000270419   83        114         86         72         111      ⋯
ENSG00000152137  740       2022       2483       2693        3583      ⋯
ENSG00000140259  265        459        448        400         907      ⋯
ENSG00000276250   21         29         27         15          42      ⋯
ENSG00000137876  347        693        533        538        1463      ⋯
ENSG00000131061  130        217        179        218         476      ⋯
ENSG00000135837  481        847        907        889        1560      ⋯
ENSG00000070601   66        122        130         97         175      ⋯
ENSG00000245958  115        255        232        191         442      ⋯
ENSG00000165997  152        198        222        256         521      ⋯
ENSG00000167619  834       1246       1324       1129        2482      ⋯
ENSG00000215788  573       1382       1196       1022        3027      ⋯
ENSG00000035928  531        842        781        819        1088      ⋯
ENSG00000138092   53        100        117        100         156      ⋯
ENSG00000160888  271        336        370        366         635      ⋯
ENSG00000182372  508        750        829        768        1283      ⋯
ENSG00000039560  131        121        162        176         172      ⋯
ENSG00000223496 1349       1972       1780       1657        3842      ⋯
ENSG00000166681 3373       4791       4658       4068       10846      ⋯
ENSG00000078061  250        384        434        438         627      ⋯
ENSG00000272143   43         84         54         46          86      ⋯
ENSG00000120457   42         23         40         30          92      ⋯
ENSG00000100528  321        674        583        730        1353      ⋯
ENSG00000116205  251        412        342        425         532      ⋯
ENSG00000100603  333        535        522        500         868      ⋯
ENSG00000114933  204        316        283        323         781      ⋯
                628_120524 587_120522 168_120423 283_120430 721_120531
ENSG00000101901  146        279        552        288        197
ENSG00000174839  192        270        333        239        180
ENSG00000151466   84        190        279        219         94
ENSG00000168288  131        184        435        283        152
ENSG00000112343   82         89         50         62        140
ENSG00000172890  434        772        892        645        633
ENSG00000150991 2074       3038       8187       5401       3103
ENSG00000100029  446        553       1108        777        489
ENSG00000181894  180        262        604        326        215
ENSG00000206560  255        560        954        616        439
ENSG00000089486 3187       5335       6847       6016       3750
ENSG00000272971   18         51         48         51         13
ENSG00000181396  218        528        727        551        287
ENSG00000150630   10         16         17         16         27
ENSG00000139908   84         83        131         69         91
ENSG00000163781  140        190        475        284        153
ENSG00000115084  113        178        196        108        133
ENSG00000110881  614        916       1584        927        510
ENSG00000163517  982       2097       2372       1561       1342
ENSG00000186297  418        576       1604        968        144
ENSG00000157168   41         65        203        142         19
ENSG00000109790  435        426        522        329        570
ENSG00000160741  435        692        867        674        483
ENSG00000119844  373        398        647        542        281
ENSG00000241258  458        693        829        865        414
ENSG00000042429  228        224        358        253        209
ENSG00000141968   42         55         59         28         31
ENSG00000159784 1090       1661       5125       2239        625
ENSG00000166225  221        309        401        247        324
ENSG00000231889  109        154        169        111        115
⋮               ⋮          ⋮          ⋮          ⋮          ⋮
ENSG00000140519   59        188        141        153        144
ENSG00000265579  112        315        602        512         48
ENSG00000179476   35         72         82         50         56
ENSG00000169189  220        531        605        559        335
ENSG00000270419   62         95         65         62         84
ENSG00000152137 1032       1343       2088       1659       2303
ENSG00000140259  325        410        626        393        319
ENSG00000276250   25         28         26         20         18
ENSG00000137876  342        458       1169        708        318
ENSG00000131061  183        282        381        256        124
ENSG00000135837  490        815        702        574        642
ENSG00000070601   53         96        168        102         75
ENSG00000245958   53        174        376        131        128
ENSG00000165997  137        216        326        199        120
ENSG00000167619  874       1428       1872       1415        467
ENSG00000215788 1289       1595       1387       1493        431
ENSG00000035928  392        648        787        572        629
ENSG00000138092   69         81        118         90         96
ENSG00000160888  358        390        388        406        306
ENSG00000182372  463        769        794        497        713
ENSG00000039560  114        114        102         82        188
ENSG00000223496 1259       1700       2743       1868        866
ENSG00000166681 2101       3314       9889       6382       1648
ENSG00000078061  218        274        357        268        404
ENSG00000272143   16         43         30         38         44
ENSG00000120457    7         18         40         15         14
ENSG00000100528  447        601        890        598        315
ENSG00000116205  260        435        332        295        365
ENSG00000100603  299        399        621        505        343
ENSG00000114933  246        266        454        267        206
                677_120604 142_120419 120_120418 483_120515 174_120424
ENSG00000101901  235        334        311        667        307
ENSG00000174839  245        260        374        432        393
ENSG00000151466  121        174        255        234        271
ENSG00000168288  198        301        180        633        266
ENSG00000112343  159         98        194        102        287
ENSG00000172890  576        686       1000        978        826
ENSG00000150991 2979       5570       3104       9291       4231
ENSG00000100029  433        671        654       1249        652
ENSG00000181894  186        394        250        754        278
ENSG00000206560  410        690        735       1171        693
ENSG00000089486 3465       4271       4182       7622       4793
ENSG00000272971   32         23         62         86         36
ENSG00000181396  379        433        649        832        471
ENSG00000150630   31         36         24         31         36
ENSG00000139908   54        126        117        163        109
ENSG00000163781  178        293        202        559        325
ENSG00000115084  177        215        215        319        270
ENSG00000110881  567       1174       1092       1754       1274
ENSG00000163517 1726       1696       2028       2707       2974
ENSG00000186297  298       1698        295       1730        282
ENSG00000157168   30         61         56        268         48
ENSG00000109790  507        477        686        539        771
ENSG00000160741  439        631        838        833        762
ENSG00000119844  316        380        349        828        402
ENSG00000241258  382        751        574       1135        786
ENSG00000042429  227        271        287        525        307
ENSG00000141968   62         96         47         49        148
ENSG00000159784  888       2048       1204       5109       1048
ENSG00000166225  391        399        365        639        461
ENSG00000231889  112        140        165        254        191
⋮               ⋮          ⋮          ⋮          ⋮          ⋮
ENSG00000140519  150        148        120         218       165
ENSG00000265579  156        448        169         839       207
ENSG00000179476   51         59         93         130        85
ENSG00000169189  392        491        511         828       604
ENSG00000270419   68         62        169         114       109
ENSG00000152137 1716       1157       1406        3104      1731
ENSG00000140259  333        380        353         815       435
ENSG00000276250   15         23         33          20        30
ENSG00000137876  442        716        494        1422       548
ENSG00000131061  133        211        241         404       191
ENSG00000135837  638        538        933         950      1068
ENSG00000070601   59         60         62         164       109
ENSG00000245958  116        182        235         270       207
ENSG00000165997  140        204        212         472       245
ENSG00000167619  772        842       1203        1853       903
ENSG00000215788  608        995       1183        2126       938
ENSG00000035928  549        506        821         903       750
ENSG00000138092   73        126         84         107       108
ENSG00000160888  300        345        575         599       496
ENSG00000182372  613        719        828         991       824
ENSG00000039560  170        135        224         117       257
ENSG00000223496 1141       1185       1970        3652      2049
ENSG00000166681 2669       6949       3471       10771      3524
ENSG00000078061  337        366        348         436       372
ENSG00000272143   32         25         47          39        83
ENSG00000120457    9         49         26          58        33
ENSG00000100528  493        602        530        1304       635
ENSG00000116205  347        345        494         500       543
ENSG00000100603  335        435        564         735       527
ENSG00000114933  200        259        381         467       404

In [25]:
start_time <- Sys.time()
count_matrix_combatseq_sub <- ComBat_seq(counts=count_matrix, batch=batch_sub, group=group_sub, shrink=FALSE)
end_time <- Sys.time()
print(end_time - start_time)

Found 8 batches
Using full model in ComBat-seq.
Adjusting for 1 covariate(s) or covariate level(s)
Estimating dispersions
Fitting the GLM model
Shrinkage off - using GLM estimates for parameters
Adjusting the data
Time difference of 25.04078 secs

In [26]:
count_matrix_combatseq_sub

                23_120411 591_120522 691_120605 588_120522 604_120523
ENSG00000101901  434       497        530        367        575
ENSG00000174839  392       392        484        428        485
ENSG00000151466  216       268        252        233        410
ENSG00000168288  290       432        508        326        600
ENSG00000112343  130       157        200        130        146
ENSG00000172890  755       844       1171       1129       1065
ENSG00000150991 3276      6423       8300       6307       8918
ENSG00000100029  582       777        947        738       1122
ENSG00000181894  302       520        525        374        551
ENSG00000206560  692       876       1047        821       1289
ENSG00000089486 3850      6487       6667       6079       7674
ENSG00000272971   46        88         84         65        113
ENSG00000181396  545       523        624        655        992
ENSG00000150630   44        38         50         35         32
ENSG00000139908  100       132        113        112        157
ENSG00000163781  297       376        511        293        608
ENSG00000115084  243       260        308        294        278
ENSG00000110881  917      1090       1094        905       1112
ENSG00000163517 1951      2071       2696       2112       2289
ENSG00000186297  570       781       1167        467       1272
ENSG00000157168   58       173        186         68        166
ENSG00000109790  489       693        636        572        983
ENSG00000160741  630       893        919        834        914
ENSG00000119844  341       661        758        520        756
ENSG00000241258  657       943       1172        988       1256
ENSG00000042429  287       353        465        363        412
ENSG00000141968   55        61        152        115        124
ENSG00000159784 1410      2622       2874       1729       3633
ENSG00000166225  462       540        507        428        662
ENSG00000231889  208       203        244        247        246
⋮               ⋮         ⋮          ⋮          ⋮          ⋮
ENSG00000140519  150       178        203        198         198
ENSG00000265579  275       422        538        299         773
ENSG00000179476   97       104        117         79         165
ENSG00000169189  530       635        768        711         711
ENSG00000270419   88       106        113        110         120
ENSG00000152137 2648      2964       3947       4053        3030
ENSG00000140259  409       580        646        483         694
ENSG00000276250   19        30         38         29          29
ENSG00000137876  606       881       1198        628        1616
ENSG00000131061  243       376        328        245         347
ENSG00000135837  646      1093       1180       1158        1068
ENSG00000070601  111       144        148         74         151
ENSG00000245958  247       217        301        320         444
ENSG00000165997  244       382        353        323         392
ENSG00000167619 1158      1497       1950       1951        2328
ENSG00000215788 1527      1588       1899       2587        1652
ENSG00000035928  626       906        978        809        1106
ENSG00000138092  111       120        134         81         137
ENSG00000160888  420       516        525        559         485
ENSG00000182372  633       821        954       1087        1110
ENSG00000039560  136       191        167        134         223
ENSG00000223496 1598      2719       2728       2097        3768
ENSG00000166681 5131      7720       9469       4785       12588
ENSG00000078061  363       411        566        513         525
ENSG00000272143   50        47         74         91          67
ENSG00000120457   49        28        100         17          68
ENSG00000100528  662       906       1186        710        1104
ENSG00000116205  411       508        504        406         560
ENSG00000100603  530       648        724        587         918
ENSG00000114933  366       451        470        365         540
                545_120516 364_120502 705_120605 711_120531 602_120523 ⋯
ENSG00000101901  227        381        278        348        615       ⋯
ENSG00000174839  287        396        333        327        534       ⋯
ENSG00000151466  206        259        199        224        290       ⋯
ENSG00000168288  236        330        355        387        579       ⋯
ENSG00000112343  121        106        103        129        187       ⋯
ENSG00000172890  634        920        701        728       1212       ⋯
ENSG00000150991 3365       5113       5546       4362       8200       ⋯
ENSG00000100029  619        818        764        688       1073       ⋯
ENSG00000181894  291        350        380        295        547       ⋯
ENSG00000206560  581        723        634        785       1047       ⋯
ENSG00000089486 3384       5019       5811       4112       8010       ⋯
ENSG00000272971   56         64         33         43         86       ⋯
ENSG00000181396  520        595        481        339        779       ⋯
ENSG00000150630   16         20         31         34         29       ⋯
ENSG00000139908   55        125        132         83        187       ⋯
ENSG00000163781  210        362        263        309        555       ⋯
ENSG00000115084  113        249        198        290        391       ⋯
ENSG00000110881  774       1028       1139        890       1495       ⋯
ENSG00000163517 1395       2133       1578       1797       2339       ⋯
ENSG00000186297  491        654        728        399       1742       ⋯
ENSG00000157168   93        106        121         67        240       ⋯
ENSG00000109790  288        532        525        835        802       ⋯
ENSG00000160741  535        752        608        572        966       ⋯
ENSG00000119844  424        498        544        496       1087       ⋯
ENSG00000241258  608        777        759        534       1154       ⋯
ENSG00000042429  249        337        306        329        587       ⋯
ENSG00000141968   63         42         43         53        146       ⋯
ENSG00000159784 1470       1949       1832       1270       4348       ⋯
ENSG00000166225  213        491        492        649        660       ⋯
ENSG00000231889  128        169        153        188        282       ⋯
⋮               ⋮          ⋮          ⋮          ⋮          ⋮          ⋱
ENSG00000140519   91        182        131        144        276       ⋯
ENSG00000265579  325        375        325        235        655       ⋯
ENSG00000179476   62         84         60         79        127       ⋯
ENSG00000169189  414        551        461        526        746       ⋯
ENSG00000270419   87        109         84         75        108       ⋯
ENSG00000152137 1140       2290       2737       2971       2979       ⋯
ENSG00000140259  328        503        503        439        892       ⋯
ENSG00000276250   21         29         30         16         43       ⋯
ENSG00000137876  549        745        668        673       1344       ⋯
ENSG00000131061  166        257        184        223        418       ⋯
ENSG00000135837  580        847        934        900       1461       ⋯
ENSG00000070601   84        136        133         89        167       ⋯
ENSG00000245958  175        280        256        198        387       ⋯
ENSG00000165997  216        232        264        306        438       ⋯
ENSG00000167619  980       1426       1320        965       2398       ⋯
ENSG00000215788  838       1586       1200        991       2444       ⋯
ENSG00000035928  620        817        771        800       1009       ⋯
ENSG00000138092   61        111        119         98        143       ⋯
ENSG00000160888  270        371        389        380        621       ⋯
ENSG00000182372  555        833        908        789       1124       ⋯
ENSG00000039560  117        109        177        192        170       ⋯
ENSG00000223496 1556       2128       1973       1795       3057       ⋯
ENSG00000166681 5269       5555       5242       4493       8860       ⋯
ENSG00000078061  273        420        423        424        597       ⋯
ENSG00000272143   51         81         50         44         75       ⋯
ENSG00000120457   63         24         39         26         79       ⋯
ENSG00000100528  438        714        664        855       1392       ⋯
ENSG00000116205  247        425        361        458        528       ⋯
ENSG00000100603  428        556        545        509        818       ⋯
ENSG00000114933  257        334        312        359        741       ⋯
                628_120524 587_120522 168_120423 283_120430 721_120531
ENSG00000101901  209        301        497        314        298
ENSG00000174839  246        289        342        252        231
ENSG00000151466  138        181        270        217        143
ENSG00000168288  215        200        420        313        242
ENSG00000112343   80         79         74         54        122
ENSG00000172890  487        760        792        619        679
ENSG00000150991 3230       3102       6952       6055       4289
ENSG00000100029  561        549        946        847        607
ENSG00000181894  262        294        541        373        309
ENSG00000206560  349        515        960        633        639
ENSG00000089486 3803       5008       6192       6080       4321
ENSG00000272971   33         47         47         48         26
ENSG00000181396  289        511        669        566        374
ENSG00000150630   12         17         22         17         30
ENSG00000139908   94         84        117         69        100
ENSG00000163781  231        187        433        307        253
ENSG00000115084  148        202        204        124        171
ENSG00000110881  734        899       1326        921        607
ENSG00000163517  938       2080       2195       1561       1335
ENSG00000186297  684        649       1320       1165        299
ENSG00000157168   85         50        160        168         47
ENSG00000109790  438        467        556        358        530
ENSG00000160741  525        665        703        657        570
ENSG00000119844  465        458        679        636        362
ENSG00000241258  652        701        739       1026        591
ENSG00000042429  295        235        376        286        270
ENSG00000141968   51         56         52         24         38
ENSG00000159784 1753       1594       3665       2421       1036
ENSG00000166225  284        333        417        261        395
ENSG00000231889  134        164        174        116        141
⋮               ⋮          ⋮          ⋮          ⋮          ⋮
ENSG00000140519   75        191        115        156        154
ENSG00000265579  239        302        542        600        134
ENSG00000179476   52         75         85         48         71
ENSG00000169189  273        522        574        543        393
ENSG00000270419   62         90         75         63         88
ENSG00000152137 1462       1581       2018       1895       2484
ENSG00000140259  398        452        610        436        388
ENSG00000276250   25         31         23         22         18
ENSG00000137876  539        571       1099        889        501
ENSG00000131061  234        285        332        259        158
ENSG00000135837  594        829        770        560        765
ENSG00000070601   68         91        138        100         95
ENSG00000245958   88        177        395        127        194
ENSG00000165997  200        253        327        233        177
ENSG00000167619 1044       1449       1501       1494        685
ENSG00000215788 1543       1653        978       1550        692
ENSG00000035928  481        611        913        534        722
ENSG00000138092   78         78        111         89        108
ENSG00000160888  342        409        317        433        297
ENSG00000182372  503        841        769        473        787
ENSG00000039560  104        129        120         96        161
ENSG00000223496 1520       1843       2770       2075       1141
ENSG00000166681 3633       3558       8174       7287       2941
ENSG00000078061  257        256        320        252        382
ENSG00000272143   19         41         34         36         53
ENSG00000120457   11         14         39         11         21
ENSG00000100528  623        671        924        679        429
ENSG00000116205  257        477        349        308        348
ENSG00000100603  398        393        643        527        439
ENSG00000114933  307        288        463        294        260
                677_120604 142_120419 120_120418 483_120515 174_120424
ENSG00000101901  345        280        404        547        421
ENSG00000174839  315        260        417        324        448
ENSG00000151466  186        167        259        206        278
ENSG00000168288  319        265        282        486        378
ENSG00000112343  141        125        198        127        357
ENSG00000172890  638        601       1045        949        955
ENSG00000150991 4550       4328       4818       7626       6132
ENSG00000100029  554        515        833        971        857
ENSG00000181894  274        324        359        591        404
ENSG00000206560  576        669        830        994        827
ENSG00000089486 4222       3565       5315       6622       6108
ENSG00000272971   53         18         68         70         48
ENSG00000181396  495        364        713        723        574
ENSG00000150630   34         40         24         32         36
ENSG00000139908   64        112        135        134        128
ENSG00000163781  294        241        284        402        418
ENSG00000115084  228        231        247        275        304
ENSG00000110881  670        992       1247       1550       1452
ENSG00000163517 1704       1556       2102       2672       2992
ENSG00000186297  568       1503        548       1346        566
ENSG00000157168   74         41         91        195         87
ENSG00000109790  501        517        647        556        728
ENSG00000160741  542        461        884        693        882
ENSG00000119844  416        292        482        747        556
ENSG00000241258  575        759        752        833        973
ENSG00000042429  294        254        340        457        375
ENSG00000141968   74         86         52         41        155
ENSG00000159784 1471       1448       1855       3633       1763
ENSG00000166225  478        424        411        575        515
ENSG00000231889  139        144        182        228        210
⋮               ⋮          ⋮          ⋮          ⋮          ⋮
ENSG00000140519  166        129        143        198        189
ENSG00000265579  332        380        294        726        352
ENSG00000179476   72         61        102        112         96
ENSG00000169189  472        465        603        825        708
ENSG00000270419   69         72        153        115        110
ENSG00000152137 2198       1125       1828       2386       2216
ENSG00000140259  415        312        459        682        553
ENSG00000276250   16         21         33         22         30
ENSG00000137876  696        604        670       1075        753
ENSG00000131061  169        146        300        330        269
ENSG00000135837  767        582        934        926       1069
ENSG00000070601   76         56         81        140        132
ENSG00000245958  181        174        271        220        248
ENSG00000165997  211        182        266        400        307
ENSG00000167619 1031        551       1498       1387       1292
ENSG00000215788  945        607       1526       1571       1368
ENSG00000035928  656        521        844        877        822
ENSG00000138092   83        127         99         98        125
ENSG00000160888  312        286        600        594        550
ENSG00000182372  670        687        918        908        908
ENSG00000039560  149        153        206        144        236
ENSG00000223496 1529       1104       2261       3253       2402
ENSG00000166681 4705       5357       5185       7818       5523
ENSG00000078061  359        336        399        382        432
ENSG00000272143   38         28         50         37         83
ENSG00000120457   14         48         27         48         34
ENSG00000100528  677        552        675       1153        798
ENSG00000116205  338        379        507        521        552
ENSG00000100603  451        392        626        627        630
ENSG00000114933  261        254        408        403        442

In [27]:
count_matrix_combatseq_sub['ENSG00000000003','23_120411']

[1] 165

In [28]:
file_path <- "data_preprocessed/temp_count_matrix_covariates_removal/count_matrix_after_iteration_without_batch_7_1_batch.csv"
write.csv(count_matrix_combatseq_sub, file = file_path, row.names = TRUE)