In [1]:
import pandas as pd

In [2]:
ad_nci_corr = pd.read_csv('../../../data_preprocessed/correlation_output/ad_nci_corr_df.csv')
ad_nci_corr

,0,corr_value,P_value
0,cognse_path_slope_ENSG00000107175_ENSG00000185133,0.090428,0.311983
1,cognse_path_slope_ENSG00000106571_ENSG00000166135,-0.080304,0.369459
2,cognse_path_slope_ENSG00000120784_ENSG00000204161,-0.050414,0.573521
3,cognse_path_slope_ENSG00000129654_ENSG00000239291,0.016855,0.850810
4,cognse_path_slope_ENSG00000169155_ENSG00000111452,-0.076543,0.392371
...,...,...,...
3554665,synap_6_synaptophys_ENSG00000196705_ENSG000001...,0.101462,0.410341
3554666,synap_6_synaptophys_ENSG00000198517_ENSG000001...,0.030194,0.806899
3554667,synap_6_synaptophys_ENSG00000250571_ENSG000002...,-0.042944,0.728051
3554668,synap_6_synaptophys_ENSG00000204524_ENSG000001...,0.254189,0.036463
3554669,synap_6_synaptophys_ENSG00000197013_ENSG000001...,0.294652,0.014723

In [3]:
nci_corr = pd.read_csv('../../../data_preprocessed/correlation_output/nci_corr_df.csv')
nci_corr

,0,NCI_correlation_value,P_value_NCI
0,synap_6_synaptophys_ENSG00000173875_ENSG000001...,-0.741653,0.000006
1,synap_6_vamp_ENSG00000184517_ENSG00000090612,-0.739464,0.000007
2,zsnare_6_ENSG00000184517_ENSG00000090612,-0.713738,0.000020
3,synap_6_synaptophys_ENSG00000173875_ENSG000001...,-0.703339,0.000030
4,synap_6_complex1_ENSG00000106536_ENSG00000115414,-0.701149,0.000032
...,...,...,...
3554665,synap_6_complex1_ENSG00000130751_ENSG00000236753,0.704433,0.000029
3554666,synap_6_complex1_ENSG00000196652_ENSG00000260236,0.706623,0.000026
3554667,synap_6_complex1_ENSG00000116016_ENSG00000236753,0.714286,0.000020
3554668,synap_6_synaptophys_ENSG00000152467_ENSG000001...,0.722496,0.000014
3554669,synap_6_complex1_ENSG00000196652_ENSG00000269038,0.730159,0.000010

In [4]:
ad_corr = pd.read_csv('../../../data_preprocessed/correlation_output/ad_corr_df.csv')
ad_corr

,0,AD_correlation_value,P_value_AD
0,zcomplexin_6_ENSG00000115112_ENSG00000197037,-0.693809,6.905714e-07
1,synap_6_complex2_ENSG00000115112_ENSG00000197037,-0.690432,8.225725e-07
2,synap_6_snap25_ENSG00000187079_ENSG00000111911,-0.681426,1.296827e-06
3,synap_6_snap25_ENSG00000170684_ENSG00000176749,-0.675235,1.757331e-06
4,synap_6_synaptophys_ENSG00000187079_ENSG000001...,-0.660976,3.445378e-06
...,...,...,...
3554665,synap_6_complex2_ENSG00000152467_ENSG00000148834,0.644090,7.312861e-06
3554666,synap_6_snap25_ENSG00000054598_ENSG00000227028,0.644841,7.079170e-06
3554667,synap_6_complex2_ENSG00000121068_ENSG00000207561,0.675610,1.725617e-06
3554668,synap_6_synaptophys_ENSG00000126804_ENSG000001...,0.679925,1.396898e-06
3554669,synap_6_snap25_ENSG00000126804_ENSG00000111911,0.682552,1.226159e-06

In [5]:
merge_ad_nci_corr = pd.merge(ad_corr,nci_corr,on = '0')
merge_ad_nci_corr

,0,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI
0,zcomplexin_6_ENSG00000115112_ENSG00000197037,-0.693809,6.905714e-07,-0.056924,0.773566
1,synap_6_complex2_ENSG00000115112_ENSG00000197037,-0.690432,8.225725e-07,-0.105638,0.592652
2,synap_6_snap25_ENSG00000187079_ENSG00000111911,-0.681426,1.296827e-06,0.046524,0.814141
3,synap_6_snap25_ENSG00000170684_ENSG00000176749,-0.675235,1.757331e-06,-0.345375,0.071847
4,synap_6_synaptophys_ENSG00000187079_ENSG000001...,-0.660976,3.445378e-06,-0.018062,0.927312
...,...,...,...,...,...
3554665,synap_6_complex2_ENSG00000152467_ENSG00000148834,0.644090,7.312861e-06,0.116037,0.556526
3554666,synap_6_snap25_ENSG00000054598_ENSG00000227028,0.644841,7.079170e-06,0.042146,0.831374
3554667,synap_6_complex2_ENSG00000121068_ENSG00000207561,0.675610,1.725617e-06,-0.009852,0.960316
3554668,synap_6_synaptophys_ENSG00000126804_ENSG000001...,0.679925,1.396898e-06,-0.139026,0.480466
3554669,synap_6_snap25_ENSG00000126804_ENSG00000111911,0.682552,1.226159e-06,-0.135194,0.492761

In [6]:
merge_ad_nci_corr['abs_diff'] = (merge_ad_nci_corr['AD_correlation_value']  - merge_ad_nci_corr['NCI_correlation_value']).abs()

In [7]:
merge_ad_nci_corr.sort_values(by = 'abs_diff',ascending=False, inplace= True)

In [8]:
edge_name = []
clinical_variables_name = []
for i in merge_ad_nci_corr['0']:
    #print('-'.join(i.split('_')[-2:]))
    #print('_'.join(i.split('_')[:-2]))
    edge_name.append('-'.join(i.split('_')[-2:]))
    clinical_variables_name.append('_'.join(i.split('_')[:-2]))

In [9]:
merge_ad_nci_corr['edges'] = edge_name
merge_ad_nci_corr['clinical_variables'] = clinical_variables_name

In [10]:
merge_ad_nci_corr

,0,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff,edges,clinical_variables
3554208,synap_6_synaptophys_ENSG00000137166_ENSG000002...,0.504878,0.000892,-0.602627,0.000690,1.107505e+00,ENSG00000137166-ENSG00000225855,synap_6_synaptophys
3554597,synap_6_snap25_ENSG00000077150_ENSG00000105982,0.567917,0.000132,-0.477833,0.010121,1.045750e+00,ENSG00000077150-ENSG00000105982,synap_6_snap25
5157,synap_6_synaptophys_ENSG00000018869_ENSG000002...,-0.397936,0.010992,0.613574,0.000516,1.011510e+00,ENSG00000018869-ENSG00000261710,synap_6_synaptophys
2290,synap_6_complex1_ENSG00000197013_ENSG00000161036,-0.435647,0.004958,0.561576,0.001874,9.972236e-01,ENSG00000197013-ENSG00000161036,synap_6_complex1
3554189,synap_6_snap25_ENSG00000137166_ENSG00000225855,0.503565,0.000925,-0.492611,0.007742,9.961756e-01,ENSG00000137166-ENSG00000225855,synap_6_snap25
...,...,...,...,...,...,...,...,...
484656,synap_6_synaptophys_ENSG00000177842_ENSG000000...,-0.132458,0.415203,-0.132458,0.501638,2.053829e-07,ENSG00000177842-ENSG00000011677,synap_6_synaptophys
3051563,zsnare_6_ENSG00000167081_ENSG00000232696,0.132458,0.415203,0.132458,0.501638,2.053829e-07,ENSG00000167081-ENSG00000232696,zsnare_6
886671,cognse_path_slope_ENSG00000118058_ENSG00000182118,-0.080520,0.501350,-0.080519,0.558963,1.670463e-07,ENSG00000118058-ENSG00000182118,cognse_path_slope
67046,cognps_demog_slope_ENSG00000170345_ENSG0000017...,-0.262244,0.019557,-0.262244,0.044802,9.959043e-08,ENSG00000170345-ENSG00000175691,cognps_demog_slope
1662657,cognep_demog_slope_ENSG00000109381_ENSG0000017...,-0.008514,0.939868,-0.008514,0.948077,1.194265e-08,ENSG00000109381-ENSG00000172977,cognep_demog_slope

In [11]:
merge_ad_nci_corr.columns

Index(['0', 'AD_correlation_value', 'P_value_AD', 'NCI_correlation_value',
       'P_value_NCI', 'abs_diff', 'edges', 'clinical_variables'],
      dtype='object')

In [12]:
keep_columns = ['clinical_variables', 'edges', 'AD_correlation_value', 'P_value_AD', 'NCI_correlation_value',
       'P_value_NCI', 'abs_diff']

In [13]:
merge_ad_nci_corr = merge_ad_nci_corr[keep_columns]

In [14]:
corr_dataframe_dict_per_clinical = dict()
for i in merge_ad_nci_corr.clinical_variables.unique():
    df = merge_ad_nci_corr[merge_ad_nci_corr.clinical_variables == i]
    df.sort_values(by = 'abs_diff',ascending=False, inplace= True)
    corr_dataframe_dict_per_clinical[i] = df

/tmp/ipykernel_541344/362961279.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.sort_values(by = 'abs_diff',ascending=False, inplace= True)

In [15]:
corr_dataframe_dict_per_clinical.keys()

dict_keys(['synap_6_synaptophys', 'synap_6_snap25', 'synap_6_complex1', 'zcomplexin_6', 'synap_6_vamp', 'zsnare_6', 'synap_6_complex2', 'zcapture_syn_6', 'synap_6_syntaxin', 'pmi', 'cognwo_demog_slope', 'cognse_demog_slope', 'cognse_path_slope', 'cognwo_path_slope', 'cognpo_path_slope', 'cognps_path_slope', 'cognep_path_slope', 'cognpo_demog_slope', 'tangsqrt_est_8reg', 'age_death', 'cogng_path_slope', 'cognep_demog_slope', 'nft', 'cognps_demog_slope', 'plaq_n', 'cogng_demog_slope', 'amylsqrt_est_8reg', 'age_bl', 'plaq_d', 'gpath'])

In [16]:
corr_dataframe_dict_per_clinical['plaq_d']

,clinical_variables,edges,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff
3358597,plaq_d,ENSG00000162924-ENSG00000163833,0.200518,0.062573,-0.468625,0.000063,0.669142
3547298,plaq_d,ENSG00000091831-ENSG00000111640,0.387530,0.000209,-0.248427,0.042652,0.635958
3535856,plaq_d,ENSG00000090447-ENSG00000187634,0.339396,0.001300,-0.284311,0.019715,0.623708
227435,plaq_d,ENSG00000131848-ENSG00000054392,-0.186794,0.083206,0.436053,0.000226,0.622847
68402,plaq_d,ENSG00000108788-ENSG00000139437,-0.261118,0.014572,0.354975,0.003203,0.616093
...,...,...,...,...,...,...,...
1348399,plaq_d,ENSG00000168826-ENSG00000086061,-0.035795,0.742042,-0.035784,0.773744,0.000011
1738269,plaq_d,ENSG00000169957-ENSG00000027697,-0.002114,0.984495,-0.002108,0.986493,0.000006
2386007,plaq_d,ENSG00000197013-ENSG00000154188,0.054750,0.614499,0.054754,0.659879,0.000005
3141763,plaq_d,ENSG00000175832-ENSG00000196712,0.147755,0.172021,0.147752,0.232791,0.000003
2046158,plaq_d,ENSG00000162599-ENSG00000138439,0.024167,0.824168,0.024165,0.846092,0.000002

In [17]:
corr_dataframe_dict_per_clinical['nft']

,clinical_variables,edges,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff
45555,nft,ENSG00000184939-ENSG00000198721,-0.284465,0.007577,0.440364,0.000192,0.724828
85904,nft,ENSG00000167182-ENSG00000148339,-0.247758,0.020684,0.475913,0.000047,0.723671
97835,nft,ENSG00000120784-ENSG00000135473,-0.240049,0.025124,0.451202,0.000127,0.691251
79080,nft,ENSG00000167182-ENSG00000177301,-0.252606,0.018251,0.426871,0.000315,0.679477
118498,nft,ENSG00000167182-ENSG00000164068,-0.228275,0.033455,0.450683,0.000130,0.678958
...,...,...,...,...,...,...,...
2514718,nft,ENSG00000187079-ENSG00000099797,0.067198,0.536304,0.067206,0.588945,0.000009
1097704,nft,ENSG00000177485-ENSG00000189241,-0.058996,0.587272,-0.059003,0.635299,0.000006
1760243,nft,ENSG00000131408-ENSG00000254713,-0.000273,0.997995,-0.000279,0.998209,0.000006
1122815,nft,ENSG00000125398-ENSG00000166927,-0.056572,0.602747,-0.056567,0.649343,0.000005
2021720,nft,ENSG00000171606-ENSG00000130175,0.022035,0.839465,0.022036,0.859508,0.000001

In [18]:
corr_dataframe_dict_per_clinical['cognps_demog_slope']

,clinical_variables,edges,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff
3512594,cognps_demog_slope,ENSG00000167562-ENSG00000143033,0.294888,0.008335,-0.427937,0.000722,7.228249e-01
70394,cognps_demog_slope,ENSG00000196152-ENSG00000070759,-0.259372,0.020985,0.462478,0.000226,7.218500e-01
133163,cognps_demog_slope,ENSG00000176165-ENSG00000157570,-0.221178,0.050128,0.489421,0.000084,7.105996e-01
3446550,cognps_demog_slope,ENSG00000196172-ENSG00000184515,0.238608,0.034202,-0.458913,0.000256,6.975205e-01
44497,cognps_demog_slope,ENSG00000111249-ENSG00000164776,-0.285906,0.010642,0.409702,0.001271,6.956075e-01
...,...,...,...,...,...,...,...
1566249,cognps_demog_slope,ENSG00000185507-ENSG00000145569,-0.016821,0.883026,-0.016832,0.899310,1.142444e-05
1082826,cognps_demog_slope,ENSG00000180787-ENSG00000142039,-0.060443,0.596701,-0.060432,0.649343,1.054236e-05
2694525,cognps_demog_slope,ENSG00000136936-ENSG00000136098,0.086027,0.450946,0.086032,0.517059,4.296616e-06
1756412,cognps_demog_slope,ENSG00000183960-ENSG00000139496,-0.000584,0.995923,-0.000584,0.996495,2.276353e-07
67046,cognps_demog_slope,ENSG00000170345-ENSG00000175691,-0.262244,0.019557,-0.262244,0.044802,9.959043e-08

In [19]:
corr_dataframe_dict_per_clinical['amylsqrt_est_8reg']

,clinical_variables,edges,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff
18505,amylsqrt_est_8reg,ENSG00000077150-ENSG00000272405,-0.333553,0.001699,0.366455,0.002289,0.700009
3545575,amylsqrt_est_8reg,ENSG00000083814-ENSG00000111262,0.377065,0.000345,-0.278467,0.022502,0.655532
3548551,amylsqrt_est_8reg,ENSG00000083814-ENSG00000123091,0.396877,0.000155,-0.257118,0.035689,0.653996
3524788,amylsqrt_est_8reg,ENSG00000127124-ENSG00000116586,0.314270,0.003211,-0.324184,0.007444,0.638453
3386208,amylsqrt_est_8reg,ENSG00000081059-ENSG00000008283,0.210416,0.051824,-0.419657,0.000408,0.630072
...,...,...,...,...,...,...,...
2492562,amylsqrt_est_8reg,ENSG00000185507-ENSG00000241956,0.065013,0.552038,0.065024,0.601127,0.000011
1120333,amylsqrt_est_8reg,ENSG00000115816-ENSG00000255198,-0.056823,0.603295,-0.056816,0.647903,0.000007
575228,amylsqrt_est_8reg,ENSG00000188290-ENSG00000152256,-0.118732,0.276233,-0.118735,0.338571,0.000003
1774309,amylsqrt_est_8reg,ENSG00000167554-ENSG00000134291,0.000896,0.993465,0.000893,0.994277,0.000003
468285,amylsqrt_est_8reg,ENSG00000188290-ENSG00000159208,-0.135148,0.214727,-0.135151,0.275514,0.000003

In [20]:
corr_dataframe_dict_per_clinical.keys()

dict_keys(['synap_6_synaptophys', 'synap_6_snap25', 'synap_6_complex1', 'zcomplexin_6', 'synap_6_vamp', 'zsnare_6', 'synap_6_complex2', 'zcapture_syn_6', 'synap_6_syntaxin', 'pmi', 'cognwo_demog_slope', 'cognse_demog_slope', 'cognse_path_slope', 'cognwo_path_slope', 'cognpo_path_slope', 'cognps_path_slope', 'cognep_path_slope', 'cognpo_demog_slope', 'tangsqrt_est_8reg', 'age_death', 'cogng_path_slope', 'cognep_demog_slope', 'nft', 'cognps_demog_slope', 'plaq_n', 'cogng_demog_slope', 'amylsqrt_est_8reg', 'age_bl', 'plaq_d', 'gpath'])

**1. cogng_demog_slope (β Global Cognition ~ Age, Sex, Education)**: The random slope of global cognition is the estimated person-specific rate of change in the global cognition variable over time. It comes from a linear mixed effects model with global cognition as the longitudinal outcome. The model controls for age at baseline, sex, and years of education.
*******

**2. cognep_demog_slope (β Episodic Memory ~ Age, Sex, Education):** The random slope of episodic memory is the estimated person-specific rate of change in the episodic memory domain variable over time. It comes from a linear mixed effects model with episodic memory as the longitudinal outcome. The model controls for age at baseline, sex, and years of education.
*******

**3. cognwo_demog_slope (β Working Memory ~ Age, Sex, Education):** The random slope of working memory is the estimated person-specific rate of change in the working memory domain variable over time. It comes from a linear mixed effects model with working memory as the longitudinal outcome. The model controls for age at baseline, sex, and years of education
*******

**4. cognse_demog_slope (β Semantic Memory ~ Age, Sex, Education):** The random slope of semantic memory is the estimated person-specific rate of change in the semantic memory domain variable over time. It comes from a linear mixed effects model with semantic memory as the longitudinal outcome. The model controls for age at baseline, sex, and years of education.
*******

**5. cognps_demog_slope (β Perceptual Speed ~ Age, Sex, Education)**: The random slope of perceptual speed is the estimated person-specific rate of change in the perceptual speed domain variable over time. It comes from a linear mixed effects model with perceptual speed as the longitudinal outcome. The model controls for age at baseline, sex, and years of education.
*******

**6. cognpo_demog_slope (β Visuospatial ability ~ Age, Sex, Education)**: The random slope of visuospatial ability/perceptual orientation is the estimated person-specific rate of change in the perceptual orientation domain variable over time. It comes from a linear mixed effects model with visuospatial ability as the longitudinal outcome. The model controls for age at baseline, sex, and years of education.
*******

**7. cogng_path_slope (β Global Cognition ~ Demographics + Pathology)**: The random slope of global cognition (demographics + pathology) is the estimated person-specific rate of change in the global cognition variable over time, controlled for the following demographics and pathology. It comes from a linear mixed effects model with global cognition as the outcome.

***Demographics***:

Age at death,
Sex,
Years of education,

***Pathology***:

Global AD pathology burden,
Amyloid beta,
PHF tau tangles,
Gross chronic cerebral infarctions,
Chronic microinfarctions,
Lewy body disease,
TDP-43,
Hippocampal sclerosis,
Cerebral amyloid angiopathy,
Cerebral atherosclerosis,
Arteriolosclerosis,

Notes: Time in this model refers to years from date of death.

The listed reference describes the model adjusting for demographics.
*******

**8. cognep_path_slope (β Episodic Memory ~ Demographics + Pathology)**: The random slope of episodic memory (demographics + pathology) is the estimated person-specific rate of change in the episodic memory domain variable over time, controlled for the following demographics and pathology. It comes from a linear mixed effects model with episodic memory as the outcome.

***Demographics***:

Age at death,
Sex,
Years of education,

***Pathology***:

Global AD pathology burden,
Amyloid beta,
PHF tau tangles,
Gross chronic cerebral infarctions,
Chronic microinfarctions,
Lewy body disease,
TDP-43,
Hippocampal sclerosis,
Cerebral amyloid angiopathy,
Cerebral atherosclerosis,
Arteriolosclerosis,

Notes: Time in this model refers to years from date of death.

The listed reference describes the model adjusting for demographics.
*******

**9. cognwo_path_slope (β Working Memory ~ Demographics + Pathology)**: The random slope of working memory (demographics + pathology) is the estimated person-specific rate of change in the working memory domain variable over time, controlled for the following demographics and pathology. It comes from a linear mixed effects model with working memory as the outcome.

***Demographics***:

Age at death,
Sex,
Years of education,

***Pathology***:

Global AD pathology burden,
Amyloid beta,
PHF tau tangles,
Gross chronic cerebral infarctions,
Chronic microinfarctions,
Lewy body disease,
TDP-43,
Hippocampal sclerosis,
Cerebral amyloid angiopathy,
Cerebral atherosclerosis,
Arteriolosclerosis,

Notes: Time in this model refers to years from date of death.

The listed reference describes the model adjusting for demographics.
*******

**10. cognse_path_slope (β Semantic Memory ~ Demographics + Pathology)**: The random slope of semantic memory (demographics + pathology) is the estimated person-specific rate of change in the semantic memory domain variable over time, controlled for the following demographics and pathology. It comes from a linear mixed effects model with semantic memory as the outcome.


***Demographics***:

Age at death,
Sex,
Years of education,

***Pathology***:

Global AD pathology burden,
Amyloid beta,
PHF tau tangles,
Gross chronic cerebral infarctions,
Chronic microinfarctions,
Lewy body disease,
TDP-43,
Hippocampal sclerosis,
Cerebral amyloid angiopathy,
Cerebral atherosclerosis,
Arteriolosclerosis,

Notes: Time in this model refers to years from date of death.

The listed reference describes the model adjusting for demographics.
*******

**11. cognps_path_slope (β Perceptual Speed ~ Demographics + Pathology)**: The random slope of perceptual speed (demographics + pathology) is the estimated person-specific rate of change in the perceptual speed domain variable over time, controlled for the following demographics and pathology. It comes from a linear mixed effects model with perceptual speed as the outcome.

***Demographics***:

Age at death,
Sex,
Years of education,

***Pathology***:

Global AD pathology burden,
Amyloid beta,
PHF tau tangles,
Gross chronic cerebral infarctions,
Chronic microinfarctions,
Lewy body disease,
TDP-43,
Hippocampal sclerosis,
Cerebral amyloid angiopathy,
Cerebral atherosclerosis,
Arteriolosclerosis,

Notes: Time in this model refers to years from date of death.

The listed reference describes the model adjusting for demographics.

*******

**12. cognpo_path_slope (β Visuospatial Ability ~ Demographics + Pathology)**: 
The random slope of visuospatial ability/perceptual orientation (demographics + pathology) is the estimated person-specific rate of change in the visuospatial ability/perceptual orientation domain variable over time, controlled for the following demographics and pathology. It comes from a linear mixed effects model with visuospatial ability/perceptual orientation as the outcome.

***Demographics***:

Age at death,
Sex,
Years of education,

***Pathology***:

Global AD pathology burden,
Amyloid beta,
PHF tau tangles,
Gross chronic cerebral infarctions,
Chronic microinfarctions,
Lewy body disease,
TDP-43,
Hippocampal sclerosis,
Cerebral amyloid angiopathy,
Cerebral atherosclerosis,
Arteriolosclerosis,

Notes: Time in this model refers to years from date of death.

The listed reference describes the model adjusting for demographics.
*******

In [21]:
corr_dataframe_dict_per_clinical['cognwo_demog_slope']

,clinical_variables,edges,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff
2416,cognwo_demog_slope,ENSG00000091831-ENSG00000148303,-0.433604,0.000053,0.404601,0.001220,0.838205
3518334,cognwo_demog_slope,ENSG00000197579-ENSG00000235513,0.303297,0.005916,-0.379164,0.002583,0.682462
3351737,cognwo_demog_slope,ENSG00000267680-ENSG00000261329,0.198216,0.076086,-0.468588,0.000140,0.666804
3518947,cognwo_demog_slope,ENSG00000135111-ENSG00000253846,0.304268,0.005751,-0.358382,0.004568,0.662650
3502392,cognwo_demog_slope,ENSG00000135625-ENSG00000198925,0.282317,0.010664,-0.371602,0.003192,0.653919
...,...,...,...,...,...,...,...
929749,cognwo_demog_slope,ENSG00000178573-ENSG00000112812,-0.075949,0.500383,-0.075939,0.560788,0.000010
2235967,cognwo_demog_slope,ENSG00000234284-ENSG00000283050,0.040921,0.716814,0.040931,0.754131,0.000009
2902219,cognwo_demog_slope,ENSG00000120837-ENSG00000157796,0.110885,0.324379,0.110894,0.394870,0.000008
1508313,cognwo_demog_slope,ENSG00000134852-ENSG00000197181,-0.021793,0.846871,-0.021787,0.867634,0.000006
2770347,cognwo_demog_slope,ENSG00000072310-ENSG00000048649,0.094603,0.400866,0.094606,0.468305,0.000003

In [22]:
for i in corr_dataframe_dict_per_clinical.keys():
    corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
    corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()

#

/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[0].tolist()
/tmp/ipykernel_541344/1476897744.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes'] =  pd.DataFrame(corr_dataframe_dict_per_clinical[i].edges.str.split('-').tolist())[1].tolist()
/tmp/ipykernel_541344/1476897744.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead


In [23]:
import pickle

# Replace 'your_file.pkl' with the path to your pickle file
with open('../../../data_preprocessed/pickle_file/ensemble_to_gene_name.pickle', 'rb') as file:
    ensemble_to_gene_dict = pickle.load(file)

In [24]:
corr_dataframe_dict_per_clinical['cognpo_path_slope']

,clinical_variables,edges,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff,TF,Target Genes
18624,cognpo_path_slope,ENSG00000177485-ENSG00000009307,-0.333173,0.004239,0.462771,0.000374,0.795943,ENSG00000177485,ENSG00000009307
54229,cognpo_path_slope,ENSG00000119547-ENSG00000163629,-0.274648,0.019555,0.517460,0.000052,0.792108,ENSG00000119547,ENSG00000163629
32595,cognpo_path_slope,ENSG00000196653-ENSG00000130244,-0.303171,0.009634,0.475180,0.000246,0.778351,ENSG00000196653,ENSG00000130244
86415,cognpo_path_slope,ENSG00000178573-ENSG00000178764,-0.247444,0.036119,0.523954,0.000040,0.771397,ENSG00000178573,ENSG00000178764
92477,cognpo_path_slope,ENSG00000187079-ENSG00000103740,-0.243424,0.039353,0.518182,0.000051,0.761606,ENSG00000187079,ENSG00000103740
...,...,...,...,...,...,...,...,...,...
2985969,cognpo_path_slope,ENSG00000091656-ENSG00000152683,0.122452,0.305498,0.122439,0.373181,0.000013,ENSG00000091656,ENSG00000152683
252359,cognpo_path_slope,ENSG00000112033-ENSG00000117614,-0.179786,0.130742,-0.179798,0.189006,0.000011,ENSG00000112033,ENSG00000117614
484173,cognpo_path_slope,ENSG00000139651-ENSG00000184347,-0.132549,0.267027,-0.132540,0.334731,0.000009,ENSG00000139651,ENSG00000184347
2006936,cognpo_path_slope,ENSG00000152467-ENSG00000132932,0.020773,0.862495,0.020779,0.880307,0.000006,ENSG00000152467,ENSG00000132932
1476691,cognpo_path_slope,ENSG00000127124-ENSG00000124253,-0.024535,0.837903,-0.024531,0.858900,0.000004,ENSG00000127124,ENSG00000124253

In [25]:
def return_gene_name(i):
    l = ensemble_to_gene_dict[i]
    if l == 'Gene name not found':
        return i
    else:
        return l

In [26]:
#corr_dataframe_dict_per_clinical['cognpo_path_slope'].TF.map(return_gene_name).tolist()

In [27]:
for i in corr_dataframe_dict_per_clinical.keys():
    corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
    corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()

#

/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['Target Genes Ensemble'] =  corr_dataframe_dict_per_clinical[i]['Target Genes'].map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['TF_Ensemble'] =  corr_dataframe_dict_per_clinical[i].TF.map(return_gene_name).tolist()
/tmp/ipykernel_541344/1427332495.py:3: SettingWithCopyWarning:

In [28]:
corr_dataframe_dict_per_clinical['cogng_demog_slope']

,clinical_variables,edges,AD_correlation_value,P_value_AD,NCI_correlation_value,P_value_NCI,abs_diff,TF,Target Genes,TF_Ensemble,Target Genes Ensemble
11811,cogng_demog_slope,ENSG00000173041-ENSG00000151575,-0.356888,0.001074,0.364410,0.003886,7.212984e-01,ENSG00000173041,ENSG00000151575,ZNF680,TEX9
3527095,cogng_demog_slope,ENSG00000169155-ENSG00000141933,0.318902,0.003712,-0.388260,0.001988,7.071626e-01,ENSG00000169155,ENSG00000141933,ZBTB43,TPGS1
22894,cogng_demog_slope,ENSG00000188786-ENSG00000172159,-0.322177,0.003355,0.382919,0.002320,7.050961e-01,ENSG00000188786,ENSG00000172159,MTF1,FRMD3
112236,cogng_demog_slope,ENSG00000135547-ENSG00000138764,-0.231640,0.037457,0.470703,0.000129,7.023429e-01,ENSG00000135547,ENSG00000138764,HEY2,CCNG2
160959,cogng_demog_slope,ENSG00000171649-ENSG00000197563,-0.209282,0.060781,0.466420,0.000151,6.757017e-01,ENSG00000171649,ENSG00000197563,ZIK1,PIGN
...,...,...,...,...,...,...,...,...,...,...,...
1034676,cogng_demog_slope,ENSG00000063438-ENSG00000118762,-0.065199,0.563072,-0.065204,0.617601,4.860660e-06,ENSG00000063438,ENSG00000118762,AHRR,PKD2
1981090,cogng_demog_slope,ENSG00000108001-ENSG00000237015,0.018564,0.869345,0.018562,0.887093,2.078022e-06,ENSG00000108001,ENSG00000237015,EBF3,ENSG00000237015
1981102,cogng_demog_slope,ENSG00000088881-ENSG00000237015,0.018564,0.869345,0.018562,0.887093,2.078022e-06,ENSG00000088881,ENSG00000237015,EBF4,ENSG00000237015
3084583,cogng_demog_slope,ENSG00000117010-ENSG00000125170,0.137760,0.220039,0.137758,0.289726,1.910825e-06,ENSG00000117010,ENSG00000125170,ZNF684,DOK4
1936178,cogng_demog_slope,ENSG00000198464-ENSG00000136861,0.014702,0.896355,0.014701,0.910466,6.807313e-07,ENSG00000198464,ENSG00000136861,ZNF480,CDK5RAP2

In [29]:
clinical_cog_var = []

for i in corr_dataframe_dict_per_clinical.keys():
    if 'cog' in i:
        clinical_cog_var.append(i)

In [30]:
AD_tf_value_counts = dict()
AD_target_genes_value_counts = dict()
AD_tf_list = dict()
AD_target_genes_list = dict()

for i in clinical_cog_var:
    print(i)
    df = corr_dataframe_dict_per_clinical[i]
    df = df[df.P_value_AD<0.05]
    #print(df)

    AD_tf_value_counts[i] = pd.DataFrame(df.TF_Ensemble.value_counts())
    AD_target_genes_value_counts[i]      = pd.DataFrame(df['Target Genes Ensemble'].value_counts())
    AD_tf_list[i] = list(set(df.TF_Ensemble.tolist()))    
    AD_target_genes_list[i] = list(set(df['Target Genes Ensemble'].tolist()))

cognwo_demog_slope
cognse_demog_slope
cognse_path_slope
cognwo_path_slope
cognpo_path_slope
cognps_path_slope
cognep_path_slope
cognpo_demog_slope
cogng_path_slope
cognep_demog_slope
cognps_demog_slope
cogng_demog_slope

In [31]:
AD_tf_value_counts.keys()

dict_keys(['cognwo_demog_slope', 'cognse_demog_slope', 'cognse_path_slope', 'cognwo_path_slope', 'cognpo_path_slope', 'cognps_path_slope', 'cognep_path_slope', 'cognpo_demog_slope', 'cogng_path_slope', 'cognep_demog_slope', 'cognps_demog_slope', 'cogng_demog_slope'])

In [32]:
for i in AD_tf_value_counts.keys():
    print(i)
    print('              ')
   # print(AD_tf_value_counts[i])
    print(AD_tf_value_counts[i][AD_tf_value_counts[i]['count']>1])
    print(AD_target_genes_value_counts[i][AD_target_genes_value_counts[i]['count']>1])
    print('__'*50)

cognwo_demog_slope

             count
TF_Ensemble
ZNF574         110
ZNF431          92
HIVEP3          78
HIVEP1          78
SP2             68
...            ...
CLOCK            2
ZFP69B           2
ZNF740           2
PLAGL1           2
ZBTB33           2

[514 rows x 1 columns]
                       count
Target Genes Ensemble
DNAJC7                    13
RNF167                    12
SULT1C4                   11
PRPF40B                    9
CDC14A                     8
...                      ...
TBC1D1                     2
ZNF346                     2
HPCA                       2
SOD3                       2
ENSG00000236255            2

[1009 rows x 1 columns]
____________________________________________________________________________________________________
cognse_demog_slope

             count
TF_Ensemble
RELB            75
ZNF574          54
ZNF486          54
ZNF589          51
NFKB1           46
...            ...
POU2F2           2
ETV1             2
ZNF248           2
FOXF2            2
ZNF527           2

[435 rows x 1 columns]
                       count
Target Genes Ensemble
ZNF335                    12
LCDR                      11
ZNF585B                   10
ANAPC2                     9
UBN2                       8
...                      ...
WNT5A                      2
EIF2B1                     2
LRRIQ1                     2
SLC39A13                   2
SPTBN1                     2

[592 rows x 1 columns]
____________________________________________________________________________________________________
cognse_path_slope

             count
TF_Ensemble
HINFP           68
RELB            67
ZNF574          54
ZNF429          47
HEY2            46
...            ...
ZNF674           2
ZNF276           2
RFX2             2
ZNF205           2
OLIG2            2

[501 rows x 1 columns]
                       count
Target Genes Ensemble
SNHG15                    12
ZNF335                    12
LCDR                       8
MROH7                      8
ZMPSTE24                   7
...                      ...
CCDC66                     2
WDR5                       2
MAN1C1                     2
CACNA1F                    2
ARHGAP24                   2

[749 rows x 1 columns]
____________________________________________________________________________________________________
cognwo_path_slope

             count
TF_Ensemble
ZNF430          65
HES4            60
TBX18           56
MXI1            47
ZNF574          45
...            ...
MITF             2
ZNF525           2
SKOR1            2
ZNF41            2
THRB             2

[514 rows x 1 columns]
                       count
Target Genes Ensemble
DNAJC7                    13
SULT1C4                   11
MRPL27                    10
ZFYVE16                   10
CDC14A                     9
...                      ...
WHRN                       2
CPVL                       2
RGPD8                      2
VPS39                      2
ENSG00000271743            2

[967 rows x 1 columns]
____________________________________________________________________________________________________
cognpo_path_slope

             count
TF_Ensemble
CREM            79
ZBTB42          67
CREB3L4         67
ZBTB18          64
ZIC1            61
...            ...
ZSCAN5A          2
JDP2             2
PBX4             2
ZNF704           2
PBX2             2

[494 rows x 1 columns]
                       count
Target Genes Ensemble
ARG2                      14
MGME1                     13
UMPS                      13
NTHL1                     12
B3GAT3                    11
...                      ...
SIRT7                      2
PARG                       2
SLC25A48                   2
MERTK                      2
F5                         2

[1005 rows x 1 columns]
____________________________________________________________________________________________________
cognps_path_slope

             count
TF_Ensemble
CREB1           63
ZNF430          62
CREB3L4         59
ZNF528          53
CREM            42
...            ...
ZNF433           2
MITF             2
TP73             2
AIRE             2
PRDM16           2

[463 rows x 1 columns]
                       count
Target Genes Ensemble
UMPS                      13
EFCAB14                   12
RIIAD1                    12
MAOA                      12
ID1                       11
...                      ...
RGS1                       2
DEPP1                      2
DHPS                       2
H3-3B                      2
PODNL1                     2

[666 rows x 1 columns]
____________________________________________________________________________________________________
cognep_path_slope

             count
TF_Ensemble
ZNF574          95
ATOH8           90
MXI1            88
RXRB            80
RXRG            79
...            ...
ZNF487           2
ZNF554           2
ZBTB12           2
GABPA            2
OLIG2            2

[579 rows x 1 columns]
                       count
Target Genes Ensemble
LOXL3                     14
MAOA                      13
SCAMP2                    13
CLSTN2                    13
TRIP6                     13
...                      ...
ENSG00000262529            2
NSUN5                      2
ENPEP                      2
GOLGA5                     2
BRAP                       2

[1604 rows x 1 columns]
____________________________________________________________________________________________________
cognpo_demog_slope

             count
TF_Ensemble
ZIC1            68
ZIC2            66
ZNF574          63
ZNF140          56
SP2             52
...            ...
NPAS2            2
ZNF454           2
TOPORS           2
CLOCK            2
TBX15            2

[511 rows x 1 columns]
                       count
Target Genes Ensemble
ZNF335                    12
LRRC8A                    11
SLC26A11                  11
TMEM39A                   11
UMPS                      11
...                      ...
STT3B                      2
TRPC4AP                    2
ENSG00000264304            2
SCRG1                      2
SHISA5P2                   2

[1086 rows x 1 columns]
____________________________________________________________________________________________________
cogng_path_slope

             count
TF_Ensemble
ZNF574          98
MXI1            75
ATOH8           68
NFE2L2          62
MAX             61
...            ...
SPDEF            2
RORB             2
CUX2             2
TBX2             2
TBX1             2

[528 rows x 1 columns]
                       count
Target Genes Ensemble
TRIP6                     13
LRRC8A                    13
LOXL3                     13
DNAJC7                    13
MGME1                     12
...                      ...
OLA1                       2
EIF3L                      2
DCAF12                     2
NNAT                       2
SLC9A9                     2

[1129 rows x 1 columns]
____________________________________________________________________________________________________
cognep_demog_slope

             count
TF_Ensemble
MAX            124
MXI1           100
KLF8            84
ZFP14           83
ATOH8           81
...            ...
REST             2
SOX18            2
OXSR1            2
ZBTB2            2
ZNF585A          2

[535 rows x 1 columns]
                       count
Target Genes Ensemble
WDR35                     15
ERI2                      13
ZNF335                    12
CTDP1                     11
ENSG00000279088           10
...                      ...
FBXO7                      2
BCAS4                      2
PALD1                      2
XRCC4                      2
PPM1A                      2

[1405 rows x 1 columns]
____________________________________________________________________________________________________
cognps_demog_slope

             count
TF_Ensemble
ZNF582          45
ZNF528          41
MAX             36
ZNF429          33
ZNF430          31
...            ...
FEZF2            2
ZNF419           2
ELF2             2
ZNF584           2
ZNF449           2

[490 rows x 1 columns]
                       count
Target Genes Ensemble
GTF2IP13                  12
PDE7A                     11
ZNF335                    10
PDE4A                      9
PPP1R9A                    9
...                      ...
COL4A2                     2
ZNF221                     2
GMPR                       2
CACNA1D                    2
TEX9                       2

[561 rows x 1 columns]
____________________________________________________________________________________________________
cogng_demog_slope

             count
TF_Ensemble
MAX            139
ZNF574          91
ZNF589          64
ZNF501          64
KLF8            61
...            ...
ZNF785           2
SOX21            2
ZNF454           2
FOXO6            2
ATF4             2

[501 rows x 1 columns]
                       count
Target Genes Ensemble
ZNF335                    11
TMEM39A                   10
ZNF585B                    9
HINT3                      8
PDE4A                      8
...                      ...
SLC27A2                    2
LINC01114                  2
CLEC2D                     2
TARBP2                     2
MMRN2                      2

[1076 rows x 1 columns]
____________________________________________________________________________________________________

In [33]:
NCI_tf_value_counts = dict()
NCI_target_genes_value_counts = dict()
NCI_tf_list = dict()
NCI_target_genes_list = dict()

for i in clinical_cog_var:
    print(i)
    df = corr_dataframe_dict_per_clinical[i]
    df = df[df.P_value_NCI<0.05]
    #print(df)

    NCI_tf_value_counts[i] = pd.DataFrame(df.TF_Ensemble.value_counts())
    NCI_tf_list[i] = list(set(df.TF_Ensemble.tolist()))
    NCI_target_genes_value_counts[i] = pd.DataFrame(df['Target Genes Ensemble'].value_counts())
    NCI_target_genes_list[i] = list(set(df['Target Genes Ensemble'].tolist()))

cognwo_demog_slope
cognse_demog_slope
cognse_path_slope
cognwo_path_slope
cognpo_path_slope
cognps_path_slope
cognep_path_slope
cognpo_demog_slope
cogng_path_slope
cognep_demog_slope
cognps_demog_slope
cogng_demog_slope

In [34]:
for i in AD_tf_value_counts.keys():
    print(i)
    print('              ')
   # print(AD_tf_value_counts[i])
    print(AD_tf_value_counts[i][AD_tf_value_counts[i]['count']>1])
    print(NCI_tf_value_counts[i][NCI_tf_value_counts[i]['count']>1])
    print(AD_target_genes_value_counts[i][AD_target_genes_value_counts[i]['count']>1])
    print(NCI_target_genes_value_counts[i][NCI_target_genes_value_counts[i]['count']>1])
    print('__'*50)

cognwo_demog_slope

             count
TF_Ensemble
ZNF574         110
ZNF431          92
HIVEP3          78
HIVEP1          78
SP2             68
...            ...
CLOCK            2
ZFP69B           2
ZNF740           2
PLAGL1           2
ZBTB33           2

[514 rows x 1 columns]
             count
TF_Ensemble
ZNF684         104
ZNF641          88
KLF13           82
ZNF69           66
PBX3            61
...            ...
ZNF337           2
PROX1            2
TEF              2
POU3F3           2
EBF1             2

[525 rows x 1 columns]
                       count
Target Genes Ensemble
DNAJC7                    13
RNF167                    12
SULT1C4                   11
PRPF40B                    9
CDC14A                     8
...                      ...
TBC1D1                     2
ZNF346                     2
HPCA                       2
SOD3                       2
ENSG00000236255            2

[1009 rows x 1 columns]
                       count
Target Genes Ensemble
DPP8                      15
AOPEP                     13
UFSP2                     13
ODAD3                     12
ZNF687                    12
...                      ...
CACNA1E                    2
IMPA1                      2
FAM86EP                    2
SNHG29                     2
UPF2                       2

[1316 rows x 1 columns]
____________________________________________________________________________________________________
cognse_demog_slope

             count
TF_Ensemble
RELB            75
ZNF574          54
ZNF486          54
ZNF589          51
NFKB1           46
...            ...
POU2F2           2
ETV1             2
ZNF248           2
FOXF2            2
ZNF527           2

[435 rows x 1 columns]
             count
TF_Ensemble
HINFP          123
ZNF430         113
ZNF19          112
ZNF616         108
ZNF16          103
...            ...
THRA             2
ZNF891           2
XPA              2
EGR1             2
ZNF467           2

[629 rows x 1 columns]
                       count
Target Genes Ensemble
ZNF335                    12
LCDR                      11
ZNF585B                   10
ANAPC2                     9
UBN2                       8
...                      ...
WNT5A                      2
EIF2B1                     2
LRRIQ1                     2
SLC39A13                   2
SPTBN1                     2

[592 rows x 1 columns]
                       count
Target Genes Ensemble
MAGOHB                    14
ZNF512                    11
PSMD3                     11
LINC01963                 10
FREM1                     10
...                      ...
AGPAT3                     2
TXN2                       2
SOCS2                      2
STK25                      2
C12orf29                   2

[3125 rows x 1 columns]
____________________________________________________________________________________________________
cognse_path_slope

             count
TF_Ensemble
HINFP           68
RELB            67
ZNF574          54
ZNF429          47
HEY2            46
...            ...
ZNF674           2
ZNF276           2
RFX2             2
ZNF205           2
OLIG2            2

[501 rows x 1 columns]
             count
TF_Ensemble
HEY2            64
RUNX1           63
ZNF519          61
ZNF701          54
ZNF34           53
...            ...
CEBPA            2
ZIC4             2
ZNF443           2
GATA2            2
ZNF225           2

[590 rows x 1 columns]
                       count
Target Genes Ensemble
SNHG15                    12
ZNF335                    12
LCDR                       8
MROH7                      8
ZMPSTE24                   7
...                      ...
CCDC66                     2
WDR5                       2
MAN1C1                     2
CACNA1F                    2
ARHGAP24                   2

[749 rows x 1 columns]
                       count
Target Genes Ensemble
XRCC4                     14
FAM32A                    13
EIF4E2                    13
ZNF57                     13
SEC24C                    13
...                      ...
NUTF2                      2
ANKRD13A                   2
PGGHG                      2
PIN1                       2
ENSG00000280163            2

[1469 rows x 1 columns]
____________________________________________________________________________________________________
cognwo_path_slope

             count
TF_Ensemble
ZNF430          65
HES4            60
TBX18           56
MXI1            47
ZNF574          45
...            ...
MITF             2
ZNF525           2
SKOR1            2
ZNF41            2
THRB             2

[514 rows x 1 columns]
             count
TF_Ensemble
INSM1           84
KLF13           83
RELB            81
ZNF19           63
ATOH8           63
...            ...
PBX4             2
ZNF443           2
ZNF235           2
KLF6             2
FOXN2            2

[533 rows x 1 columns]
                       count
Target Genes Ensemble
DNAJC7                    13
SULT1C4                   11
MRPL27                    10
ZFYVE16                   10
CDC14A                     9
...                      ...
WHRN                       2
CPVL                       2
RGPD8                      2
VPS39                      2
ENSG00000271743            2

[967 rows x 1 columns]
                       count
Target Genes Ensemble
DPP8                      13
ENSG00000258674           12
ZNF57                     11
ZNF763                    10
GON4L                     10
...                      ...
TTC31                      2
PALD1                      2
LINC00937                  2
CD58                       2
SH3D19                     2

[874 rows x 1 columns]
____________________________________________________________________________________________________
cognpo_path_slope

             count
TF_Ensemble
CREM            79
ZBTB42          67
CREB3L4         67
ZBTB18          64
ZIC1            61
...            ...
ZSCAN5A          2
JDP2             2
PBX4             2
ZNF704           2
PBX2             2

[494 rows x 1 columns]
             count
TF_Ensemble
HEY2           134
ZNF582         128
ASCL1          128
EBF4           119
EBF3           119
...            ...
NEUROD2          2
ZNF296           2
NFKB2            2
MYCN             2
PBX1             2

[614 rows x 1 columns]
                       count
Target Genes Ensemble
ARG2                      14
MGME1                     13
UMPS                      13
NTHL1                     12
B3GAT3                    11
...                      ...
SIRT7                      2
PARG                       2
SLC25A48                   2
MERTK                      2
F5                         2

[1005 rows x 1 columns]
                       count
Target Genes Ensemble
AP2S1                     17
FAM32A                    15
EXOSC4                    15
GFOD1                     13
MYCBPAP                   13
...                      ...
PDLIM5                     2
PTGFRN                     2
PLEKHD1                    2
TXN2                       2
BACE1                      2

[2504 rows x 1 columns]
____________________________________________________________________________________________________
cognps_path_slope

             count
TF_Ensemble
CREB1           63
ZNF430          62
CREB3L4         59
ZNF528          53
CREM            42
...            ...
ZNF433           2
MITF             2
TP73             2
AIRE             2
PRDM16           2

[463 rows x 1 columns]
             count
TF_Ensemble
CEBPZ           96
ZFP28           95
ZNF3            89
MXI1            89
ZNF98           82
...            ...
ETV6             2
ZNF69            2
PKNOX2           2
NR1H2            2
TCF7L2           2

[509 rows x 1 columns]
                       count
Target Genes Ensemble
UMPS                      13
EFCAB14                   12
RIIAD1                    12
MAOA                      12
ID1                       11
...                      ...
RGS1                       2
DEPP1                      2
DHPS                       2
H3-3B                      2
PODNL1                     2

[666 rows x 1 columns]
                       count
Target Genes Ensemble
Y_RNA                     18
HPS5                      15
CLPB                      13
ENSG00000276115           12
CSNK1A1                   10
...                      ...
RDH14                      2
ENSG00000260261            2
VANGL2                     2
SLC25A35                   2
CPT2                       2

[1102 rows x 1 columns]
____________________________________________________________________________________________________
cognep_path_slope

             count
TF_Ensemble
ZNF574          95
ATOH8           90
MXI1            88
RXRB            80
RXRG            79
...            ...
ZNF487           2
ZNF554           2
ZBTB12           2
GABPA            2
OLIG2            2

[579 rows x 1 columns]
             count
TF_Ensemble
SP2             87
HIVEP2          60
ZNF701          58
MAX             56
ZNF574          56
...            ...
ZFHX3            2
MESP2            2
AHRR             2
AHR              2
CREB3            2

[540 rows x 1 columns]
                       count
Target Genes Ensemble
LOXL3                     14
MAOA                      13
SCAMP2                    13
CLSTN2                    13
TRIP6                     13
...                      ...
ENSG00000262529            2
NSUN5                      2
ENPEP                      2
GOLGA5                     2
BRAP                       2

[1604 rows x 1 columns]
                       count
Target Genes Ensemble
RNF7                      11
ZSCAN16-AS1               11
ZNHIT2                     9
RBM42                      9
ZNHIT1                     9
...                      ...
ENSG00000272444            2
ENSG00000280332            2
MSH3                       2
ZMYND19                    2
HIPK1-AS1                  2

[1008 rows x 1 columns]
____________________________________________________________________________________________________
cognpo_demog_slope

             count
TF_Ensemble
ZIC1            68
ZIC2            66
ZNF574          63
ZNF140          56
SP2             52
...            ...
NPAS2            2
ZNF454           2
TOPORS           2
CLOCK            2
TBX15            2

[511 rows x 1 columns]
             count
TF_Ensemble
GLIS2          116
ZNF580         112
EBF3           105
EBF4           105
HINFP           91
...            ...
E2F4             2
ZNF574           2
ZNF219           2
RARG             2
ATF7             2

[612 rows x 1 columns]
                       count
Target Genes Ensemble
ZNF335                    12
LRRC8A                    11
SLC26A11                  11
TMEM39A                   11
UMPS                      11
...                      ...
STT3B                      2
TRPC4AP                    2
ENSG00000264304            2
SCRG1                      2
SHISA5P2                   2

[1086 rows x 1 columns]
                       count
Target Genes Ensemble
AP2S1                     18
FAM32A                    16
DAPK3                     13
DDX60L                    12
GFOD1                     12
...                      ...
SMYD3                      2
VCP                        2
ENSG00000265791            2
YPEL4                      2
PLA2G6                     2

[2484 rows x 1 columns]
____________________________________________________________________________________________________
cogng_path_slope

             count
TF_Ensemble
ZNF574          98
MXI1            75
ATOH8           68
NFE2L2          62
MAX             61
...            ...
SPDEF            2
RORB             2
CUX2             2
TBX2             2
TBX1             2

[528 rows x 1 columns]
             count
TF_Ensemble
SP2            101
ZNF574          82
ZNF143          69
ZNF2            65
BHLHE41         63
...            ...
TCF15            2
THRA             2
ZNF224           2
IRF8             2
FOSL1            2

[538 rows x 1 columns]
                       count
Target Genes Ensemble
TRIP6                     13
LRRC8A                    13
LOXL3                     13
DNAJC7                    13
MGME1                     12
...                      ...
OLA1                       2
EIF3L                      2
DCAF12                     2
NNAT                       2
SLC9A9                     2

[1129 rows x 1 columns]
                       count
Target Genes Ensemble
POT1-AS1                  12
FSTL4                     12
ZNF57                     11
RNF7                      11
AP3S2                     11
...                      ...
ATP13A2                    2
TMEM167B                   2
PARD3                      2
CEP162                     2
PMS2P3                     2

[1078 rows x 1 columns]
____________________________________________________________________________________________________
cognep_demog_slope

             count
TF_Ensemble
MAX            124
MXI1           100
KLF8            84
ZFP14           83
ATOH8           81
...            ...
REST             2
SOX18            2
OXSR1            2
ZBTB2            2
ZNF585A          2

[535 rows x 1 columns]
             count
TF_Ensemble
KLF8            84
ZNF701          70
ZNF768          50
HIVEP2          46
MXI1            45
...            ...
GLI3             2
ZNF527           2
YBX1             2
ZIC5             2
ZNF540           2

[570 rows x 1 columns]
                       count
Target Genes Ensemble
WDR35                     15
ERI2                      13
ZNF335                    12
CTDP1                     11
ENSG00000279088           10
...                      ...
FBXO7                      2
BCAS4                      2
PALD1                      2
XRCC4                      2
PPM1A                      2

[1405 rows x 1 columns]
                       count
Target Genes Ensemble
UBE2H                     12
ZSWIM3                    12
HPS5                       9
GPANK1                     9
LCORL                      9
...                      ...
RMND5A                     2
TMEM167B                   2
RBM11                      2
B3GALT5                    2
RPUSD4                     2

[1078 rows x 1 columns]
____________________________________________________________________________________________________
cognps_demog_slope

             count
TF_Ensemble
ZNF582          45
ZNF528          41
MAX             36
ZNF429          33
ZNF430          31
...            ...
FEZF2            2
ZNF419           2
ELF2             2
ZNF584           2
ZNF449           2

[490 rows x 1 columns]
             count
TF_Ensemble
ZNF626         113
ZNF641          92
ZNF671          92
MXI1            83
ZSCAN5A         74
...            ...
ZNF554           2
DMRT2            2
ZBTB37           2
ZNF524           2
PBX4             2

[564 rows x 1 columns]
                       count
Target Genes Ensemble
GTF2IP13                  12
PDE7A                     11
ZNF335                    10
PDE4A                      9
PPP1R9A                    9
...                      ...
COL4A2                     2
ZNF221                     2
GMPR                       2
CACNA1D                    2
TEX9                       2

[561 rows x 1 columns]
                       count
Target Genes Ensemble
Y_RNA                     19
ENSG00000279917           12
ENSG00000260038           11
MYCBPAP                    9
PAPSS1                     9
...                      ...
ENSG00000280088            2
DALRD3                     2
CCDC124                    2
IL18R1                     2
MAP4K4                     2

[1615 rows x 1 columns]
____________________________________________________________________________________________________
cogng_demog_slope

             count
TF_Ensemble
MAX            139
ZNF574          91
ZNF589          64
ZNF501          64
KLF8            61
...            ...
ZNF785           2
SOX21            2
ZNF454           2
FOXO6            2
ATF4             2

[501 rows x 1 columns]
             count
TF_Ensemble
ZNF480          59
ZNF16           57
HEY2            49
ZNF701          45
RELB            40
...            ...
ZNF669           2
ZNF749           2
ZNF264           2
MESP2            2
MBNL2            2

[539 rows x 1 columns]
                       count
Target Genes Ensemble
ZNF335                    11
TMEM39A                   10
ZNF585B                    9
HINT3                      8
PDE4A                      8
...                      ...
SLC27A2                    2
LINC01114                  2
CLEC2D                     2
TARBP2                     2
MMRN2                      2

[1076 rows x 1 columns]
                       count
Target Genes Ensemble
UBE2H                     11
GPANK1                     9
ENSG00000271780            9
ITM2C                      9
SYNJ2BP                    8
...                      ...
CABYR                      2
STRADA                     2
SBNO1-AS1                  2
EID2B                      2
APEX2                      2

[906 rows x 1 columns]
____________________________________________________________________________________________________

# GSEA preranking on absolute difference

In [35]:
corr_dataframe_dict_per_clinical.keys()

dict_keys(['synap_6_synaptophys', 'synap_6_snap25', 'synap_6_complex1', 'zcomplexin_6', 'synap_6_vamp', 'zsnare_6', 'synap_6_complex2', 'zcapture_syn_6', 'synap_6_syntaxin', 'pmi', 'cognwo_demog_slope', 'cognse_demog_slope', 'cognse_path_slope', 'cognwo_path_slope', 'cognpo_path_slope', 'cognps_path_slope', 'cognep_path_slope', 'cognpo_demog_slope', 'tangsqrt_est_8reg', 'age_death', 'cogng_path_slope', 'cognep_demog_slope', 'nft', 'cognps_demog_slope', 'plaq_n', 'cogng_demog_slope', 'amylsqrt_est_8reg', 'age_bl', 'plaq_d', 'gpath'])

In [36]:
corr_dataframe_dict_per_clinical.keys()

dict_keys(['synap_6_synaptophys', 'synap_6_snap25', 'synap_6_complex1', 'zcomplexin_6', 'synap_6_vamp', 'zsnare_6', 'synap_6_complex2', 'zcapture_syn_6', 'synap_6_syntaxin', 'pmi', 'cognwo_demog_slope', 'cognse_demog_slope', 'cognse_path_slope', 'cognwo_path_slope', 'cognpo_path_slope', 'cognps_path_slope', 'cognep_path_slope', 'cognpo_demog_slope', 'tangsqrt_est_8reg', 'age_death', 'cogng_path_slope', 'cognep_demog_slope', 'nft', 'cognps_demog_slope', 'plaq_n', 'cogng_demog_slope', 'amylsqrt_est_8reg', 'age_bl', 'plaq_d', 'gpath'])

In [37]:
clinical_cog_var

['cognwo_demog_slope',
 'cognse_demog_slope',
 'cognse_path_slope',
 'cognwo_path_slope',
 'cognpo_path_slope',
 'cognps_path_slope',
 'cognep_path_slope',
 'cognpo_demog_slope',
 'cogng_path_slope',
 'cognep_demog_slope',
 'cognps_demog_slope',
 'cogng_demog_slope']

In [38]:
corr_dataframe_dict_per_clinical['cognwo_demog_slope'][['clinical_variables','TF_Ensemble','Target Genes Ensemble','AD_correlation_value','NCI_correlation_value','abs_diff']]

,clinical_variables,TF_Ensemble,Target Genes Ensemble,AD_correlation_value,NCI_correlation_value,abs_diff
2416,cognwo_demog_slope,ESR1,RPL7A,-0.433604,0.404601,0.838205
3518334,cognwo_demog_slope,TOPORS,L3MBTL2-AS1,0.303297,-0.379164,0.682462
3351737,cognwo_demog_slope,ZNF224,ENSG00000261329,0.198216,-0.468588,0.666804
3518947,cognwo_demog_slope,TBX3,PCDHGA10,0.304268,-0.358382,0.662650
3502392,cognwo_demog_slope,EGR4,ATG9A,0.282317,-0.371602,0.653919
...,...,...,...,...,...,...
929749,cognwo_demog_slope,MAF,PRSS16,-0.075949,-0.075939,0.000010
2235967,cognwo_demog_slope,ZNF879,GTF2IP12,0.040921,0.040931,0.000009
2902219,cognwo_demog_slope,NFYB,WDR19,0.110885,0.110894,0.000008
1508313,cognwo_demog_slope,CLOCK,PIWIL2,-0.021793,-0.021787,0.000006
2770347,cognwo_demog_slope,SREBF1,RSF1,0.094603,0.094606,0.000003

In [39]:
for i in corr_dataframe_dict_per_clinical.keys():
    corr_dataframe_dict_per_clinical[i]=  corr_dataframe_dict_per_clinical[i][['clinical_variables','TF_Ensemble','Target Genes Ensemble','AD_correlation_value','NCI_correlation_value','abs_diff']]

In [40]:
corr_dataframe_dict_per_clinical['cognwo_demog_slope']

,clinical_variables,TF_Ensemble,Target Genes Ensemble,AD_correlation_value,NCI_correlation_value,abs_diff
2416,cognwo_demog_slope,ESR1,RPL7A,-0.433604,0.404601,0.838205
3518334,cognwo_demog_slope,TOPORS,L3MBTL2-AS1,0.303297,-0.379164,0.682462
3351737,cognwo_demog_slope,ZNF224,ENSG00000261329,0.198216,-0.468588,0.666804
3518947,cognwo_demog_slope,TBX3,PCDHGA10,0.304268,-0.358382,0.662650
3502392,cognwo_demog_slope,EGR4,ATG9A,0.282317,-0.371602,0.653919
...,...,...,...,...,...,...
929749,cognwo_demog_slope,MAF,PRSS16,-0.075949,-0.075939,0.000010
2235967,cognwo_demog_slope,ZNF879,GTF2IP12,0.040921,0.040931,0.000009
2902219,cognwo_demog_slope,NFYB,WDR19,0.110885,0.110894,0.000008
1508313,cognwo_demog_slope,CLOCK,PIWIL2,-0.021793,-0.021787,0.000006
2770347,cognwo_demog_slope,SREBF1,RSF1,0.094603,0.094606,0.000003

In [41]:
gene_sets = ['GO_Molecular_Function_2023','GO_Cellular_Component_2023','GO_Biological_Process_2023','KEGG_2021_Human','Reactome_Pathways_2024','Reactome_2022']



def return_gseapy_obj(gene_rank, gene_set):
    
    pre_res = gp.prerank(rnk=gene_rank, # or rnk = rnk,
                     gene_sets=gene_set,
                     threads=4,
                     min_size=5,
                     max_size=1000,
                     permutation_num=1000, # reduce number to speed up testing
                     outdir=None, # don't write to disk
                     seed=6,
                     verbose=True, # see what's going on behind the scenes
                    )
    return pre_res

In [42]:


for i in clinical_cog_var:
    print(i)
    corr_dataframe_dict_per_clinical[i]['abs_AD_correlation_value'] = corr_dataframe_dict_per_clinical[i]['AD_correlation_value'].abs()
    corr_dataframe_dict_per_clinical[i]['abs_NCI_correlation_value'] = corr_dataframe_dict_per_clinical[i]['NCI_correlation_value'].abs()

    ad_sort = corr_dataframe_dict_per_clinical[i].sort_values(by = 'abs_AD_correlation_value', ascending = False)
    ad_sort = ad_sort[['Target Genes Ensemble','abs_AD_correlation_value']].set_index('Target Genes Ensemble').rename(columns = {'abs_AD_correlation_value':1})
    
    nci_sort = corr_dataframe_dict_per_clinical[i].sort_values(by = 'abs_NCI_correlation_value', ascending = False)
    nci_sort = nci_sort[['Target Genes Ensemble','abs_NCI_correlation_value']].set_index('Target Genes Ensemble').rename(columns = {'abs_NCI_correlation_value':1})
    
    ad_nci_diff_sort = corr_dataframe_dict_per_clinical[i].sort_values(by = 'abs_diff', ascending = False)
    
    ad_nci_diff_sort =    ad_nci_diff_sort[['Target Genes Ensemble','abs_diff']].set_index('Target Genes Ensemble').rename(columns = {'abs_diff':1})
    print(ad_nci_diff_sort)
    break

cognwo_demog_slope
                              1
Target Genes Ensemble
RPL7A                  0.838205
L3MBTL2-AS1            0.682462
ENSG00000261329        0.666804
PCDHGA10               0.662650
ATG9A                  0.653919
...                         ...
PRSS16                 0.000010
GTF2IP12               0.000009
WDR19                  0.000008
PIWIL2                 0.000006
RSF1                   0.000003

[118489 rows x 1 columns]

/tmp/ipykernel_541344/1552502769.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['abs_AD_correlation_value'] = corr_dataframe_dict_per_clinical[i]['AD_correlation_value'].abs()
/tmp/ipykernel_541344/1552502769.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  corr_dataframe_dict_per_clinical[i]['abs_NCI_correlation_value'] = corr_dataframe_dict_per_clinical[i]['NCI_correlation_value'].abs()

In [43]:
for i in clinical_cog_var:
    print(i)
    print("AD TF: ",len(AD_tf_list[i]))
    print("NCI TF: ",len(NCI_tf_list[i]))
    print("AD Genes: ",len(AD_target_genes_list[i]))
    print("NCI Genes: ",len(NCI_target_genes_list[i]))

cognwo_demog_slope
AD TF:  576
NCI TF:  585
AD Genes:  3488
NCI Genes:  4264
cognse_demog_slope
AD TF:  548
NCI TF:  656
AD Genes:  2500
NCI Genes:  6709
cognse_path_slope
AD TF:  584
NCI TF:  630
AD Genes:  2887
NCI Genes:  4214
cognwo_path_slope
AD TF:  590
NCI TF:  587
AD Genes:  3203
NCI Genes:  3388
cognpo_path_slope
AD TF:  570
NCI TF:  643
AD Genes:  3204
NCI Genes:  5700
cognps_path_slope
AD TF:  568
NCI TF:  581
AD Genes:  2526
NCI Genes:  3706
cognep_path_slope
AD TF:  613
NCI TF:  607
AD Genes:  4560
NCI Genes:  3422
cognpo_demog_slope
AD TF:  579
NCI TF:  644
AD Genes:  3520
NCI Genes:  5693
cogng_path_slope
AD TF:  596
NCI TF:  599
AD Genes:  3590
NCI Genes:  3528
cognep_demog_slope
AD TF:  603
NCI TF:  607
AD Genes:  4299
NCI Genes:  3360
cognps_demog_slope
AD TF:  569
NCI TF:  614
AD Genes:  2232
NCI Genes:  4582
cogng_demog_slope
AD TF:  581
NCI TF:  602
AD Genes:  3630
NCI Genes:  3031

In [44]:
import pandas as pd
import gseapy as gp
import matplotlib.pyplot as plt

In [45]:
ad_sort

                              1
Target Genes Ensemble
RGS6                   0.444399
ATG12                  0.440899
ATG12                  0.440583
RPL7A                  0.433604
ZDHHC11                0.428997
...                         ...
IFNGR1                 0.000000
ABRAXAS2               0.000000
RPLP2                  0.000000
TPP2                   0.000000
EAPP                   0.000000

[118489 rows x 1 columns]

In [46]:
import pandas as pd
import gseapy as gp
import matplotlib.pyplot as plt
from gseapy import Biomart
bm = Biomart()

In [47]:
for i in clinical_cog_var:
    print(i)
    li = [item for item in AD_target_genes_list[i] if item is not None]
    li_2 = [item for item in NCI_target_genes_list[i] if item is not None]

    #m = set(li).union(li_2)
    #n = set(li).intersection(li_2)

    #k  = m - n
    k = list(set(li)- set(li_2))
    print(len(k))
    enr = gp.enrichr(gene_list= k, # or "./tests/data/gene_list.txt",
                     gene_sets=['GO_Cellular_Component_2023'],
                     organism='human', # don't forget to set organism to the one you desired! e.g. Yeast
                     outdir=None, # don't write to disk
                    )
    print(enr.results[enr.results['Adjusted P-value']<=0.05])

cognwo_demog_slope
2379
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognse_demog_slope
1369
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognse_path_slope
2041
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognwo_path_slope
2370
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognpo_path_slope
1898
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognps_path_slope
1835
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognep_path_slope
3425
                     Gene_set                               Term  Overlap  \
0  GO_Cellular_Component_2023     Neuron Projection (GO:0043005)  132/557
1  GO_Cellular_Component_2023              Dendrite (GO:0030425)   72/270
2  GO_Cellular_Component_2023                  Axon (GO:0030424)   57/205
3  GO_Cellular_Component_2023          Cytoskeleton (GO:0005856)  134/599
4  GO_Cellular_Component_2023            Sarcolemma (GO:0042383)    19/52
5  GO_Cellular_Component_2023  Postsynaptic Density (GO:0014069)   42/151

    P-value  Adjusted P-value  Old P-value  Old Adjusted P-value  Odds Ratio  \
0  0.000038          0.010857            0                     0    1.523231
1  0.000050          0.010857            0                     0    1.776103
2  0.000087          0.012498            0                     0    1.878449
3  0.000484          0.049384            0                     0    1.410651
4  0.000625          0.049384            0                     0    2.796295
5  0.000687          0.049384            0                     0    1.875465

   Combined Score                                              Genes
0       15.519791  EPHB6;APP;RAB3A;CPNE6;STMN2;STMN3;CIB1;KNDC1;H...
1       17.576182  EPHB6;CNTNAP2;GSK3B;TENM2;GSK3A;KCNC2;LRRK2;CP...
2       17.562913  APP;CNTNAP2;GSK3B;ROBO4;GSK3A;RAB3A;KCNC2;LRRK...
3       10.769013  RIPOR2;WIPF1;FHOD1;CLU;MYLK3;MYLK;MAEA;BASP1;C...
4       20.631597  ITGB1;MLIP;CCDC78;AHNAK2;SLC2A1;DTNBP1;CIB1;AN...
5       13.658038  GRIA1;RTN3;MTMR2;RTN1;GRIK3;GRIK2;PPP1R9A;ADD3...
cognpo_demog_slope
2124
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cogng_path_slope
2672
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognep_demog_slope
3295
                     Gene_set  \
0  GO_Cellular_Component_2023
1  GO_Cellular_Component_2023

                                                Term Overlap   P-value  \
0                Lytic Vacuole Membrane (GO:0098852)  72/287  0.000115
1  Cytoskeleton Of Presynaptic Active Zone (GO:00...     6/7  0.000120

   Adjusted P-value  Old P-value  Old Adjusted P-value  Odds Ratio  \
0          0.025692            0                     0    1.713383
1          0.025692            0                     0   30.472484

   Combined Score                                              Genes
0       15.539490  SCARB2;ABCD4;SLC48A1;SLC35F6;SCARB1;IFITM2;SPA...
1      275.162787                  RIMS2;RIMS1;RIMS4;PCLO;RIMS3;ERC2
cognps_demog_slope
1529
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cogng_demog_slope
2848
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []

In [48]:
for i in clinical_cog_var:
    print(i)
    li = [item for item in AD_target_genes_list[i] if item is not None]
    li_2 = [item for item in NCI_target_genes_list[i] if item is not None]

    #m = set(li).union(li_2)
    #n = set(li).intersection(li_2)

    #k  = m - n
    k = list(set(li)- set(li_2))
    print(len(k))
    enr = gp.enrichr(gene_list= k, # or "./tests/data/gene_list.txt",
                     gene_sets=['Reactome_2022'],
                     organism='human', # don't forget to set organism to the one you desired! e.g. Yeast
                     outdir=None, # don't write to disk
                    )
    print(enr.results[enr.results['Adjusted P-value']<=0.05])

cognwo_demog_slope
2379
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognse_demog_slope
1369
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognse_path_slope
2041
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognwo_path_slope
2370
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognpo_path_slope
1898
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognps_path_slope
1835
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognep_path_slope
3425
        Gene_set                                            Term  Overlap  \
0  Reactome_2022               Membrane Trafficking R-HSA-199991  142/599
1  Reactome_2022   COPII-mediated Vesicle Transport R-HSA-204005    25/66
2  Reactome_2022        Vesicle-mediated Transport R-HSA-5653656  147/637
3  Reactome_2022  ER To Golgi Anterograde Transport R-HSA-199977   41/133

    P-value  Adjusted P-value  Old P-value  Old Adjusted P-value  Odds Ratio  \
0  0.000019          0.029536            0                     0    1.525501
1  0.000047          0.029536            0                     0    2.965208
2  0.000057          0.029536            0                     0    1.472087
3  0.000072          0.029536            0                     0    2.170711

   Combined Score                                              Genes
0       16.577919  USP6NL;APP;SH3GL3;RAB3A;GOLIM4;FNBP1L;GOLGA2;G...
1       29.572834  GRIA1;MCFD2;LMAN2L;USO1;GOLGA2;SCFD1;STX5;SEC3...
2       14.378057  USP6NL;APP;SH3GL3;RAB3A;SPARC;GOLIM4;FNBP1L;GO...
3       20.720725  GRIA1;COPB2;DCTN5;COPA;SPTBN5;MCFD2;LMAN2L;COP...
cognpo_demog_slope
2124
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cogng_path_slope
2672
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cognep_demog_slope
3295
         Gene_set                                               Term  Overlap  \
0   Reactome_2022                    Metabolism Of RNA R-HSA-8953854  159/666
1   Reactome_2022  Processing Of Capped Intron-Containing Pre-mRN...   65/242
2   Reactome_2022                          mRNA Splicing R-HSA-72172   53/189
3   Reactome_2022  Formation Of A Pool Of Free 40S Subunits R-HSA...    32/98
4   Reactome_2022              Peptide Chain Elongation R-HSA-156902    29/86
5   Reactome_2022  SRP-dependent Cotranslational Protein Targetin...   34/108
6   Reactome_2022                        rRNA Processing R-HSA-72312   54/199
7   Reactome_2022  GTP Hydrolysis And Joining Of 60S Ribosomal Su...   34/109
8   Reactome_2022  Major Pathway Of rRNA Processing In Nucleolus ...   49/179
9   Reactome_2022     Eukaryotic Translation Elongation R-HSA-156842    29/90
10  Reactome_2022     Eukaryotic Translation Termination R-HSA-72764    29/90
11  Reactome_2022             Selenocysteine Synthesis R-HSA-2408557    29/90
12  Reactome_2022                Viral mRNA Translation R-HSA-192823    29/90
13  Reactome_2022  L13a-mediated Translational Silencing Of Cerul...   33/108
14  Reactome_2022          mRNA Splicing - Major Pathway R-HSA-72163   49/181
15  Reactome_2022  Response Of EIF2AK4 (GCN2) To Amino Acid Defic...    30/98
16  Reactome_2022   Cap-dependent Translation Initiation R-HSA-72737   34/116
17  Reactome_2022      Cellular Response To Starvation R-HSA-9711097   42/153
18  Reactome_2022  Nonsense Mediated Decay (NMD) Enhanced By Exon...   33/112
19  Reactome_2022  Conversion From APC/C:Cdc20 To APC/C:Cdh1 In L...    10/20
20  Reactome_2022  Influenza Viral RNA Transcription And Replicat...   38/137
21  Reactome_2022  rRNA Processing In Nucleus And Cytosol R-HSA-8...   49/189
22  Reactome_2022  Nonsense Mediated Decay (NMD) Independent Of E...    28/92

         P-value  Adjusted P-value  Old P-value  Old Adjusted P-value  \
0   3.830956e-07          0.000616            0                     0
1   2.727461e-05          0.020702            0                     0
2   4.189463e-05          0.020702            0                     0
3   6.132697e-05          0.020702            0                     0
4   6.942786e-05          0.020702            0                     0
5   8.406196e-05          0.020702            0                     0
6   9.343438e-05          0.020702            0                     0
7   1.030588e-04          0.020702            0                     0
8   1.527598e-04          0.021353            0                     0
9   1.727413e-04          0.021353            0                     0
10  1.727413e-04          0.021353            0                     0
11  1.727413e-04          0.021353            0                     0
12  1.727413e-04          0.021353            0                     0
13  1.999072e-04          0.021884            0                     0
14  2.042646e-04          0.021884            0                     0
15  3.679195e-04          0.035466            0                     0
16  3.848872e-04          0.035466            0                     0
17  4.080925e-04          0.035466            0                     0
18  4.193199e-04          0.035466            0                     0
19  5.399741e-04          0.043387            0                     0
20  6.033236e-04          0.044002            0                     0
21  6.040956e-04          0.044002            0                     0
22  6.297774e-04          0.044002            0                     0

    Odds Ratio  Combined Score  \
0     1.619849       23.933237
1     1.879135       19.748866
2     1.991683       20.076869
3     2.472386       23.980386
4     2.593397       24.832354
5     2.343229       21.988760
6     1.902861       17.655222
7     2.311847       21.223243
8     1.924677       16.911447
9     2.422756       20.990068
10    2.422756       20.990068
11    2.422756       20.990068
12    2.422756       20.990068
13    2.243164       19.106499
14    1.895286       16.102529
15    2.248041       17.776711
16    2.113604       16.618341
17    1.930160       15.063002
18    2.129074       16.557542
19    5.082192       38.238357
20    1.957022       14.507514
21    1.786121       13.238335
22    2.228478       16.424204

                                                Genes
0   RPL4;RPL5;RPL30;RPL32;RPL31;PDCD7;RPL34;FCF1;H...
1   DDX46;PDCD7;PPWD1;HNRNPR;ELAVL1;ELAVL2;CCAR1;E...
2   DDX46;PDCD7;PPWD1;HNRNPR;ELAVL1;ELAVL2;CCAR1;E...
3   RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
4   RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
5   RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
6   RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;FCF1;RPL7;RR...
7   RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
8   RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;FCF1;RPL7;RR...
9   RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
10  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;APEH;R...
11  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
12  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
13  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
14  DDX46;PPWD1;HNRNPR;ELAVL1;ELAVL2;CCAR1;EFTUD2;...
15  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
16  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
17  RPL4;RPL5;RPL30;SEH1L;RPL32;RPL31;RPL34;RPL11;...
18  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;SMG5;R...
19  FZR1;CDC23;ANAPC16;UBE2S;CDC16;UBE2E1;UBE2D1;C...
20  RPL4;RPL5;RPL30;NUP205;SEH1L;RPL32;RPL31;RPL34...
21  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;FCF1;RPL7;RR...
22  RPL4;RPL5;RPL30;RPL32;RPL31;RPL34;RPL11;RPL7;R...
cognps_demog_slope
1529
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []
cogng_demog_slope
2848
Empty DataFrame
Columns: [Gene_set, Term, Overlap, P-value, Adjusted P-value, Old P-value, Old Adjusted P-value, Odds Ratio, Combined Score, Genes]
Index: []

# identified edges correlation

In [49]:
ad_corr_22 = pd.read_csv('../../../data_preprocessed/correlation_output/ad_22_edges_corr.csv')
nci_corr_22 = pd.read_csv('../../../data_preprocessed/correlation_output/nci_22_edges_corr.csv')

In [50]:
ad_corr_22

,0,AD_correlation_value,P_value_AD
0,cognep_demog_slope_ENSG00000166823_ENSG0000017...,-0.237895,0.032469
1,cognep_path_slope_ENSG00000188786_ENSG00000083799,-0.238029,0.042574
2,cogng_demog_slope_ENSG00000169635_ENSG00000234841,-0.234982,0.034718
3,cogng_path_slope_ENSG00000168874_ENSG00000139197,-0.239356,0.041399
4,cognpo_demog_slope_ENSG00000234284_ENSG0000014...,0.259939,0.019883
5,cognse_demog_slope_ENSG00000169635_ENSG0000023...,-0.265049,0.017500
6,cognse_demog_slope_ENSG00000234284_ENSG0000014...,0.237717,0.033730
7,cognwo_demog_slope_ENSG00000162992_ENSG0000013...,-0.239250,0.031466
8,cognwo_demog_slope_ENSG00000168874_ENSG0000013...,-0.270867,0.014452
9,cognwo_demog_slope_ENSG00000169635_ENSG0000023...,-0.266283,0.016268
10,cognwo_demog_slope_ENSG00000234284_ENSG0000014...,0.234666,0.034970
11,cognwo_path_slope_ENSG00000169635_ENSG00000234841,-0.256171,0.028700

In [51]:
m = []
for i in nci_corr_22['0'].tolist():
    k = i.split('_')[0:3]
    m.append(('_'.join(k)))

nci_corr_22['cog_decline'] = m

In [64]:
m = []
n = []
for i in ad_corr_22['0'].tolist():
    k = i.split('_')[0:3]
    j = i.split('_')[3:]
    m.append(('_'.join(k)))
    n.append(('_'.join(j)))
    

ad_corr_22['cog_decline'] = m
ad_corr_22['edge'] = n

In [65]:
nci_corr_22

,0,NCI_correlation_value,P_value_NCI,cog_decline
0,cognep_demog_slope_ENSG00000079432_ENSG0000018...,0.256372,0.046111,cognep_demog_slope
1,cognep_path_slope_ENSG00000079432_ENSG00000188234,0.261991,0.048987,cognep_path_slope
2,cognep_path_slope_ENSG00000167981_ENSG00000143222,-0.318512,0.015749,cognep_path_slope
3,cogng_demog_slope_ENSG00000198482_ENSG00000156219,0.258329,0.044417,cogng_demog_slope
4,cogng_path_slope_ENSG00000167981_ENSG00000143222,-0.318706,0.015681,cogng_path_slope
5,cognpo_demog_slope_ENSG00000125850_ENSG0000019...,0.331327,0.010366,cognpo_demog_slope
6,cognpo_path_slope_ENSG00000166823_ENSG00000178199,-0.284416,0.035334,cognpo_path_slope
7,cognps_demog_slope_ENSG00000028277_ENSG0000003...,-0.265283,0.042293,cognps_demog_slope
8,cognps_demog_slope_ENSG00000234284_ENSG0000014...,0.370251,0.003896,cognps_demog_slope
9,cognps_path_slope_ENSG00000234284_ENSG00000149089,0.331313,0.013478,cognps_path_slope
10,cognse_demog_slope_ENSG00000166823_ENSG0000017...,-0.278784,0.032504,cognse_demog_slope
11,cognse_path_slope_ENSG00000167981_ENSG00000143222,-0.285498,0.034612,cognse_path_slope
12,cognwo_demog_slope_ENSG00000028277_ENSG0000003...,-0.306399,0.016323,cognwo_demog_slope

In [66]:
ad_corr_22

,0,AD_correlation_value,P_value_AD,cog_decline,edge
0,cognep_demog_slope_ENSG00000166823_ENSG0000017...,-0.237895,0.032469,cognep_demog_slope,ENSG00000166823_ENSG00000178199
1,cognep_path_slope_ENSG00000188786_ENSG00000083799,-0.238029,0.042574,cognep_path_slope,ENSG00000188786_ENSG00000083799
2,cogng_demog_slope_ENSG00000169635_ENSG00000234841,-0.234982,0.034718,cogng_demog_slope,ENSG00000169635_ENSG00000234841
3,cogng_path_slope_ENSG00000168874_ENSG00000139197,-0.239356,0.041399,cogng_path_slope,ENSG00000168874_ENSG00000139197
4,cognpo_demog_slope_ENSG00000234284_ENSG0000014...,0.259939,0.019883,cognpo_demog_slope,ENSG00000234284_ENSG00000149089
5,cognse_demog_slope_ENSG00000169635_ENSG0000023...,-0.265049,0.017500,cognse_demog_slope,ENSG00000169635_ENSG00000234841
6,cognse_demog_slope_ENSG00000234284_ENSG0000014...,0.237717,0.033730,cognse_demog_slope,ENSG00000234284_ENSG00000149089
7,cognwo_demog_slope_ENSG00000162992_ENSG0000013...,-0.239250,0.031466,cognwo_demog_slope,ENSG00000162992_ENSG00000139197
8,cognwo_demog_slope_ENSG00000168874_ENSG0000013...,-0.270867,0.014452,cognwo_demog_slope,ENSG00000168874_ENSG00000139197
9,cognwo_demog_slope_ENSG00000169635_ENSG0000023...,-0.266283,0.016268,cognwo_demog_slope,ENSG00000169635_ENSG00000234841
10,cognwo_demog_slope_ENSG00000234284_ENSG0000014...,0.234666,0.034970,cognwo_demog_slope,ENSG00000234284_ENSG00000149089
11,cognwo_path_slope_ENSG00000169635_ENSG00000234841,-0.256171,0.028700,cognwo_path_slope,ENSG00000169635_ENSG00000234841

In [55]:
len(set(ad_corr_22.cog_decline).intersection(set(nci_corr_22.cog_decline)))

7

In [56]:
set(nci_corr_22.cog_decline).union(set(ad_corr_22.cog_decline))

{'cognep_demog_slope',
 'cognep_path_slope',
 'cogng_demog_slope',
 'cogng_path_slope',
 'cognpo_demog_slope',
 'cognpo_path_slope',
 'cognps_demog_slope',
 'cognps_path_slope',
 'cognse_demog_slope',
 'cognse_path_slope',
 'cognwo_demog_slope',
 'cognwo_path_slope'}

In [57]:
ad_corr_22.cog_decline.value_counts()

cog_decline
cognwo_demog_slope    4
cognse_demog_slope    2
cognep_demog_slope    1
cognep_path_slope     1
cogng_path_slope      1
cogng_demog_slope     1
cognpo_demog_slope    1
cognwo_path_slope     1
Name: count, dtype: int64

In [59]:
nci_corr_22

,0,NCI_correlation_value,P_value_NCI,cog_decline
0,cognep_demog_slope_ENSG00000079432_ENSG0000018...,0.256372,0.046111,cognep_demog_slope
1,cognep_path_slope_ENSG00000079432_ENSG00000188234,0.261991,0.048987,cognep_path_slope
2,cognep_path_slope_ENSG00000167981_ENSG00000143222,-0.318512,0.015749,cognep_path_slope
3,cogng_demog_slope_ENSG00000198482_ENSG00000156219,0.258329,0.044417,cogng_demog_slope
4,cogng_path_slope_ENSG00000167981_ENSG00000143222,-0.318706,0.015681,cogng_path_slope
5,cognpo_demog_slope_ENSG00000125850_ENSG0000019...,0.331327,0.010366,cognpo_demog_slope
6,cognpo_path_slope_ENSG00000166823_ENSG00000178199,-0.284416,0.035334,cognpo_path_slope
7,cognps_demog_slope_ENSG00000028277_ENSG0000003...,-0.265283,0.042293,cognps_demog_slope
8,cognps_demog_slope_ENSG00000234284_ENSG0000014...,0.370251,0.003896,cognps_demog_slope
9,cognps_path_slope_ENSG00000234284_ENSG00000149089,0.331313,0.013478,cognps_path_slope
10,cognse_demog_slope_ENSG00000166823_ENSG0000017...,-0.278784,0.032504,cognse_demog_slope
11,cognse_path_slope_ENSG00000167981_ENSG00000143222,-0.285498,0.034612,cognse_path_slope
12,cognwo_demog_slope_ENSG00000028277_ENSG0000003...,-0.306399,0.016323,cognwo_demog_slope

In [76]:
ad_corr_22

,0,AD_correlation_value,P_value_AD,cog_decline,edge
0,cognep_demog_slope_ENSG00000166823_ENSG0000017...,-0.237895,0.032469,cognep_demog_slope,ENSG00000166823_ENSG00000178199
1,cognep_path_slope_ENSG00000188786_ENSG00000083799,-0.238029,0.042574,cognep_path_slope,ENSG00000188786_ENSG00000083799
2,cogng_demog_slope_ENSG00000169635_ENSG00000234841,-0.234982,0.034718,cogng_demog_slope,ENSG00000169635_ENSG00000234841
3,cogng_path_slope_ENSG00000168874_ENSG00000139197,-0.239356,0.041399,cogng_path_slope,ENSG00000168874_ENSG00000139197
4,cognpo_demog_slope_ENSG00000234284_ENSG0000014...,0.259939,0.019883,cognpo_demog_slope,ENSG00000234284_ENSG00000149089
5,cognse_demog_slope_ENSG00000169635_ENSG0000023...,-0.265049,0.017500,cognse_demog_slope,ENSG00000169635_ENSG00000234841
6,cognse_demog_slope_ENSG00000234284_ENSG0000014...,0.237717,0.033730,cognse_demog_slope,ENSG00000234284_ENSG00000149089
7,cognwo_demog_slope_ENSG00000162992_ENSG0000013...,-0.239250,0.031466,cognwo_demog_slope,ENSG00000162992_ENSG00000139197
8,cognwo_demog_slope_ENSG00000168874_ENSG0000013...,-0.270867,0.014452,cognwo_demog_slope,ENSG00000168874_ENSG00000139197
9,cognwo_demog_slope_ENSG00000169635_ENSG0000023...,-0.266283,0.016268,cognwo_demog_slope,ENSG00000169635_ENSG00000234841
10,cognwo_demog_slope_ENSG00000234284_ENSG0000014...,0.234666,0.034970,cognwo_demog_slope,ENSG00000234284_ENSG00000149089
11,cognwo_path_slope_ENSG00000169635_ENSG00000234841,-0.256171,0.028700,cognwo_path_slope,ENSG00000169635_ENSG00000234841

In [67]:
ad_corr

,0,AD_correlation_value,P_value_AD
0,zcomplexin_6_ENSG00000115112_ENSG00000197037,-0.693809,6.905714e-07
1,synap_6_complex2_ENSG00000115112_ENSG00000197037,-0.690432,8.225725e-07
2,synap_6_snap25_ENSG00000187079_ENSG00000111911,-0.681426,1.296827e-06
3,synap_6_snap25_ENSG00000170684_ENSG00000176749,-0.675235,1.757331e-06
4,synap_6_synaptophys_ENSG00000187079_ENSG000001...,-0.660976,3.445378e-06
...,...,...,...
3554665,synap_6_complex2_ENSG00000152467_ENSG00000148834,0.644090,7.312861e-06
3554666,synap_6_snap25_ENSG00000054598_ENSG00000227028,0.644841,7.079170e-06
3554667,synap_6_complex2_ENSG00000121068_ENSG00000207561,0.675610,1.725617e-06
3554668,synap_6_synaptophys_ENSG00000126804_ENSG000001...,0.679925,1.396898e-06
3554669,synap_6_snap25_ENSG00000126804_ENSG00000111911,0.682552,1.226159e-06

In [68]:
m = []
n = []
for i in ad_corr['0'].tolist():
    k = i.split('_')[0:3]
    j = i.split('_')[3:]
    m.append(('_'.join(k)))
    n.append(('_'.join(j)))
    

ad_corr['cog_decline'] = m
ad_corr['edge'] = n

In [74]:
ad_corr = ad_corr[['cog' in i for i in  ad_corr.cog_decline.tolist()]]

In [78]:
ad_corr = ad_corr[ad_corr.edge.isin(ad_corr_22.edge)]

In [79]:
ad_corr

,0,AD_correlation_value,P_value_AD,cog_decline,edge
57867,cognwo_demog_slope_ENSG00000168874_ENSG0000013...,-0.270867,0.014452,cognwo_demog_slope,ENSG00000168874_ENSG00000139197
62583,cognwo_demog_slope_ENSG00000169635_ENSG0000023...,-0.266283,0.016268,cognwo_demog_slope,ENSG00000169635_ENSG00000234841
63939,cognse_demog_slope_ENSG00000169635_ENSG0000023...,-0.265049,0.017500,cognse_demog_slope,ENSG00000169635_ENSG00000234841
74448,cognwo_path_slope_ENSG00000169635_ENSG00000234841,-0.256171,0.028700,cognwo_path_slope,ENSG00000169635_ENSG00000234841
98971,cogng_path_slope_ENSG00000168874_ENSG00000139197,-0.239356,0.041399,cogng_path_slope,ENSG00000168874_ENSG00000139197
...,...,...,...,...,...
3347225,cogng_demog_slope_ENSG00000234284_ENSG00000149089,0.196725,0.078365,cogng_demog_slope,ENSG00000234284_ENSG00000149089
3387548,cognps_demog_slope_ENSG00000234284_ENSG0000014...,0.210906,0.062078,cognps_demog_slope,ENSG00000234284_ENSG00000149089
3439589,cognwo_demog_slope_ENSG00000234284_ENSG0000014...,0.234666,0.034970,cognwo_demog_slope,ENSG00000234284_ENSG00000149089
3445130,cognse_demog_slope_ENSG00000234284_ENSG0000014...,0.237717,0.033730,cognse_demog_slope,ENSG00000234284_ENSG00000149089
3478519,cognpo_demog_slope_ENSG00000234284_ENSG0000014...,0.259939,0.019883,cognpo_demog_slope,ENSG00000234284_ENSG00000149089

In [80]:
ad_corr.edge.unique()

array(['ENSG00000168874_ENSG00000139197',
       'ENSG00000169635_ENSG00000234841',
       'ENSG00000162992_ENSG00000139197',
       'ENSG00000188786_ENSG00000083799',
       'ENSG00000166823_ENSG00000178199',
       'ENSG00000234284_ENSG00000149089'], dtype=object)

In [82]:
ad_corr.cog_decline.unique()

array(['cognwo_demog_slope', 'cognse_demog_slope', 'cognwo_path_slope',
       'cogng_path_slope', 'cognep_path_slope', 'cognep_demog_slope',
       'cogng_demog_slope', 'cognse_path_slope', 'cognps_demog_slope',
       'cognps_path_slope', 'cognpo_demog_slope', 'cognpo_path_slope'],
      dtype=object)

In [86]:
cols = ['edge','cog_decline','P_value_AD','AD_correlation_value']
ad_corr = ad_corr[cols]

In [87]:
ad_corr.head()

,edge,cog_decline,P_value_AD,AD_correlation_value
57867,ENSG00000168874_ENSG00000139197,cognwo_demog_slope,0.014452,-0.270867
62583,ENSG00000169635_ENSG00000234841,cognwo_demog_slope,0.016268,-0.266283
63939,ENSG00000169635_ENSG00000234841,cognse_demog_slope,0.017500,-0.265049
74448,ENSG00000169635_ENSG00000234841,cognwo_path_slope,0.028700,-0.256171
98971,ENSG00000168874_ENSG00000139197,cogng_path_slope,0.041399,-0.239356

In [84]:
import pickle

# Path to your pickle file
pickle_file_path = '../../../data_preprocessed/pickle_file/ensemble_to_gene_name.pickle'

# Load the pickle file
with open(pickle_file_path, 'rb') as file:
    ensemble_to_gene_name = pickle.load(file)

In [85]:

def return_gene_name(gene):
    
    try:
        if ensemble_to_gene_name[gene] == 'Gene name not found':
            return gene
        return ensemble_to_gene_name[gene]
    except:
        return gene

In [93]:
edge = []
for i in ad_corr.edge.tolist():
    
    m = return_gene_name(i.split('_')[0])
    n = return_gene_name(i.split('_')[1])
    edge.append(f'{m}-{n}')

In [95]:
ad_corr.edge = edge

/tmp/ipykernel_541344/2283554893.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ad_corr.edge = edge

In [97]:
ad_corr.to_csv('../../../data_preprocessed/correlation_output/ad_corr_for_plot.csv', index = False)

In [98]:
ad_corr.P_value_AD.min()

0.0144521508511589

In [100]:
ad_corr.AD_correlation_value.max()

0.2599390529770277

In [102]:
ad_corr[ad_corr.P_value_AD <= 0.05]

,edge,cog_decline,P_value_AD,AD_correlation_value
57867,ATOH8-PEX5,cognwo_demog_slope,0.014452,-0.270867
62583,HIC2-ENSG00000234841,cognwo_demog_slope,0.016268,-0.266283
63939,HIC2-ENSG00000234841,cognse_demog_slope,0.017500,-0.265049
74448,HIC2-ENSG00000234841,cognwo_path_slope,0.028700,-0.256171
98971,ATOH8-PEX5,cogng_path_slope,0.041399,-0.239356
99051,NEUROD1-PEX5,cognwo_demog_slope,0.031466,-0.239250
101147,MTF1-CYLD,cognep_path_slope,0.042574,-0.238029
101418,MESP1-ZC3H12D,cognep_demog_slope,0.032469,-0.237895
106257,HIC2-ENSG00000234841,cogng_demog_slope,0.034718,-0.234982
3439589,ZNF879-APIP,cognwo_demog_slope,0.034970,0.234666
3445130,ZNF879-APIP,cognse_demog_slope,0.033730,0.237717
3478519,ZNF879-APIP,cognpo_demog_slope,0.019883,0.259939