In [1]:
import pandas as pd
import os
from tqdm import tqdm

In [2]:
preprocessed_ad_single_sample_network_dir_path = '/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/grn_output/ad_nci_seperate_network/lioness/ad_preprocessed/'
preprocessed_nci_single_sample_network_dir_path = '/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/grn_output/ad_nci_seperate_network/lioness/nci_preprocessed/'

In [3]:
AD_data = pd.read_csv(preprocessed_ad_single_sample_network_dir_path +'lioness.427_120507.58.csv').rename(columns={'2':'lioness.427_120507.58.csv'.split('.')[1]})

for i in tqdm(os.listdir(preprocessed_ad_single_sample_network_dir_path)):
    if i.split('.')[1] in AD_data.columns:
        continue
    if 'csv' in i:
        df = pd.read_csv(preprocessed_ad_single_sample_network_dir_path + i).rename(columns={'2':i.split('.')[1]})
        AD_data = pd.merge(AD_data,df, on=['0','1'])

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 87/87 [00:20<00:00,  4.31it/s]

In [4]:
NCI_data = pd.read_csv(preprocessed_nci_single_sample_network_dir_path +'lioness.713_120531.47.csv').rename(columns={'2':'lioness.713_120531.47.csv'.split('.')[1]})

for i in tqdm(os.listdir(preprocessed_nci_single_sample_network_dir_path)):
    if i.split('.')[1] in NCI_data.columns:
        continue
    if 'csv' in i:
        df = pd.read_csv(preprocessed_nci_single_sample_network_dir_path + i).rename(columns={'2':i.split('.')[1]})
        NCI_data = pd.merge(NCI_data,df, on=['0','1'])

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [00:15<00:00,  4.34it/s]

In [5]:
AD_data.index = AD_data['0'] + '_' + AD_data['1']
AD_data.drop(columns=['0','1'],inplace = True)
AD_data

,427_120507,350_120501,497_120515,231_120425,24_120411,520_120515,202_120424,429_120507,568_120521,237_120426,...,34_120416,323_120501,384_120503,630_120524,708_120531,77_120417,23_120411,715_120531,420_120507,689_120604
ENSG00000001167_ENSG00000109685,5.422789,5.582590,5.550316,5.436518,5.477918,5.548920,6.046489,7.273255,5.856410,5.458538,...,7.035479,4.978047,5.226350,5.794004,5.773878,6.562551,5.389306,5.295861,5.771548,5.458670
ENSG00000001167_ENSG00000107362,5.349803,5.752049,5.402732,5.970177,5.579969,5.545492,5.524647,7.371541,6.909634,5.208306,...,6.190164,5.540829,5.583583,5.759652,5.260326,5.617084,5.433905,5.406885,6.530646,6.094826
ENSG00000001167_ENSG00000159423,6.944132,6.990538,6.876413,6.901820,7.081787,6.839790,6.660703,4.564330,6.687014,7.031452,...,5.906971,7.367776,7.354607,6.683811,6.306993,5.897600,7.140654,7.122604,8.000273,6.676154
ENSG00000001167_ENSG00000187187,7.422239,7.454585,7.505677,7.496206,7.481783,7.508017,8.091021,5.815734,6.816783,7.498840,...,6.295673,7.262532,8.275199,7.424579,7.459808,6.719548,7.478677,7.982371,8.699310,7.352844
ENSG00000001167_ENSG00000082701,5.269524,5.272363,5.310407,5.199323,5.234593,5.347205,4.991966,6.463328,4.880796,5.210510,...,6.167558,5.164574,5.143659,5.702611,5.787845,5.607147,5.211411,4.986887,4.633950,5.299784
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278129_ENSG00000149311,13.323806,13.551514,13.455582,13.484518,13.782081,13.830250,13.832985,12.696918,13.087175,12.987033,...,13.643625,13.820091,14.347983,13.649700,13.699755,13.901009,13.704960,13.691899,13.739728,13.844341
ENSG00000278129_ENSG00000149308,13.651741,13.384342,13.417867,13.138848,14.043145,13.598172,13.447751,13.050427,13.273157,13.042831,...,13.304772,13.365571,13.219922,13.502602,13.330046,14.842179,13.335939,13.413799,13.165613,13.400331
ENSG00000278129_ENSG00000259291,13.322590,13.217686,13.624116,13.552711,13.314662,13.600096,13.381757,13.938124,13.432308,13.487628,...,13.579048,13.126054,11.702317,13.902514,13.227954,12.306634,13.353002,13.559723,13.362870,13.377070
ENSG00000278129_ENSG00000075826,15.400658,15.185094,15.313141,15.302828,15.520248,15.504817,15.394125,15.222350,15.275454,15.302409,...,14.903426,15.765718,14.325750,15.746934,15.301823,16.321014,15.159812,14.998269,15.219113,15.219156
ENSG00000278129_ENSG00000101040,13.149005,13.433854,13.069732,13.260914,13.235256,13.224622,13.269111,13.468500,13.284884,13.084374,...,13.431703,13.556180,14.903238,13.070853,14.047822,12.450501,13.362226,12.999160,13.549021,13.116372

In [6]:
NCI_data.index = NCI_data['0'] + '_' + NCI_data['1']
NCI_data.drop(columns=['0','1'],inplace = True)
NCI_data

,713_120531,951_131107,534_120516,950_131107,298_120430,508_120515,567_120521,408_120503,340_120501,290_120430,...,45_120416,677_120604,65_120417,680_120604,74_120417,152_120419,360_120502,72_120417,470_120514,386_120503
ENSG00000001167_ENSG00000176261,5.482700,5.559684,5.328263,5.558828,5.234112,5.764225,4.958463,5.549492,5.142077,5.423955,...,5.539045,5.486246,5.495824,5.509237,5.682126,5.939890,5.470133,5.919201,5.088127,5.487017
ENSG00000001167_ENSG00000140350,4.982475,5.268472,5.056994,4.951359,4.641155,4.781434,3.728474,5.032809,4.849961,5.066636,...,4.641848,4.917301,4.860898,4.327789,4.937663,7.987460,4.933812,4.901850,5.088763,4.872469
ENSG00000001167_ENSG00000139517,4.670906,5.577982,4.541473,5.160953,5.674692,4.282357,5.061684,5.294319,5.333695,5.182849,...,5.138902,5.051557,5.169504,5.097622,5.208951,6.057974,4.922699,5.388184,5.884548,5.224092
ENSG00000001167_ENSG00000130175,5.404625,5.039784,5.966988,5.429527,5.448997,5.461276,4.730063,5.469214,6.011928,5.213447,...,5.310032,5.421357,5.611544,5.238567,5.591549,5.091609,5.426514,5.538087,4.533787,5.320011
ENSG00000001167_ENSG00000132763,6.668552,7.620014,6.928177,6.414171,5.395703,6.557029,6.610947,6.684681,6.723611,6.637750,...,6.582676,6.368325,5.864250,6.331151,6.526524,5.654648,6.704224,6.709261,7.736940,6.620601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000278129_ENSG00000146281,13.407919,13.608027,13.227907,14.391915,13.549009,12.006405,13.739711,13.870628,13.617681,14.556836,...,13.815204,13.900298,14.238177,13.738605,13.644225,12.071337,13.669115,13.824280,14.036683,14.066838
ENSG00000278129_ENSG00000149311,13.579513,13.506464,13.196193,13.461399,13.766703,12.441919,13.481220,13.682145,14.360163,13.905794,...,13.861326,13.678813,14.054400,13.978881,13.474053,12.636080,13.386020,12.389482,13.614431,13.592434
ENSG00000278129_ENSG00000149308,13.468954,13.396475,13.954026,13.570598,13.515806,12.230682,13.424496,13.456604,13.519724,13.709119,...,13.383097,13.604407,13.267566,13.527308,13.619648,14.694977,13.298863,13.189243,13.487149,13.202929
ENSG00000278129_ENSG00000259291,13.402257,13.593209,13.433287,13.741236,13.459474,13.860608,13.401375,13.013666,12.994866,13.598956,...,13.947162,13.491532,13.561849,12.852991,13.357489,17.289715,13.600090,14.106542,13.737192,13.276627
ENSG00000278129_ENSG00000075826,15.274045,15.282260,15.514377,15.448710,15.023314,16.028995,15.476839,15.216776,15.439769,15.468871,...,15.915617,15.433889,15.464810,15.220469,14.878867,19.255064,15.356346,15.681196,15.719278,14.963361

In [7]:
common_edge = set(NCI_data.index).intersection(set(AD_data.index))
AD_data = AD_data.loc[list(common_edge),:]
NCI_data = NCI_data.loc[list(common_edge),:]

In [8]:
AD_data.T

,ENSG00000111206_ENSG00000113068,ENSG00000105136_ENSG00000239556,ENSG00000119508_ENSG00000198604,ENSG00000171606_ENSG00000104936,ENSG00000179627_ENSG00000244509,ENSG00000119950_ENSG00000148842,ENSG00000151090_ENSG00000277053,ENSG00000198466_ENSG00000113048,ENSG00000128573_ENSG00000134419,ENSG00000244405_ENSG00000110756,...,ENSG00000158711_ENSG00000131269,ENSG00000125846_ENSG00000100292,ENSG00000107175_ENSG00000198369,ENSG00000158711_ENSG00000090432,ENSG00000170631_ENSG00000275367,ENSG00000186026_ENSG00000232422,ENSG00000091656_ENSG00000187240,ENSG00000101190_ENSG00000084092,ENSG00000130684_ENSG00000213638,ENSG00000111087_ENSG00000164300
427_120507,6.866799,5.866243,6.277637,6.592245,6.895820,5.857056,8.092920,5.983084,9.651353,6.784801,...,8.410677,9.260922,5.978680,7.791102,8.109402,9.211201,9.622003,6.330724,9.650963,6.301971
350_120501,7.023659,5.706085,6.771441,6.637529,7.619400,5.743290,7.241982,5.809716,9.876536,6.599112,...,8.228926,9.282917,5.828705,7.774363,8.322826,9.263000,10.291935,6.166327,9.919274,6.710866
497_120515,6.943699,5.609176,6.741453,6.268777,7.694185,5.846475,7.428377,6.058195,9.157999,6.605870,...,8.249943,9.379785,5.523218,7.594713,9.116001,8.523355,9.635320,6.484870,9.999934,6.803965
231_120425,6.990845,10.091893,6.750992,7.336689,7.234312,5.816019,6.893884,6.012349,9.580174,6.955425,...,8.469026,9.619468,5.974258,7.619446,8.274802,9.107787,9.890734,6.296855,10.091167,6.321649
24_120411,6.769093,5.751710,6.921485,6.663758,7.345831,5.750914,8.337076,6.152799,9.626175,6.557003,...,8.432765,9.153021,5.688147,7.690068,7.711229,9.223429,8.457733,6.298503,9.977038,6.666010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77_120417,6.322425,6.150659,7.028648,6.630012,8.130014,6.145587,4.435247,4.650754,8.851097,6.698005,...,9.837026,6.919222,5.882343,11.319585,10.059762,8.738922,9.302066,6.325434,10.042682,6.634790
23_120411,7.005639,5.779118,7.006182,6.408333,7.414831,5.466749,7.461318,5.711331,9.635373,6.888600,...,8.134748,9.283202,6.100372,7.943469,8.675399,9.472172,10.133308,6.442886,10.331264,6.739267
715_120531,6.721336,5.906043,6.783255,6.357966,7.312478,5.726961,7.202536,5.758418,9.810183,6.861619,...,8.616443,8.532079,6.084957,7.309277,8.152755,9.186036,9.200678,6.328791,9.675305,6.648849
420_120507,7.161648,5.469438,6.246394,6.893919,7.177525,5.561345,7.463155,5.864784,10.117567,6.437173,...,7.932141,8.710065,6.110159,8.221522,8.180674,9.164088,9.826124,6.426601,10.028604,6.540942
689_120604,6.850640,5.782499,7.044135,6.461255,7.675678,5.595576,6.163828,5.718703,9.321147,6.847677,...,8.368738,9.091003,5.969412,8.052429,8.293416,9.368700,9.669145,6.233142,10.009847,6.692632

In [9]:
NCI_data.T

,ENSG00000111206_ENSG00000113068,ENSG00000105136_ENSG00000239556,ENSG00000119508_ENSG00000198604,ENSG00000171606_ENSG00000104936,ENSG00000179627_ENSG00000244509,ENSG00000119950_ENSG00000148842,ENSG00000151090_ENSG00000277053,ENSG00000198466_ENSG00000113048,ENSG00000128573_ENSG00000134419,ENSG00000244405_ENSG00000110756,...,ENSG00000158711_ENSG00000131269,ENSG00000125846_ENSG00000100292,ENSG00000107175_ENSG00000198369,ENSG00000158711_ENSG00000090432,ENSG00000170631_ENSG00000275367,ENSG00000186026_ENSG00000232422,ENSG00000091656_ENSG00000187240,ENSG00000101190_ENSG00000084092,ENSG00000130684_ENSG00000213638,ENSG00000111087_ENSG00000164300
713_120531,5.883255,6.421775,7.094897,6.788696,7.516619,5.774246,7.786894,6.735299,10.336340,6.641119,...,8.317298,9.564898,5.720031,7.404958,8.258424,9.160643,10.639600,6.535102,9.662001,6.625092
951_131107,6.799167,5.693901,6.744580,6.491812,6.861641,5.675937,7.399757,5.890237,9.043911,6.633541,...,8.177434,9.207444,6.441144,7.800094,8.295659,9.165246,8.973130,6.455468,10.054814,6.668130
534_120516,6.540983,3.738357,5.578013,5.837926,6.881231,5.703887,9.449967,6.095380,8.897007,5.974918,...,6.700218,9.225893,4.241607,8.275509,7.845967,8.898338,10.330957,5.131966,10.196294,7.533545
950_131107,6.927882,6.144943,6.696559,5.967567,7.221562,5.897701,6.203018,5.728296,9.270654,6.737918,...,8.283937,8.936946,5.783160,7.732845,8.202458,9.220865,9.863840,6.320678,9.744451,6.725968
298_120430,6.861142,6.179692,6.997691,6.731646,7.548629,5.714418,6.855724,6.151368,9.463882,6.677104,...,8.630560,9.297814,5.877362,7.755879,7.765998,9.415116,10.124429,6.722244,10.076022,6.748645
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152_120419,8.863550,5.463732,6.363461,6.350726,5.149491,5.801996,7.142695,4.469761,10.320010,8.472076,...,9.476973,6.624850,6.102985,6.949983,8.140807,9.817286,15.015547,5.467858,8.522552,7.156029
360_120502,6.925227,5.752070,6.754978,6.587663,7.009244,5.456807,6.984879,5.817228,9.622101,6.580003,...,8.170897,9.330826,5.864913,7.894330,8.244964,9.305252,10.004176,6.520382,10.034323,6.558357
72_120417,7.476287,6.433090,6.959855,6.373167,7.577427,6.878738,7.284126,5.981440,10.442023,6.328166,...,7.728579,9.308455,5.057982,6.133221,8.748987,9.308046,9.947355,6.087994,9.647077,6.972800
470_120514,7.115762,5.835815,6.725863,6.551809,7.677636,6.326903,4.755281,5.940483,9.679303,6.646256,...,7.886500,9.338077,6.239616,7.884989,9.143263,9.031299,9.874688,6.361218,10.064778,6.875718
386_120503,6.709045,5.318376,6.932226,6.849344,7.402720,5.422319,6.969532,5.924014,9.939966,6.589798,...,8.217111,9.502421,5.998985,8.545801,7.814854,9.405525,9.910139,6.225830,11.297662,6.409966

In [10]:
clinical_data_ad_nci  = pd.read_csv('/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/count_matrix_preprocessed/final_clinical_data.csv')
clinical_data_ad_nci

,specimenID,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label
0,23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1
1,591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1
2,691_120605,5,14.0,1.0,1.0,4.833333,90.000000,4.0,3.0,0.0,NCI with No Plaques,0
3,588_120522,1,18.0,1.0,1.0,4.400000,90.000000,4.0,4.0,0.0,NCI with No Plaques,0
4,604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1
...,...,...,...,...,...,...,...,...,...,...,...,...
149,677_120604,4,23.0,1.0,1.0,18.666667,71.720739,4.0,3.0,0.0,NCI with No Plaques,0
150,142_120419,6,23.0,1.0,1.0,7.000000,71.603012,4.0,2.0,1.0,NCI with No Plaques,0
151,120_120418,5,26.0,1.0,1.0,4.083333,71.482546,4.0,1.0,1.0,NCI with No Plaques,0
152,483_120515,1,10.0,1.0,1.0,5.433333,70.510609,4.0,0.0,1.0,NCI with No Plaques,0
153,174_120424,5,12.0,1.0,1.0,5.000000,66.959617,4.0,1.0,1.0,NCI with No Plaques,0

In [11]:
clinical_data_ad_nci.set_index('specimenID', inplace = True)
clinical_data_ad_nci

,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label
specimenID,,,,,,,,,,,
23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1
591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1
691_120605,5,14.0,1.0,1.0,4.833333,90.000000,4.0,3.0,0.0,NCI with No Plaques,0
588_120522,1,18.0,1.0,1.0,4.400000,90.000000,4.0,4.0,0.0,NCI with No Plaques,0
604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1
...,...,...,...,...,...,...,...,...,...,...,...
677_120604,4,23.0,1.0,1.0,18.666667,71.720739,4.0,3.0,0.0,NCI with No Plaques,0
142_120419,6,23.0,1.0,1.0,7.000000,71.603012,4.0,2.0,1.0,NCI with No Plaques,0
120_120418,5,26.0,1.0,1.0,4.083333,71.482546,4.0,1.0,1.0,NCI with No Plaques,0
483_120515,1,10.0,1.0,1.0,5.433333,70.510609,4.0,0.0,1.0,NCI with No Plaques,0
174_120424,5,12.0,1.0,1.0,5.000000,66.959617,4.0,1.0,1.0,NCI with No Plaques,0

# AD

In [12]:
data = AD_data.T
data

,ENSG00000111206_ENSG00000113068,ENSG00000105136_ENSG00000239556,ENSG00000119508_ENSG00000198604,ENSG00000171606_ENSG00000104936,ENSG00000179627_ENSG00000244509,ENSG00000119950_ENSG00000148842,ENSG00000151090_ENSG00000277053,ENSG00000198466_ENSG00000113048,ENSG00000128573_ENSG00000134419,ENSG00000244405_ENSG00000110756,...,ENSG00000158711_ENSG00000131269,ENSG00000125846_ENSG00000100292,ENSG00000107175_ENSG00000198369,ENSG00000158711_ENSG00000090432,ENSG00000170631_ENSG00000275367,ENSG00000186026_ENSG00000232422,ENSG00000091656_ENSG00000187240,ENSG00000101190_ENSG00000084092,ENSG00000130684_ENSG00000213638,ENSG00000111087_ENSG00000164300
427_120507,6.866799,5.866243,6.277637,6.592245,6.895820,5.857056,8.092920,5.983084,9.651353,6.784801,...,8.410677,9.260922,5.978680,7.791102,8.109402,9.211201,9.622003,6.330724,9.650963,6.301971
350_120501,7.023659,5.706085,6.771441,6.637529,7.619400,5.743290,7.241982,5.809716,9.876536,6.599112,...,8.228926,9.282917,5.828705,7.774363,8.322826,9.263000,10.291935,6.166327,9.919274,6.710866
497_120515,6.943699,5.609176,6.741453,6.268777,7.694185,5.846475,7.428377,6.058195,9.157999,6.605870,...,8.249943,9.379785,5.523218,7.594713,9.116001,8.523355,9.635320,6.484870,9.999934,6.803965
231_120425,6.990845,10.091893,6.750992,7.336689,7.234312,5.816019,6.893884,6.012349,9.580174,6.955425,...,8.469026,9.619468,5.974258,7.619446,8.274802,9.107787,9.890734,6.296855,10.091167,6.321649
24_120411,6.769093,5.751710,6.921485,6.663758,7.345831,5.750914,8.337076,6.152799,9.626175,6.557003,...,8.432765,9.153021,5.688147,7.690068,7.711229,9.223429,8.457733,6.298503,9.977038,6.666010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77_120417,6.322425,6.150659,7.028648,6.630012,8.130014,6.145587,4.435247,4.650754,8.851097,6.698005,...,9.837026,6.919222,5.882343,11.319585,10.059762,8.738922,9.302066,6.325434,10.042682,6.634790
23_120411,7.005639,5.779118,7.006182,6.408333,7.414831,5.466749,7.461318,5.711331,9.635373,6.888600,...,8.134748,9.283202,6.100372,7.943469,8.675399,9.472172,10.133308,6.442886,10.331264,6.739267
715_120531,6.721336,5.906043,6.783255,6.357966,7.312478,5.726961,7.202536,5.758418,9.810183,6.861619,...,8.616443,8.532079,6.084957,7.309277,8.152755,9.186036,9.200678,6.328791,9.675305,6.648849
420_120507,7.161648,5.469438,6.246394,6.893919,7.177525,5.561345,7.463155,5.864784,10.117567,6.437173,...,7.932141,8.710065,6.110159,8.221522,8.180674,9.164088,9.826124,6.426601,10.028604,6.540942
689_120604,6.850640,5.782499,7.044135,6.461255,7.675678,5.595576,6.163828,5.718703,9.321147,6.847677,...,8.368738,9.091003,5.969412,8.052429,8.293416,9.368700,9.669145,6.233142,10.009847,6.692632

In [13]:
cross = pd.read_csv('/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/count_matrix_preprocessed/cross_section.csv')
long = pd.read_csv('/12tb_dsk2/danish/GRN_new_21_feb_2025/data_preprocessed/count_matrix_preprocessed/longn.csv')

In [14]:
cross

,projid,study,scaled_to,apoe_genotype,tomm40_hap,synap_6_complex1,synap_6_complex2,synap_6_snap25,synap_6_synaptophys,synap_6_syntaxin,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
0,9121,MAP,NaN,34.0,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21073,ROS,ROSMAP,34.0,NaN,NaN,NaN,NaN,NaN,NaN,...,83.608487,1.0,2.205581,1.845655,0.622034,3.231146,2.763562,4.682664,3.0,2.0
2,33027,MAP,NaN,33.0,3.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,45071,MAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,46112,MAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3841,99893592,MAP,NaN,33.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3842,99911705,MAP,NaN,23.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3843,99969159,MAP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3844,99978916,ROS,ROSMAP,33.0,NaN,NaN,NaN,NaN,NaN,NaN,...,89.368925,2.0,0.039992,0.016090,0.000000,0.000000,0.119977,0.717632,2.0,0.0
3845,99982430,MAP,NaN,23.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
long

,projid,study,fu_year,scaled_to,hsv1_1,cogn_ep,cogn_po,cogn_ps,cogn_se,cogn_wo,cogn_global,cts_estmmse30,age_at_visit,stroke_cum,ad_rx
0,9121,MAP,0,ROSMAP,NaN,0.020933,0.149295,0.357068,0.613074,0.098715,0.210987,29.0,79.969884,NaN,0.0
1,9121,MAP,1,ROSMAP,NaN,-0.049446,0.760382,0.317058,0.568144,-0.063168,0.208305,29.0,81.081451,NaN,0.0
2,9121,MAP,2,ROSMAP,NaN,-0.579577,0.760382,0.330437,0.882001,-0.382830,0.014894,30.0,81.612594,0.0,0.0
3,9121,MAP,3,ROSMAP,NaN,0.164920,0.755471,0.348868,0.769839,-0.220459,0.300473,30.0,82.595483,0.0,0.0
4,9121,MAP,4,ROSMAP,NaN,-0.012688,0.755471,0.529877,0.781153,-0.058088,0.300570,29.0,83.594798,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32762,99982430,MAP,15,ROSMAP,NaN,0.337987,-0.645255,0.200206,-0.952944,-0.060872,-0.061328,28.0,81.708419,0.0,0.0
32763,99982430,MAP,16,ROSMAP,NaN,NaN,NaN,NaN,NaN,0.098715,-0.218454,NaN,82.663929,0.0,0.0
32764,99982430,MAP,17,ROSMAP,NaN,0.275713,-0.809075,0.300325,-0.328499,0.101499,0.043797,28.0,83.759069,0.0,0.0
32765,99982430,MAP,18,ROSMAP,NaN,0.732239,-0.640344,0.295025,-0.254984,-0.222755,0.208931,26.0,84.692676,0.0,0.0
32766,99982430,MAP,19,ROSMAP,NaN,0.224745,-0.804165,-0.549501,-0.204560,0.422968,-0.048460,26.0,85.713895,0.0,0.0

In [16]:
biospecimen_metadata = pd.read_csv('/12tb_dsk2/common_data/ROSMAP_DATA/ROSMAP_biospecimen_metadata.csv')
clinical_data = pd.read_csv('/12tb_dsk2/common_data/ROSMAP_DATA/RSP_CL.csv')
rna_seq_metadata = pd.read_csv('/12tb_dsk2/common_data/ROSMAP_DATA/ROSMAP_assay_rnaSeq_metadata.csv')

In [17]:
biospecimen_metadata

,individualID,specimenID,specimenIdSource,organ,tissue,BrodmannArea,sampleStatus,tissueWeight,tissueVolume,nucleicAcidSource,cellType,fastingState,isPostMortem,samplingAge,samplingAgeUnits,visitNumber,assay,exclude,excludeReason,samplingDate
0,R1743384,190403-B4-A_R1743384,NaN,brain,dorsolateral prefrontal cortex,NaN,frozen,NaN,NaN,single nucleus,NaN,NaN,True,NaN,NaN,NaN,scrnaSeq,False,NaN,NaN
1,R2670295,190403-B4-A_R2670295,NaN,brain,dorsolateral prefrontal cortex,NaN,frozen,NaN,NaN,single nucleus,NaN,NaN,True,NaN,NaN,NaN,scrnaSeq,False,NaN,NaN
2,R4119160,190403-B4-A_R4119160,NaN,brain,dorsolateral prefrontal cortex,NaN,frozen,NaN,NaN,single nucleus,NaN,NaN,True,NaN,NaN,NaN,scrnaSeq,True,RNA genotype discordant with WGS,NaN
3,R4641987,190403-B4-A_R4641987,NaN,brain,dorsolateral prefrontal cortex,NaN,frozen,NaN,NaN,single nucleus,NaN,NaN,True,NaN,NaN,NaN,scrnaSeq,False,NaN,NaN
4,R5693901,190403-B4-A_R5693901,NaN,brain,dorsolateral prefrontal cortex,NaN,frozen,NaN,NaN,single nucleus,NaN,NaN,True,NaN,NaN,NaN,scrnaSeq,True,Duplicated donor,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13340,R4244951,ROSMAP210.b14.132N.R4244951,NaN,brain,dorsolateral prefrontal cortex,9,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,TMT quantitation,NaN,NaN,NaN
13341,R2039807,ROSMAP210.b14.132C.R2039807,NaN,brain,dorsolateral prefrontal cortex,9,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,TMT quantitation,NaN,NaN,NaN
13342,R5938989,ROSMAP210.b14.133N.R5938989,NaN,brain,dorsolateral prefrontal cortex,9,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,TMT quantitation,NaN,NaN,NaN
13343,R6622577,ROSMAP210.b14.133C.R6622577,NaN,brain,dorsolateral prefrontal cortex,9,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,TMT quantitation,NaN,NaN,NaN
13344,R9649089,ROSMAP210.b14.134N.R9649089,NaN,brain,dorsolateral prefrontal cortex,9,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,NaN,NaN,TMT quantitation,NaN,NaN,NaN

In [18]:
biospecimen_metadata = biospecimen_metadata[biospecimen_metadata.assay == 'rnaSeq' ]
biospecimen_metadata = biospecimen_metadata[biospecimen_metadata.nucleicAcidSource == 'bulk cell' ]
biospecimen_metadata = biospecimen_metadata[biospecimen_metadata.tissue == 'dorsolateral prefrontal cortex' ]
biospecimen_metadata = biospecimen_metadata[~biospecimen_metadata.individualID.isna()  ]
biospecimen_metadata

,individualID,specimenID,specimenIdSource,organ,tissue,BrodmannArea,sampleStatus,tissueWeight,tissueVolume,nucleicAcidSource,cellType,fastingState,isPostMortem,samplingAge,samplingAgeUnits,visitNumber,assay,exclude,excludeReason,samplingDate
1916,R9976232,510_120515,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1917,R9936070,207_120424,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1918,R9907075,81_120417,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1919,R9905342,649_120529,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
1920,R9904978,487_120515,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10157,R6796261,Sample_R6796261-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10158,R7310856,Sample_200r1-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10159,R3824126,Sample_R3824126-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10160,R7559268,Sample_R7559268-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN
10161,R3505473,Sample_R3505473-DLPFC,NaN,brain,dorsolateral prefrontal cortex,NaN,NaN,NaN,NaN,bulk cell,NaN,NaN,NaN,NaN,NaN,NaN,rnaSeq,True,sample swap,NaN

In [19]:
rna_seq_metadata

,specimenID,platform,RIN,rnaBatch,libraryBatch,sequencingBatch,libraryPrep,libraryPreparationMethod,isStranded,readStrandOrigin,runType,readLength,notes
0,492_120515,NaN,9.1,NaN,"0, 6, 7","0, 6, 7",polyAselection,NaN,True,NaN,pairedEnd,101,data contribution batch 1
1,R9938478,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,NaN,NaN,NaN,pairedEnd,101,NaN
2,R9254359,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,NaN,NaN,NaN,pairedEnd,101,NaN
3,R8718712,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,NaN,NaN,NaN,pairedEnd,101,NaN
4,R8434166,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,NaN,NaN,NaN,pairedEnd,101,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3191,R9254359_G,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,Smart-seq2,NaN,NaN,pairedEnd,101,NaN
3192,R8718712_G,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,Smart-seq2,NaN,NaN,pairedEnd,101,NaN
3193,R8434166_G,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,Smart-seq2,NaN,NaN,pairedEnd,101,NaN
3194,R3633816_G,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,Smart-seq2,NaN,NaN,pairedEnd,101,NaN
3195,R2809589_G,HiSeq2500,NaN,NaN,NaN,NaN,polyAselection,Smart-seq2,NaN,NaN,pairedEnd,101,NaN

In [20]:
clinical_data

,projid,Study,msex,educ,race,spanish,apoe_genotype,age_at_visit_max,age_first_ad_dx,age_death,cts_mmse30_first_ad_dx,cts_mmse30_lv,pmi,braaksc,ceradsc,cogdx,dcfdx_lv,individualID
0,10101589,ROS,1.0,20.0,1.0,2.0,34.0,90+,90+,90+,18.0,5.0,9.916667,4.0,2.0,4.0,4.0,R6939144
1,86767530,MAP,0.0,10.0,1.0,2.0,33.0,90+,90+,90+,18.0,10.0,6.500000,4.0,2.0,4.0,4.0,R3893503
2,9650662,MAP,0.0,15.0,1.0,2.0,23.0,90+,90+,90+,0.0,0.0,3.850000,3.0,2.0,4.0,4.0,R8937093
3,50402855,MAP,0.0,21.0,1.0,2.0,33.0,90+,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R7139444
4,20544321,ROS,0.0,16.0,1.0,2.0,23.0,90+,90+,NaN,13.0,14.0,NaN,NaN,NaN,NaN,4.0,R4971237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579,22207815,ROS,0.0,18.0,2.0,2.0,23.0,57.653661875427787,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R5306025
3580,22207941,ROS,0.0,16.0,2.0,2.0,34.0,56.651608487337441,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R6142763
3581,49333806,MAP,0.0,12.0,2.0,2.0,NaN,56.599589322381931,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,1.0,R4468842
3582,59720188,MAP,0.0,13.0,1.0,1.0,NaN,54.622861054072551,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R9446033
3583,90214403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R5615105

In [21]:
import numpy as np
def return_specimenid(indvidualid):
    
    x = biospecimen_metadata[biospecimen_metadata.individualID == indvidualid]['specimenID'].values
    try:
        return x[0]
    except:
        return np.nan

In [22]:
clinical_data['specimenID'] = clinical_data.individualID.apply(return_specimenid)
clinical_data

,projid,Study,msex,educ,race,spanish,apoe_genotype,age_at_visit_max,age_first_ad_dx,age_death,cts_mmse30_first_ad_dx,cts_mmse30_lv,pmi,braaksc,ceradsc,cogdx,dcfdx_lv,individualID,specimenID
0,10101589,ROS,1.0,20.0,1.0,2.0,34.0,90+,90+,90+,18.0,5.0,9.916667,4.0,2.0,4.0,4.0,R6939144,594_120522
1,86767530,MAP,0.0,10.0,1.0,2.0,33.0,90+,90+,90+,18.0,10.0,6.500000,4.0,2.0,4.0,4.0,R3893503,NaN
2,9650662,MAP,0.0,15.0,1.0,2.0,23.0,90+,90+,90+,0.0,0.0,3.850000,3.0,2.0,4.0,4.0,R8937093,565_120517
3,50402855,MAP,0.0,21.0,1.0,2.0,33.0,90+,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R7139444,NaN
4,20544321,ROS,0.0,16.0,1.0,2.0,23.0,90+,90+,NaN,13.0,14.0,NaN,NaN,NaN,NaN,4.0,R4971237,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579,22207815,ROS,0.0,18.0,2.0,2.0,23.0,57.653661875427787,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R5306025,NaN
3580,22207941,ROS,0.0,16.0,2.0,2.0,34.0,56.651608487337441,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R6142763,NaN
3581,49333806,MAP,0.0,12.0,2.0,2.0,NaN,56.599589322381931,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,1.0,R4468842,NaN
3582,59720188,MAP,0.0,13.0,1.0,1.0,NaN,54.622861054072551,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R9446033,NaN
3583,90214403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R5615105,NaN

In [23]:
biospecimen_metadata[biospecimen_metadata.individualID == 'R8937093']['specimenID'].values

array(['565_120517'], dtype=object)

In [25]:
def return_projid(specimenID):
    
    x = clinical_data[clinical_data.specimenID== specimenID]['projid'].values
    try:
        return x[0]
    except:
        return np.nan

In [26]:
proj_ids_list  = clinical_data_ad_nci.reset_index().specimenID.apply(return_projid)

In [27]:
proj_ids_list

0      50305165
1       7287209
2       2525608
3      20280666
4      20120255
         ...
149    20254164
150    15712086
151    10850171
152    11615242
153    11631558
Name: specimenID, Length: 154, dtype: int64

In [28]:
clinical_data_ad_nci['projid'] = proj_ids_list.tolist()

In [29]:
clinical_data_ad_nci

,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label,projid
specimenID,,,,,,,,,,,,
23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1,50305165
591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1,7287209
691_120605,5,14.0,1.0,1.0,4.833333,90.000000,4.0,3.0,0.0,NCI with No Plaques,0,2525608
588_120522,1,18.0,1.0,1.0,4.400000,90.000000,4.0,4.0,0.0,NCI with No Plaques,0,20280666
604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1,20120255
...,...,...,...,...,...,...,...,...,...,...,...,...
677_120604,4,23.0,1.0,1.0,18.666667,71.720739,4.0,3.0,0.0,NCI with No Plaques,0,20254164
142_120419,6,23.0,1.0,1.0,7.000000,71.603012,4.0,2.0,1.0,NCI with No Plaques,0,15712086
120_120418,5,26.0,1.0,1.0,4.083333,71.482546,4.0,1.0,1.0,NCI with No Plaques,0,10850171
483_120515,1,10.0,1.0,1.0,5.433333,70.510609,4.0,0.0,1.0,NCI with No Plaques,0,11615242
174_120424,5,12.0,1.0,1.0,5.000000,66.959617,4.0,1.0,1.0,NCI with No Plaques,0,11631558

In [30]:
def return_age_at_diag(specimenID):
    
    x = clinical_data[clinical_data.specimenID== specimenID]['age_first_ad_dx'].values
    try:
        return x[0]
    except:
        return np.nan

In [32]:
age_at_diag  = clinical_data_ad_nci.reset_index().specimenID.apply(return_age_at_diag)

In [33]:
age_at_diag

0      NaN
1      90+
2      NaN
3      NaN
4      90+
      ...
149    NaN
150    NaN
151    NaN
152    NaN
153    NaN
Name: specimenID, Length: 154, dtype: object

In [34]:
clinical_data_ad_nci['age_at_diag'] = age_at_diag.tolist()

In [35]:
clinical_data_ad_nci

,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label,projid,age_at_diag
specimenID,,,,,,,,,,,,,
23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1,50305165,NaN
591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1,7287209,90+
691_120605,5,14.0,1.0,1.0,4.833333,90.000000,4.0,3.0,0.0,NCI with No Plaques,0,2525608,NaN
588_120522,1,18.0,1.0,1.0,4.400000,90.000000,4.0,4.0,0.0,NCI with No Plaques,0,20280666,NaN
604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1,20120255,90+
...,...,...,...,...,...,...,...,...,...,...,...,...,...
677_120604,4,23.0,1.0,1.0,18.666667,71.720739,4.0,3.0,0.0,NCI with No Plaques,0,20254164,NaN
142_120419,6,23.0,1.0,1.0,7.000000,71.603012,4.0,2.0,1.0,NCI with No Plaques,0,15712086,NaN
120_120418,5,26.0,1.0,1.0,4.083333,71.482546,4.0,1.0,1.0,NCI with No Plaques,0,10850171,NaN
483_120515,1,10.0,1.0,1.0,5.433333,70.510609,4.0,0.0,1.0,NCI with No Plaques,0,11615242,NaN
174_120424,5,12.0,1.0,1.0,5.000000,66.959617,4.0,1.0,1.0,NCI with No Plaques,0,11631558,NaN

In [40]:
clinical_data_ad_nci[clinical_data_ad_nci.Category == 'AD with Plaques']

,Batch,educ,cogdx,race,pmi,age_at_visit_max,ceradsc,braaksc,msex,Category,Label,projid,age_at_diag
specimenID,,,,,,,,,,,,,
23_120411,6,18.0,4.0,1.0,6.416667,90.000000,1.0,4.0,0.0,AD with Plaques,1,50305165,NaN
591_120522,2,12.0,4.0,1.0,5.200000,90.000000,1.0,4.0,0.0,AD with Plaques,1,7287209,90+
604_120523,2,20.0,4.0,1.0,17.833333,90.000000,1.0,5.0,0.0,AD with Plaques,1,20120255,90+
545_120516,4,16.0,4.0,1.0,7.750000,90.000000,1.0,3.0,1.0,AD with Plaques,1,50302554,90+
364_120502,5,16.0,4.0,1.0,19.000000,90.000000,1.0,5.0,0.0,AD with Plaques,1,20260284,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
649_120529,3,21.0,4.0,1.0,6.750000,80.558522,1.0,3.0,0.0,AD with Plaques,1,21293107,79.3949349760438
689_120604,5,16.0,4.0,1.0,6.000000,79.961670,1.0,5.0,0.0,AD with Plaques,1,20674902,77.026694045174537
942_131101,8,16.0,4.0,1.0,5.950000,78.855578,1.0,4.0,1.0,AD with Plaques,1,28363718,NaN
628_120524,4,16.0,4.0,1.0,6.083333,75.493498,1.0,5.0,1.0,AD with Plaques,1,78452313,71.444216290212182
721_120531,4,13.0,4.0,1.0,3.000000,72.043806,1.0,5.0,0.0,AD with Plaques,1,21406920,NaN

In [41]:
clinical_data[clinical_data.specimenID == '942_131101']

,projid,Study,msex,educ,race,spanish,apoe_genotype,age_at_visit_max,age_first_ad_dx,age_death,cts_mmse30_first_ad_dx,cts_mmse30_lv,pmi,braaksc,ceradsc,cogdx,dcfdx_lv,individualID,specimenID
2916,28363718,MAP,1.0,16.0,1.0,1.0,33.0,78.855578370978776,NaN,79.200547570157426,NaN,9.0,5.95,4.0,1.0,4.0,4.0,R3914030,942_131101

In [45]:
clinical_data[clinical_data.specimenID== '677_120604']['projid'].values

array([20254164])

In [46]:
keep_projids = clinical_data_ad_nci.projid.tolist()

In [47]:
cross_ad_nci = cross[cross.projid.isin(keep_projids)]
cross_ad_nci

,projid,study,scaled_to,apoe_genotype,tomm40_hap,synap_6_complex1,synap_6_complex2,synap_6_snap25,synap_6_synaptophys,synap_6_syntaxin,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
14,482428,MAP,ROSMAP,23.0,6.0,1.237661,1.625262,1.439554,1.290091,1.256545,...,83.690623,4.0,0.288440,0.000000,0.063814,0.000000,0.801505,1.126262,1.0,2.0
28,1243685,MAP,ROSMAP,33.0,1.0,-0.310333,-0.885603,-0.760926,-0.501402,-0.396581,...,90.384668,2.0,0.955066,0.887281,1.007557,1.402597,0.455045,1.357190,1.0,1.0
51,2525608,MAP,ROSMAP,33.0,3.0,-0.191097,-1.307052,0.560709,0.444140,0.498696,...,101.190965,1.0,0.082848,0.000000,0.010854,0.000000,0.237691,0.676926,0.0,1.0
86,4127190,MAP,ROSMAP,23.0,3.0,-0.874412,-0.628507,-1.105788,-0.873418,-1.119047,...,88.637919,3.0,0.018012,0.000000,0.000000,0.000000,0.054037,0.208106,1.0,2.0
130,6107196,MAP,ROSMAP,33.0,6.0,1.356037,1.023536,0.661170,0.615141,0.562103,...,94.069815,0.0,1.150062,1.482179,0.879952,1.167937,1.402297,1.884515,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3436,85171938,MAP,ROSMAP,33.0,1.0,-0.249525,-0.699091,0.323486,0.318941,0.250118,...,94.587269,1.0,1.913206,2.097811,1.094365,1.309735,3.335517,3.686204,2.0,2.0
3456,85666580,MAP,ROSMAP,33.0,3.0,0.152136,-0.414558,0.713983,0.646937,0.703197,...,85.278576,0.0,1.624258,1.844629,1.356655,1.743439,1.772680,2.908767,1.0,2.0
3516,87779516,MAP,ROSMAP,33.0,1.0,0.905939,1.173079,1.280469,1.253568,1.237589,...,91.917864,2.0,0.100507,0.043460,0.000000,0.062790,0.238732,1.084628,0.0,3.0
3689,94092977,MAP,ROSMAP,24.0,2.0,0.505018,0.286759,0.644773,0.742954,0.706626,...,82.713210,0.0,1.104523,1.309622,1.588728,1.468640,0.256201,1.184133,2.0,3.0
3712,94828877,MAP,ROSMAP,33.0,5.0,0.792032,0.992865,0.961411,0.844815,0.816245,...,82.770705,1.0,1.592491,1.645525,0.557751,2.180445,2.039276,3.913996,1.0,2.0

In [48]:
cross_ad_nci.columns

Index(['projid', 'study', 'scaled_to', 'apoe_genotype', 'tomm40_hap',
       'synap_6_complex1', 'synap_6_complex2', 'synap_6_snap25',
       'synap_6_synaptophys', 'synap_6_syntaxin', 'synap_6_vamp',
       'zcapture_syn_6', 'zcomplexin_6', 'zsnare_6', 'cognep_demog_slope',
       'cognep_path_slope', 'cogng_demog_slope', 'cogng_path_slope',
       'cognpo_demog_slope', 'cognpo_path_slope', 'cognps_demog_slope',
       'cognps_path_slope', 'cognse_demog_slope', 'cognse_path_slope',
       'cognwo_demog_slope', 'cognwo_path_slope', 'age_bl', 'age_death',
       'med_con_sum_bl', 'gpath', 'amylsqrt_est_8reg', 'plaq_d', 'plaq_n',
       'nft', 'tangsqrt_est_8reg', 'caa_4gp', 'cvda_4gp2'],
      dtype='object')

In [49]:
clinical_data_ad_nci.reset_index(inplace=True)

In [52]:
clinical_data_ad_nci = clinical_data_ad_nci[['specimenID',
'age_at_diag', 
 'educ',
 'cogdx',
 'race',
 'pmi',
 'ceradsc',
 'braaksc',
 'msex',
 'Category',
 'Label',
 'projid']]

In [53]:
clinical_data_ad_nci

,specimenID,age_at_diag,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,Label,projid
0,23_120411,NaN,18.0,4.0,1.0,6.416667,1.0,4.0,0.0,AD with Plaques,1,50305165
1,591_120522,90+,12.0,4.0,1.0,5.200000,1.0,4.0,0.0,AD with Plaques,1,7287209
2,691_120605,NaN,14.0,1.0,1.0,4.833333,4.0,3.0,0.0,NCI with No Plaques,0,2525608
3,588_120522,NaN,18.0,1.0,1.0,4.400000,4.0,4.0,0.0,NCI with No Plaques,0,20280666
4,604_120523,90+,20.0,4.0,1.0,17.833333,1.0,5.0,0.0,AD with Plaques,1,20120255
...,...,...,...,...,...,...,...,...,...,...,...,...
149,677_120604,NaN,23.0,1.0,1.0,18.666667,4.0,3.0,0.0,NCI with No Plaques,0,20254164
150,142_120419,NaN,23.0,1.0,1.0,7.000000,4.0,2.0,1.0,NCI with No Plaques,0,15712086
151,120_120418,NaN,26.0,1.0,1.0,4.083333,4.0,1.0,1.0,NCI with No Plaques,0,10850171
152,483_120515,NaN,10.0,1.0,1.0,5.433333,4.0,0.0,1.0,NCI with No Plaques,0,11615242
153,174_120424,NaN,12.0,1.0,1.0,5.000000,4.0,1.0,1.0,NCI with No Plaques,0,11631558

In [54]:
cross_ad_nci.columns

Index(['projid', 'study', 'scaled_to', 'apoe_genotype', 'tomm40_hap',
       'synap_6_complex1', 'synap_6_complex2', 'synap_6_snap25',
       'synap_6_synaptophys', 'synap_6_syntaxin', 'synap_6_vamp',
       'zcapture_syn_6', 'zcomplexin_6', 'zsnare_6', 'cognep_demog_slope',
       'cognep_path_slope', 'cogng_demog_slope', 'cogng_path_slope',
       'cognpo_demog_slope', 'cognpo_path_slope', 'cognps_demog_slope',
       'cognps_path_slope', 'cognse_demog_slope', 'cognse_path_slope',
       'cognwo_demog_slope', 'cognwo_path_slope', 'age_bl', 'age_death',
       'med_con_sum_bl', 'gpath', 'amylsqrt_est_8reg', 'plaq_d', 'plaq_n',
       'nft', 'tangsqrt_est_8reg', 'caa_4gp', 'cvda_4gp2'],
      dtype='object')

In [55]:
merge_data = pd.merge(clinical_data_ad_nci,cross_ad_nci, on = 'projid')

In [56]:
merge_data

,specimenID,age_at_diag,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
0,23_120411,NaN,18.0,4.0,1.0,6.416667,1.0,4.0,0.0,AD with Plaques,...,101.998631,0.0,1.069731,0.648951,0.605607,1.212379,1.391206,1.639377,1.0,2.0
1,591_120522,90+,12.0,4.0,1.0,5.200000,1.0,4.0,0.0,AD with Plaques,...,101.472964,3.0,0.926817,1.831791,0.255506,2.019769,0.505175,1.834671,1.0,1.0
2,691_120605,NaN,14.0,1.0,1.0,4.833333,4.0,3.0,0.0,NCI with No Plaques,...,101.190965,1.0,0.082848,0.000000,0.010854,0.000000,0.237691,0.676926,0.0,1.0
3,588_120522,NaN,18.0,1.0,1.0,4.400000,4.0,4.0,0.0,NCI with No Plaques,...,101.089665,0.0,0.704864,1.272550,1.424990,0.191199,0.498402,1.304210,3.0,3.0
4,604_120523,90+,20.0,4.0,1.0,17.833333,1.0,5.0,0.0,AD with Plaques,...,99.696099,1.0,1.549014,1.175537,0.958724,1.664274,2.024042,2.217816,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,677_120604,NaN,23.0,1.0,1.0,18.666667,4.0,3.0,0.0,NCI with No Plaques,...,71.958932,0.0,0.124224,0.000000,0.025775,0.000000,0.346897,1.160054,0.0,0.0
150,142_120419,NaN,23.0,1.0,1.0,7.000000,4.0,2.0,1.0,NCI with No Plaques,...,72.429843,5.0,0.024499,0.000000,0.000000,0.000000,0.073498,0.160236,NaN,0.0
151,120_120418,NaN,26.0,1.0,1.0,4.083333,4.0,1.0,1.0,NCI with No Plaques,...,71.624914,0.0,0.009730,0.293077,0.000000,0.000000,0.029191,0.319598,0.0,1.0
152,483_120515,NaN,10.0,1.0,1.0,5.433333,4.0,0.0,1.0,NCI with No Plaques,...,71.660507,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.317621,1.0,2.0
153,174_120424,NaN,12.0,1.0,1.0,5.000000,4.0,1.0,1.0,NCI with No Plaques,...,67.370294,3.0,0.006487,0.120482,0.000000,0.000000,0.019461,0.185859,0.0,2.0

In [57]:
merge_data[['specimenID','projid','gpath']]

     specimenID    projid     gpath
0     23_120411  50305165  1.069731
1    591_120522   7287209  0.926817
2    691_120605   2525608  0.082848
3    588_120522  20280666  0.704864
4    604_120523  20120255  1.549014
..          ...       ...       ...
149  677_120604  20254164  0.124224
150  142_120419  15712086  0.024499
151  120_120418  10850171  0.009730
152  483_120515  11615242  0.000000
153  174_120424  11631558  0.006487

[154 rows x 3 columns]

In [58]:
clinical_data_ad_nci[clinical_data_ad_nci.specimenID == '591_120522']

,specimenID,age_at_diag,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,Label,projid
1,591_120522,90+,12.0,4.0,1.0,5.2,1.0,4.0,0.0,AD with Plaques,1,7287209

In [59]:
cross[cross.projid == 7287209].gpath.values

array([0.92681696])

In [60]:
all_clinical_data = merge_data.copy()

In [61]:
all_clinical_data

,specimenID,age_at_diag,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
0,23_120411,NaN,18.0,4.0,1.0,6.416667,1.0,4.0,0.0,AD with Plaques,...,101.998631,0.0,1.069731,0.648951,0.605607,1.212379,1.391206,1.639377,1.0,2.0
1,591_120522,90+,12.0,4.0,1.0,5.200000,1.0,4.0,0.0,AD with Plaques,...,101.472964,3.0,0.926817,1.831791,0.255506,2.019769,0.505175,1.834671,1.0,1.0
2,691_120605,NaN,14.0,1.0,1.0,4.833333,4.0,3.0,0.0,NCI with No Plaques,...,101.190965,1.0,0.082848,0.000000,0.010854,0.000000,0.237691,0.676926,0.0,1.0
3,588_120522,NaN,18.0,1.0,1.0,4.400000,4.0,4.0,0.0,NCI with No Plaques,...,101.089665,0.0,0.704864,1.272550,1.424990,0.191199,0.498402,1.304210,3.0,3.0
4,604_120523,90+,20.0,4.0,1.0,17.833333,1.0,5.0,0.0,AD with Plaques,...,99.696099,1.0,1.549014,1.175537,0.958724,1.664274,2.024042,2.217816,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149,677_120604,NaN,23.0,1.0,1.0,18.666667,4.0,3.0,0.0,NCI with No Plaques,...,71.958932,0.0,0.124224,0.000000,0.025775,0.000000,0.346897,1.160054,0.0,0.0
150,142_120419,NaN,23.0,1.0,1.0,7.000000,4.0,2.0,1.0,NCI with No Plaques,...,72.429843,5.0,0.024499,0.000000,0.000000,0.000000,0.073498,0.160236,NaN,0.0
151,120_120418,NaN,26.0,1.0,1.0,4.083333,4.0,1.0,1.0,NCI with No Plaques,...,71.624914,0.0,0.009730,0.293077,0.000000,0.000000,0.029191,0.319598,0.0,1.0
152,483_120515,NaN,10.0,1.0,1.0,5.433333,4.0,0.0,1.0,NCI with No Plaques,...,71.660507,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.317621,1.0,2.0
153,174_120424,NaN,12.0,1.0,1.0,5.000000,4.0,1.0,1.0,NCI with No Plaques,...,67.370294,3.0,0.006487,0.120482,0.000000,0.000000,0.019461,0.185859,0.0,2.0

In [62]:
all_clinical_data.set_index('specimenID', inplace = True)

In [63]:
all_clinical_data

,age_at_diag,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,Label,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
specimenID,,,,,,,,,,,,,,,,,,,,,
23_120411,NaN,18.0,4.0,1.0,6.416667,1.0,4.0,0.0,AD with Plaques,1,...,101.998631,0.0,1.069731,0.648951,0.605607,1.212379,1.391206,1.639377,1.0,2.0
591_120522,90+,12.0,4.0,1.0,5.200000,1.0,4.0,0.0,AD with Plaques,1,...,101.472964,3.0,0.926817,1.831791,0.255506,2.019769,0.505175,1.834671,1.0,1.0
691_120605,NaN,14.0,1.0,1.0,4.833333,4.0,3.0,0.0,NCI with No Plaques,0,...,101.190965,1.0,0.082848,0.000000,0.010854,0.000000,0.237691,0.676926,0.0,1.0
588_120522,NaN,18.0,1.0,1.0,4.400000,4.0,4.0,0.0,NCI with No Plaques,0,...,101.089665,0.0,0.704864,1.272550,1.424990,0.191199,0.498402,1.304210,3.0,3.0
604_120523,90+,20.0,4.0,1.0,17.833333,1.0,5.0,0.0,AD with Plaques,1,...,99.696099,1.0,1.549014,1.175537,0.958724,1.664274,2.024042,2.217816,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
677_120604,NaN,23.0,1.0,1.0,18.666667,4.0,3.0,0.0,NCI with No Plaques,0,...,71.958932,0.0,0.124224,0.000000,0.025775,0.000000,0.346897,1.160054,0.0,0.0
142_120419,NaN,23.0,1.0,1.0,7.000000,4.0,2.0,1.0,NCI with No Plaques,0,...,72.429843,5.0,0.024499,0.000000,0.000000,0.000000,0.073498,0.160236,NaN,0.0
120_120418,NaN,26.0,1.0,1.0,4.083333,4.0,1.0,1.0,NCI with No Plaques,0,...,71.624914,0.0,0.009730,0.293077,0.000000,0.000000,0.029191,0.319598,0.0,1.0
483_120515,NaN,10.0,1.0,1.0,5.433333,4.0,0.0,1.0,NCI with No Plaques,0,...,71.660507,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.317621,1.0,2.0
174_120424,NaN,12.0,1.0,1.0,5.000000,4.0,1.0,1.0,NCI with No Plaques,0,...,67.370294,3.0,0.006487,0.120482,0.000000,0.000000,0.019461,0.185859,0.0,2.0

In [64]:
keep_samples = list(set(data.index).intersection(set(all_clinical_data.index)))

In [65]:
data = data.loc[keep_samples]
data

,ENSG00000111206_ENSG00000113068,ENSG00000105136_ENSG00000239556,ENSG00000119508_ENSG00000198604,ENSG00000171606_ENSG00000104936,ENSG00000179627_ENSG00000244509,ENSG00000119950_ENSG00000148842,ENSG00000151090_ENSG00000277053,ENSG00000198466_ENSG00000113048,ENSG00000128573_ENSG00000134419,ENSG00000244405_ENSG00000110756,...,ENSG00000158711_ENSG00000131269,ENSG00000125846_ENSG00000100292,ENSG00000107175_ENSG00000198369,ENSG00000158711_ENSG00000090432,ENSG00000170631_ENSG00000275367,ENSG00000186026_ENSG00000232422,ENSG00000091656_ENSG00000187240,ENSG00000101190_ENSG00000084092,ENSG00000130684_ENSG00000213638,ENSG00000111087_ENSG00000164300
429_120507,8.106844,5.953746,6.982843,6.704462,7.560285,5.984992,5.180594,5.871500,8.419682,6.684675,...,8.693215,9.533984,5.477487,7.576140,8.642704,9.726011,9.374269,6.724997,10.044114,6.990022
321_120501,7.026412,6.480585,6.563555,6.702860,7.163425,5.886370,7.407375,5.917673,9.802440,6.425286,...,7.764447,8.869367,5.948520,7.723241,7.915955,9.232442,10.584731,5.922493,10.125676,6.529332
715_120531,6.721336,5.906043,6.783255,6.357966,7.312478,5.726961,7.202536,5.758418,9.810183,6.861619,...,8.616443,8.532079,6.084957,7.309277,8.152755,9.186036,9.200678,6.328791,9.675305,6.648849
232_120425,6.862470,5.390621,6.218685,6.304508,7.284934,5.968609,8.162574,6.465257,9.334754,5.997467,...,8.386665,9.160886,5.451607,8.689367,8.677687,9.047344,9.435422,6.710578,10.109824,6.724867
511_120515,6.922772,5.619094,8.139077,6.002942,7.332551,5.788170,7.032000,5.845303,8.615721,6.930930,...,8.230843,7.776168,6.119251,6.435303,7.389269,9.200690,10.992755,6.168366,10.083069,6.627241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434_120507,7.185419,5.678550,6.635823,6.387301,7.169939,5.981906,6.810191,6.299799,8.482809,7.192838,...,9.108525,9.086801,6.644873,5.397323,8.160205,9.210829,9.626756,6.024547,10.185424,6.646170
721_120531,7.201048,5.978915,6.602670,6.754971,6.185004,5.338485,7.914904,5.787812,9.571388,7.420922,...,9.108327,9.490019,6.062113,8.360826,8.283306,9.176075,10.026373,5.923558,9.984965,6.578862
459_120514,6.993379,5.798019,7.012632,6.969961,7.629748,5.689236,6.149011,5.862015,9.576479,6.995242,...,8.551721,9.286045,5.880532,7.970798,8.259386,9.365843,9.547453,6.422678,10.127116,6.715680
635_120524,7.192252,7.852239,7.097503,6.851899,7.157685,5.565584,7.265344,6.002101,8.060742,7.131518,...,8.770605,9.524290,6.052024,7.865985,8.271631,9.047047,9.462333,6.189153,10.276237,6.397147
689_120604,6.850640,5.782499,7.044135,6.461255,7.675678,5.595576,6.163828,5.718703,9.321147,6.847677,...,8.368738,9.091003,5.969412,8.052429,8.293416,9.368700,9.669145,6.233142,10.009847,6.692632

In [66]:
data

,ENSG00000111206_ENSG00000113068,ENSG00000105136_ENSG00000239556,ENSG00000119508_ENSG00000198604,ENSG00000171606_ENSG00000104936,ENSG00000179627_ENSG00000244509,ENSG00000119950_ENSG00000148842,ENSG00000151090_ENSG00000277053,ENSG00000198466_ENSG00000113048,ENSG00000128573_ENSG00000134419,ENSG00000244405_ENSG00000110756,...,ENSG00000158711_ENSG00000131269,ENSG00000125846_ENSG00000100292,ENSG00000107175_ENSG00000198369,ENSG00000158711_ENSG00000090432,ENSG00000170631_ENSG00000275367,ENSG00000186026_ENSG00000232422,ENSG00000091656_ENSG00000187240,ENSG00000101190_ENSG00000084092,ENSG00000130684_ENSG00000213638,ENSG00000111087_ENSG00000164300
429_120507,8.106844,5.953746,6.982843,6.704462,7.560285,5.984992,5.180594,5.871500,8.419682,6.684675,...,8.693215,9.533984,5.477487,7.576140,8.642704,9.726011,9.374269,6.724997,10.044114,6.990022
321_120501,7.026412,6.480585,6.563555,6.702860,7.163425,5.886370,7.407375,5.917673,9.802440,6.425286,...,7.764447,8.869367,5.948520,7.723241,7.915955,9.232442,10.584731,5.922493,10.125676,6.529332
715_120531,6.721336,5.906043,6.783255,6.357966,7.312478,5.726961,7.202536,5.758418,9.810183,6.861619,...,8.616443,8.532079,6.084957,7.309277,8.152755,9.186036,9.200678,6.328791,9.675305,6.648849
232_120425,6.862470,5.390621,6.218685,6.304508,7.284934,5.968609,8.162574,6.465257,9.334754,5.997467,...,8.386665,9.160886,5.451607,8.689367,8.677687,9.047344,9.435422,6.710578,10.109824,6.724867
511_120515,6.922772,5.619094,8.139077,6.002942,7.332551,5.788170,7.032000,5.845303,8.615721,6.930930,...,8.230843,7.776168,6.119251,6.435303,7.389269,9.200690,10.992755,6.168366,10.083069,6.627241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434_120507,7.185419,5.678550,6.635823,6.387301,7.169939,5.981906,6.810191,6.299799,8.482809,7.192838,...,9.108525,9.086801,6.644873,5.397323,8.160205,9.210829,9.626756,6.024547,10.185424,6.646170
721_120531,7.201048,5.978915,6.602670,6.754971,6.185004,5.338485,7.914904,5.787812,9.571388,7.420922,...,9.108327,9.490019,6.062113,8.360826,8.283306,9.176075,10.026373,5.923558,9.984965,6.578862
459_120514,6.993379,5.798019,7.012632,6.969961,7.629748,5.689236,6.149011,5.862015,9.576479,6.995242,...,8.551721,9.286045,5.880532,7.970798,8.259386,9.365843,9.547453,6.422678,10.127116,6.715680
635_120524,7.192252,7.852239,7.097503,6.851899,7.157685,5.565584,7.265344,6.002101,8.060742,7.131518,...,8.770605,9.524290,6.052024,7.865985,8.271631,9.047047,9.462333,6.189153,10.276237,6.397147
689_120604,6.850640,5.782499,7.044135,6.461255,7.675678,5.595576,6.163828,5.718703,9.321147,6.847677,...,8.368738,9.091003,5.969412,8.052429,8.293416,9.368700,9.669145,6.233142,10.009847,6.692632

In [68]:
all_clinical_data.columns

Index(['age_at_diag', 'educ', 'cogdx', 'race', 'pmi', 'ceradsc', 'braaksc',
       'msex', 'Category', 'Label', 'projid', 'study', 'scaled_to',
       'apoe_genotype', 'tomm40_hap', 'synap_6_complex1', 'synap_6_complex2',
       'synap_6_snap25', 'synap_6_synaptophys', 'synap_6_syntaxin',
       'synap_6_vamp', 'zcapture_syn_6', 'zcomplexin_6', 'zsnare_6',
       'cognep_demog_slope', 'cognep_path_slope', 'cogng_demog_slope',
       'cogng_path_slope', 'cognpo_demog_slope', 'cognpo_path_slope',
       'cognps_demog_slope', 'cognps_path_slope', 'cognse_demog_slope',
       'cognse_path_slope', 'cognwo_demog_slope', 'cognwo_path_slope',
       'age_bl', 'age_death', 'med_con_sum_bl', 'gpath', 'amylsqrt_est_8reg',
       'plaq_d', 'plaq_n', 'nft', 'tangsqrt_est_8reg', 'caa_4gp', 'cvda_4gp2'],
      dtype='object')

In [70]:
§all_clinical_data[all_clinical_data.Category == 'AD with Plaques'][['age_bl','age_at_diag','age_death']]

               age_bl         age_at_diag   age_death
specimenID
23_120411   99.797399                 NaN  101.998631
591_120522  96.449008                 90+  101.472964
604_120523  83.939767                 90+   99.696099
545_120516  90.781656                 90+  100.542094
364_120502  89.549624                 NaN   98.852841
...               ...                 ...         ...
649_120529  70.234086    79.3949349760438   80.687201
689_120604  72.911704  77.026694045174537   80.736482
942_131101  78.855578                 NaN   79.200548
628_120524  70.537988  71.444216290212182   75.978097
721_120531  63.019849                 NaN   72.399726

[87 rows x 3 columns]

In [75]:


def return_float(age):
    
    
    if age == '90+':
        return 90
    elif age == np.nan:
        return np.nan
    else:
        return age

In [78]:
ad_data = all_clinical_data[all_clinical_data.Category == 'AD with Plaques']

In [80]:
ad_data

,age_at_diag,educ,cogdx,race,pmi,ceradsc,braaksc,msex,Category,Label,...,age_death,med_con_sum_bl,gpath,amylsqrt_est_8reg,plaq_d,plaq_n,nft,tangsqrt_est_8reg,caa_4gp,cvda_4gp2
specimenID,,,,,,,,,,,,,,,,,,,,,
23_120411,NaN,18.0,4.0,1.0,6.416667,1.0,4.0,0.0,AD with Plaques,1,...,101.998631,0.0,1.069731,0.648951,0.605607,1.212379,1.391206,1.639377,1.0,2.0
591_120522,90+,12.0,4.0,1.0,5.200000,1.0,4.0,0.0,AD with Plaques,1,...,101.472964,3.0,0.926817,1.831791,0.255506,2.019769,0.505175,1.834671,1.0,1.0
604_120523,90+,20.0,4.0,1.0,17.833333,1.0,5.0,0.0,AD with Plaques,1,...,99.696099,1.0,1.549014,1.175537,0.958724,1.664274,2.024042,2.217816,3.0,2.0
545_120516,90+,16.0,4.0,1.0,7.750000,1.0,3.0,1.0,AD with Plaques,1,...,100.542094,0.0,0.727593,1.631315,0.593186,1.470877,0.118717,1.529590,2.0,3.0
364_120502,NaN,16.0,4.0,1.0,19.000000,1.0,5.0,0.0,AD with Plaques,1,...,98.852841,1.0,1.198759,1.164589,0.470473,1.970883,1.154920,1.812797,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
649_120529,79.3949349760438,21.0,4.0,1.0,6.750000,1.0,3.0,0.0,AD with Plaques,1,...,80.687201,0.0,0.883564,1.908817,1.307345,1.238923,0.104423,1.327859,1.0,1.0
689_120604,77.026694045174537,16.0,4.0,1.0,6.000000,1.0,5.0,0.0,AD with Plaques,1,...,80.736482,1.0,2.375138,1.712075,2.218073,3.372463,1.534877,2.976579,3.0,1.0
942_131101,NaN,16.0,4.0,1.0,5.950000,1.0,4.0,1.0,AD with Plaques,1,...,79.200548,1.0,1.294964,1.867472,0.951585,2.221625,0.711683,3.898150,3.0,1.0
628_120524,71.444216290212182,16.0,4.0,1.0,6.083333,1.0,5.0,1.0,AD with Plaques,1,...,75.978097,0.0,1.907649,1.963961,0.597990,3.621776,1.503180,3.999719,2.0,0.0
721_120531,NaN,13.0,4.0,1.0,3.000000,1.0,5.0,0.0,AD with Plaques,1,...,72.399726,0.0,2.312114,1.349242,0.360288,5.146106,1.429948,3.098522,1.0,0.0

In [81]:
ad_data['age_at_diag'] = [return_float(age) for age in ad_data.age_at_diag.tolist()]

/tmp/ipykernel_563809/948676402.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ad_data['age_at_diag'] = [return_float(age) for age in ad_data.age_at_diag.tolist()]

In [83]:
ad_data[['age_bl','age_at_diag','age_death']]

               age_bl         age_at_diag   age_death
specimenID
23_120411   99.797399                 NaN  101.998631
591_120522  96.449008                  90  101.472964
604_120523  83.939767                  90   99.696099
545_120516  90.781656                  90  100.542094
364_120502  89.549624                 NaN   98.852841
...               ...                 ...         ...
649_120529  70.234086    79.3949349760438   80.687201
689_120604  72.911704  77.026694045174537   80.736482
942_131101  78.855578                 NaN   79.200548
628_120524  70.537988  71.444216290212182   75.978097
721_120531  63.019849                 NaN   72.399726

[87 rows x 3 columns]

In [92]:
ad_data['age_at_diag'] = ad_data['age_at_diag'].astype(float)
ad_data[['age_bl','age_at_diag','age_death']]

/tmp/ipykernel_563809/2840807684.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ad_data['age_at_diag'] = ad_data['age_at_diag'].astype(float)

               age_bl  age_at_diag   age_death
specimenID
23_120411   99.797399          NaN  101.998631
591_120522  96.449008    90.000000  101.472964
604_120523  83.939767    90.000000   99.696099
545_120516  90.781656    90.000000  100.542094
364_120502  89.549624          NaN   98.852841
...               ...          ...         ...
649_120529  70.234086    79.394935   80.687201
689_120604  72.911704    77.026694   80.736482
942_131101  78.855578          NaN   79.200548
628_120524  70.537988    71.444216   75.978097
721_120531  63.019849          NaN   72.399726

[87 rows x 3 columns]

In [101]:
ad_data[['age_bl','age_at_diag','age_death']]

               age_bl  age_at_diag   age_death
specimenID
23_120411   99.797399          NaN  101.998631
591_120522  96.449008    90.000000  101.472964
604_120523  83.939767    90.000000   99.696099
545_120516  90.781656    90.000000  100.542094
364_120502  89.549624          NaN   98.852841
...               ...          ...         ...
649_120529  70.234086    79.394935   80.687201
689_120604  72.911704    77.026694   80.736482
942_131101  78.855578          NaN   79.200548
628_120524  70.537988    71.444216   75.978097
721_120531  63.019849          NaN   72.399726

[87 rows x 3 columns]

In [112]:
l = []
for i,j in ad_data.iterrows():
    if pd.isna(j['age_at_diag']):
        l.append(j['age_bl'])

    elif j['age_at_diag'] < j['age_bl']:
        l.append(j['age_bl'])

    else:
        l.append(j['age_at_diag'])

In [114]:
ad_data['final_age_at_diag'] = l
ad_data[['age_bl','age_at_diag','final_age_at_diag','age_death']]

/tmp/ipykernel_563809/2076495123.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ad_data['final_age_at_diag'] = l

               age_bl  age_at_diag  final_age_at_diag   age_death
specimenID
23_120411   99.797399          NaN          99.797399  101.998631
591_120522  96.449008    90.000000          96.449008  101.472964
604_120523  83.939767    90.000000          90.000000   99.696099
545_120516  90.781656    90.000000          90.781656  100.542094
364_120502  89.549624          NaN          89.549624   98.852841
...               ...          ...                ...         ...
649_120529  70.234086    79.394935          79.394935   80.687201
689_120604  72.911704    77.026694          77.026694   80.736482
942_131101  78.855578          NaN          78.855578   79.200548
628_120524  70.537988    71.444216          71.444216   75.978097
721_120531  63.019849          NaN          63.019849   72.399726

[87 rows x 4 columns]

In [116]:
ad_data['disease_duration'] = ad_data['age_death'] -  ad_data['final_age_at_diag']

/tmp/ipykernel_563809/664668749.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ad_data['disease_duration'] = ad_data['age_death'] -  ad_data['final_age_at_diag']

In [117]:
ad_data[['age_bl','age_at_diag','final_age_at_diag','age_death','disease_duration']]

,age_bl,age_at_diag,final_age_at_diag,age_death,disease_duration
specimenID,,,,,
23_120411,99.797399,NaN,99.797399,101.998631,2.201232
591_120522,96.449008,90.000000,96.449008,101.472964,5.023956
604_120523,83.939767,90.000000,90.000000,99.696099,9.696099
545_120516,90.781656,90.000000,90.781656,100.542094,9.760438
364_120502,89.549624,NaN,89.549624,98.852841,9.303217
...,...,...,...,...,...
649_120529,70.234086,79.394935,79.394935,80.687201,1.292266
689_120604,72.911704,77.026694,77.026694,80.736482,3.709788
942_131101,78.855578,NaN,78.855578,79.200548,0.344969
628_120524,70.537988,71.444216,71.444216,75.978097,4.533881
721_120531,63.019849,NaN,63.019849,72.399726,9.379877

In [115]:
for i in ad_data.columns:
    print(ad_data[i].head())
    print("_"*100)

specimenID
23_120411      NaN
591_120522    90.0
604_120523    90.0
545_120516    90.0
364_120502     NaN
Name: age_at_diag, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     18.0
591_120522    12.0
604_120523    20.0
545_120516    16.0
364_120502    16.0
Name: educ, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     4.0
591_120522    4.0
604_120523    4.0
545_120516    4.0
364_120502    4.0
Name: cogdx, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.0
591_120522    1.0
604_120523    1.0
545_120516    1.0
364_120502    1.0
Name: race, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411      6.416667
591_120522     5.200000
604_120523    17.833333
545_120516     7.750000
364_120502    19.000000
Name: pmi, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.0
591_120522    1.0
604_120523    1.0
545_120516    1.0
364_120502    1.0
Name: ceradsc, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     4.0
591_120522    4.0
604_120523    5.0
545_120516    3.0
364_120502    5.0
Name: braaksc, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     0.0
591_120522    0.0
604_120523    0.0
545_120516    1.0
364_120502    0.0
Name: msex, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     AD with Plaques
591_120522    AD with Plaques
604_120523    AD with Plaques
545_120516    AD with Plaques
364_120502    AD with Plaques
Name: Category, dtype: object
____________________________________________________________________________________________________
specimenID
23_120411     1
591_120522    1
604_120523    1
545_120516    1
364_120502    1
Name: Label, dtype: int64
____________________________________________________________________________________________________
specimenID
23_120411     50305165
591_120522     7287209
604_120523    20120255
545_120516    50302554
364_120502    20260284
Name: projid, dtype: int64
____________________________________________________________________________________________________
specimenID
23_120411     MAP
591_120522    MAP
604_120523    ROS
545_120516    MAP
364_120502    ROS
Name: study, dtype: object
____________________________________________________________________________________________________
specimenID
23_120411     ROSMAP
591_120522    ROSMAP
604_120523    ROSMAP
545_120516    ROSMAP
364_120502    ROSMAP
Name: scaled_to, dtype: object
____________________________________________________________________________________________________
specimenID
23_120411     33.0
591_120522    33.0
604_120523    33.0
545_120516    33.0
364_120502    33.0
Name: apoe_genotype, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     6.0
591_120522    6.0
604_120523    6.0
545_120516    3.0
364_120502    NaN
Name: tomm40_hap, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.129164
591_120522         NaN
604_120523         NaN
545_120516    0.248760
364_120502         NaN
Name: synap_6_complex1, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.457244
591_120522         NaN
604_120523         NaN
545_120516    0.426033
364_120502         NaN
Name: synap_6_complex2, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.478322
591_120522         NaN
604_120523         NaN
545_120516    1.338024
364_120502         NaN
Name: synap_6_snap25, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.352142
591_120522         NaN
604_120523         NaN
545_120516    1.159796
364_120502         NaN
Name: synap_6_synaptophys, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     0.404275
591_120522         NaN
604_120523         NaN
545_120516    1.370556
364_120502         NaN
Name: synap_6_syntaxin, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.439385
591_120522         NaN
604_120523         NaN
545_120516    0.705197
364_120502         NaN
Name: synap_6_vamp, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.926034
591_120522         NaN
604_120523         NaN
545_120516    0.039495
364_120502         NaN
Name: zcapture_syn_6, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.293204
591_120522         NaN
604_120523         NaN
545_120516    0.337397
364_120502         NaN
Name: zcomplexin_6, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     0.921830
591_120522         NaN
604_120523         NaN
545_120516    1.037877
364_120502         NaN
Name: zsnare_6, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.165115
591_120522   -0.065686
604_120523    0.023832
545_120516   -0.016033
364_120502   -0.077457
Name: cognep_demog_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.134972
591_120522   -0.056317
604_120523    0.051306
545_120516    0.050535
364_120502   -0.100975
Name: cognep_path_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.192183
591_120522   -0.108394
604_120523    0.013583
545_120516    0.021839
364_120502   -0.107844
Name: cogng_demog_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.124867
591_120522   -0.080517
604_120523    0.036849
545_120516    0.070394
364_120502   -0.129420
Name: cogng_path_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411          NaN
591_120522   -0.052466
604_120523    0.057189
545_120516   -0.016124
364_120502   -0.081511
Name: cognpo_demog_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411          NaN
591_120522   -0.061038
604_120523    0.077578
545_120516    0.003256
364_120502   -0.083608
Name: cognpo_path_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411          NaN
591_120522    0.013420
604_120523    0.014072
545_120516    0.032266
364_120502   -0.173234
Name: cognps_demog_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411          NaN
591_120522    0.021447
604_120523    0.027421
545_120516    0.056891
364_120502   -0.190029
Name: cognps_path_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411          NaN
591_120522   -0.120232
604_120523    0.054661
545_120516    0.016265
364_120502   -0.046920
Name: cognse_demog_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411          NaN
591_120522   -0.086772
604_120523    0.081693
545_120516    0.074434
364_120502   -0.075763
Name: cognse_path_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.034137
591_120522   -0.046109
604_120523    0.021570
545_120516    0.071933
364_120502   -0.128388
Name: cognwo_demog_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411    -0.064889
591_120522   -0.049986
604_120523    0.041213
545_120516    0.096781
364_120502   -0.139920
Name: cognwo_path_slope, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     99.797399
591_120522    96.449008
604_120523    83.939767
545_120516    90.781656
364_120502    89.549624
Name: age_bl, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     101.998631
591_120522    101.472964
604_120523     99.696099
545_120516    100.542094
364_120502     98.852841
Name: age_death, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     0.0
591_120522    3.0
604_120523    1.0
545_120516    0.0
364_120502    1.0
Name: med_con_sum_bl, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.069731
591_120522    0.926817
604_120523    1.549014
545_120516    0.727593
364_120502    1.198759
Name: gpath, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     0.648951
591_120522    1.831791
604_120523    1.175537
545_120516    1.631315
364_120502    1.164589
Name: amylsqrt_est_8reg, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     0.605607
591_120522    0.255506
604_120523    0.958724
545_120516    0.593186
364_120502    0.470473
Name: plaq_d, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.212379
591_120522    2.019769
604_120523    1.664274
545_120516    1.470877
364_120502    1.970883
Name: plaq_n, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.391206
591_120522    0.505175
604_120523    2.024042
545_120516    0.118717
364_120502    1.154920
Name: nft, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.639377
591_120522    1.834671
604_120523    2.217816
545_120516    1.529590
364_120502    1.812797
Name: tangsqrt_est_8reg, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     1.0
591_120522    1.0
604_120523    3.0
545_120516    2.0
364_120502    2.0
Name: caa_4gp, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     2.0
591_120522    1.0
604_120523    2.0
545_120516    3.0
364_120502    1.0
Name: cvda_4gp2, dtype: float64
____________________________________________________________________________________________________
specimenID
23_120411     99.797399
591_120522    96.449008
604_120523    90.000000
545_120516    90.781656
364_120502    89.549624
Name: final_age_at_diag, dtype: float64
____________________________________________________________________________________________________

In [122]:
numeric_columns = ['disease_duration']
numeric_columns

['disease_duration']

In [123]:
data

,ENSG00000111206_ENSG00000113068,ENSG00000105136_ENSG00000239556,ENSG00000119508_ENSG00000198604,ENSG00000171606_ENSG00000104936,ENSG00000179627_ENSG00000244509,ENSG00000119950_ENSG00000148842,ENSG00000151090_ENSG00000277053,ENSG00000198466_ENSG00000113048,ENSG00000128573_ENSG00000134419,ENSG00000244405_ENSG00000110756,...,ENSG00000158711_ENSG00000131269,ENSG00000125846_ENSG00000100292,ENSG00000107175_ENSG00000198369,ENSG00000158711_ENSG00000090432,ENSG00000170631_ENSG00000275367,ENSG00000186026_ENSG00000232422,ENSG00000091656_ENSG00000187240,ENSG00000101190_ENSG00000084092,ENSG00000130684_ENSG00000213638,ENSG00000111087_ENSG00000164300
429_120507,8.106844,5.953746,6.982843,6.704462,7.560285,5.984992,5.180594,5.871500,8.419682,6.684675,...,8.693215,9.533984,5.477487,7.576140,8.642704,9.726011,9.374269,6.724997,10.044114,6.990022
321_120501,7.026412,6.480585,6.563555,6.702860,7.163425,5.886370,7.407375,5.917673,9.802440,6.425286,...,7.764447,8.869367,5.948520,7.723241,7.915955,9.232442,10.584731,5.922493,10.125676,6.529332
715_120531,6.721336,5.906043,6.783255,6.357966,7.312478,5.726961,7.202536,5.758418,9.810183,6.861619,...,8.616443,8.532079,6.084957,7.309277,8.152755,9.186036,9.200678,6.328791,9.675305,6.648849
232_120425,6.862470,5.390621,6.218685,6.304508,7.284934,5.968609,8.162574,6.465257,9.334754,5.997467,...,8.386665,9.160886,5.451607,8.689367,8.677687,9.047344,9.435422,6.710578,10.109824,6.724867
511_120515,6.922772,5.619094,8.139077,6.002942,7.332551,5.788170,7.032000,5.845303,8.615721,6.930930,...,8.230843,7.776168,6.119251,6.435303,7.389269,9.200690,10.992755,6.168366,10.083069,6.627241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434_120507,7.185419,5.678550,6.635823,6.387301,7.169939,5.981906,6.810191,6.299799,8.482809,7.192838,...,9.108525,9.086801,6.644873,5.397323,8.160205,9.210829,9.626756,6.024547,10.185424,6.646170
721_120531,7.201048,5.978915,6.602670,6.754971,6.185004,5.338485,7.914904,5.787812,9.571388,7.420922,...,9.108327,9.490019,6.062113,8.360826,8.283306,9.176075,10.026373,5.923558,9.984965,6.578862
459_120514,6.993379,5.798019,7.012632,6.969961,7.629748,5.689236,6.149011,5.862015,9.576479,6.995242,...,8.551721,9.286045,5.880532,7.970798,8.259386,9.365843,9.547453,6.422678,10.127116,6.715680
635_120524,7.192252,7.852239,7.097503,6.851899,7.157685,5.565584,7.265344,6.002101,8.060742,7.131518,...,8.770605,9.524290,6.052024,7.865985,8.271631,9.047047,9.462333,6.189153,10.276237,6.397147
689_120604,6.850640,5.782499,7.044135,6.461255,7.675678,5.595576,6.163828,5.718703,9.321147,6.847677,...,8.368738,9.091003,5.969412,8.052429,8.293416,9.368700,9.669145,6.233142,10.009847,6.692632

In [124]:
all_clinical_data_numerical_columns = ad_data[numeric_columns]
all_clinical_data_numerical_columns

            disease_duration
specimenID
23_120411           2.201232
591_120522          5.023956
604_120523          9.696099
545_120516          9.760438
364_120502          9.303217
...                      ...
649_120529          1.292266
689_120604          3.709788
942_131101          0.344969
628_120524          4.533881
721_120531          9.379877

[87 rows x 1 columns]

In [125]:
all_clinical_data_numerical_columns = all_clinical_data_numerical_columns.loc[data.index]
all_clinical_data_numerical_columns

            disease_duration
429_120507          2.652977
321_120501          6.713210
715_120531          3.422313
232_120425          2.907598
511_120515          5.965777
...                      ...
434_120507         10.201232
721_120531          9.379877
459_120514          6.929500
635_120524          1.092402
689_120604          3.709788

[87 rows x 1 columns]

In [126]:
data

,ENSG00000111206_ENSG00000113068,ENSG00000105136_ENSG00000239556,ENSG00000119508_ENSG00000198604,ENSG00000171606_ENSG00000104936,ENSG00000179627_ENSG00000244509,ENSG00000119950_ENSG00000148842,ENSG00000151090_ENSG00000277053,ENSG00000198466_ENSG00000113048,ENSG00000128573_ENSG00000134419,ENSG00000244405_ENSG00000110756,...,ENSG00000158711_ENSG00000131269,ENSG00000125846_ENSG00000100292,ENSG00000107175_ENSG00000198369,ENSG00000158711_ENSG00000090432,ENSG00000170631_ENSG00000275367,ENSG00000186026_ENSG00000232422,ENSG00000091656_ENSG00000187240,ENSG00000101190_ENSG00000084092,ENSG00000130684_ENSG00000213638,ENSG00000111087_ENSG00000164300
429_120507,8.106844,5.953746,6.982843,6.704462,7.560285,5.984992,5.180594,5.871500,8.419682,6.684675,...,8.693215,9.533984,5.477487,7.576140,8.642704,9.726011,9.374269,6.724997,10.044114,6.990022
321_120501,7.026412,6.480585,6.563555,6.702860,7.163425,5.886370,7.407375,5.917673,9.802440,6.425286,...,7.764447,8.869367,5.948520,7.723241,7.915955,9.232442,10.584731,5.922493,10.125676,6.529332
715_120531,6.721336,5.906043,6.783255,6.357966,7.312478,5.726961,7.202536,5.758418,9.810183,6.861619,...,8.616443,8.532079,6.084957,7.309277,8.152755,9.186036,9.200678,6.328791,9.675305,6.648849
232_120425,6.862470,5.390621,6.218685,6.304508,7.284934,5.968609,8.162574,6.465257,9.334754,5.997467,...,8.386665,9.160886,5.451607,8.689367,8.677687,9.047344,9.435422,6.710578,10.109824,6.724867
511_120515,6.922772,5.619094,8.139077,6.002942,7.332551,5.788170,7.032000,5.845303,8.615721,6.930930,...,8.230843,7.776168,6.119251,6.435303,7.389269,9.200690,10.992755,6.168366,10.083069,6.627241
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434_120507,7.185419,5.678550,6.635823,6.387301,7.169939,5.981906,6.810191,6.299799,8.482809,7.192838,...,9.108525,9.086801,6.644873,5.397323,8.160205,9.210829,9.626756,6.024547,10.185424,6.646170
721_120531,7.201048,5.978915,6.602670,6.754971,6.185004,5.338485,7.914904,5.787812,9.571388,7.420922,...,9.108327,9.490019,6.062113,8.360826,8.283306,9.176075,10.026373,5.923558,9.984965,6.578862
459_120514,6.993379,5.798019,7.012632,6.969961,7.629748,5.689236,6.149011,5.862015,9.576479,6.995242,...,8.551721,9.286045,5.880532,7.970798,8.259386,9.365843,9.547453,6.422678,10.127116,6.715680
635_120524,7.192252,7.852239,7.097503,6.851899,7.157685,5.565584,7.265344,6.002101,8.060742,7.131518,...,8.770605,9.524290,6.052024,7.865985,8.271631,9.047047,9.462333,6.189153,10.276237,6.397147
689_120604,6.850640,5.782499,7.044135,6.461255,7.675678,5.595576,6.163828,5.718703,9.321147,6.847677,...,8.368738,9.091003,5.969412,8.052429,8.293416,9.368700,9.669145,6.233142,10.009847,6.692632

In [127]:
for i in all_clinical_data_numerical_columns.columns:
    print(len(all_clinical_data_numerical_columns[i].dropna()))

87

In [129]:
from scipy import stats

dct_corr= dict()
dct_p_value= dict()
from tqdm import tqdm
for i in tqdm(all_clinical_data_numerical_columns.columns):
    
    df = all_clinical_data_numerical_columns[i].dropna()
    
    df = pd.DataFrame(df)
    
    temp_data = data.loc[df.index]

    clinical_var_list = df[i].tolist()
    
    #print(temp_data)
    for k in temp_data.columns:
        
        #print(clinical_var_list)
        
        #print(temp_df_count_matrix)
        edge_weights_list = temp_data[k].tolist()
        
        rho, p_value = stats.spearmanr(clinical_var_list,edge_weights_list)

        dct_corr[f'{i}_{k}']= rho
        
        dct_p_value[f'{i}_{k}'] = p_value

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [01:12<00:00, 72.55s/it]

In [130]:
corr_df = pd.DataFrame.from_dict(list(dct_corr.items()))

In [131]:
corr_df = corr_df.sort_values(by = 1)
corr_df

                                                       0         1
36347   disease_duration_ENSG00000166823_ENSG00000026103 -0.441532
55064   disease_duration_ENSG00000256683_ENSG00000179776 -0.431253
32311   disease_duration_ENSG00000172939_ENSG00000213694 -0.410421
57942   disease_duration_ENSG00000198939_ENSG00000152778 -0.410330
19572   disease_duration_ENSG00000156925_ENSG00000005379 -0.409036
...                                                  ...       ...
66857   disease_duration_ENSG00000173404_ENSG00000170385  0.390100
3376    disease_duration_ENSG00000156273_ENSG00000261325  0.399413
117068  disease_duration_ENSG00000188227_ENSG00000189184  0.402821
118428  disease_duration_ENSG00000196724_ENSG00000138629  0.407742
84339   disease_duration_ENSG00000133740_ENSG00000141699  0.407852

[118489 rows x 2 columns]

In [ ]:
!mkdir '../../../data_preprocessed/correlation_output'

In [132]:
corr_df.rename(columns = {1:'AD_correlation_value'}, inplace = True)

In [133]:
corr_df

                                                       0  AD_correlation_value
36347   disease_duration_ENSG00000166823_ENSG00000026103             -0.441532
55064   disease_duration_ENSG00000256683_ENSG00000179776             -0.431253
32311   disease_duration_ENSG00000172939_ENSG00000213694             -0.410421
57942   disease_duration_ENSG00000198939_ENSG00000152778             -0.410330
19572   disease_duration_ENSG00000156925_ENSG00000005379             -0.409036
...                                                  ...                   ...
66857   disease_duration_ENSG00000173404_ENSG00000170385              0.390100
3376    disease_duration_ENSG00000156273_ENSG00000261325              0.399413
117068  disease_duration_ENSG00000188227_ENSG00000189184              0.402821
118428  disease_duration_ENSG00000196724_ENSG00000138629              0.407742
84339   disease_duration_ENSG00000133740_ENSG00000141699              0.407852

[118489 rows x 2 columns]

In [134]:
p_value_df = pd.DataFrame.from_dict(list( dct_p_value.items()))
p_value_df

                                                       0         1
0       disease_duration_ENSG00000111206_ENSG00000113068  0.161210
1       disease_duration_ENSG00000105136_ENSG00000239556  0.933505
2       disease_duration_ENSG00000119508_ENSG00000198604  0.501763
3       disease_duration_ENSG00000171606_ENSG00000104936  0.418652
4       disease_duration_ENSG00000179627_ENSG00000244509  0.844053
...                                                  ...       ...
118484  disease_duration_ENSG00000186026_ENSG00000232422  0.538633
118485  disease_duration_ENSG00000091656_ENSG00000187240  0.669172
118486  disease_duration_ENSG00000101190_ENSG00000084092  0.536415
118487  disease_duration_ENSG00000130684_ENSG00000213638  0.903319
118488  disease_duration_ENSG00000111087_ENSG00000164300  0.580811

[118489 rows x 2 columns]

In [135]:
p_value_df.rename(columns = {1:'P_value_AD'}, inplace = True)

In [136]:
p_value_df

                                                       0  P_value_AD
0       disease_duration_ENSG00000111206_ENSG00000113068    0.161210
1       disease_duration_ENSG00000105136_ENSG00000239556    0.933505
2       disease_duration_ENSG00000119508_ENSG00000198604    0.501763
3       disease_duration_ENSG00000171606_ENSG00000104936    0.418652
4       disease_duration_ENSG00000179627_ENSG00000244509    0.844053
...                                                  ...         ...
118484  disease_duration_ENSG00000186026_ENSG00000232422    0.538633
118485  disease_duration_ENSG00000091656_ENSG00000187240    0.669172
118486  disease_duration_ENSG00000101190_ENSG00000084092    0.536415
118487  disease_duration_ENSG00000130684_ENSG00000213638    0.903319
118488  disease_duration_ENSG00000111087_ENSG00000164300    0.580811

[118489 rows x 2 columns]

In [137]:
final_corr_df = pd.merge(corr_df, p_value_df, on = 0)

In [138]:
final_corr_df

,0,AD_correlation_value,P_value_AD
0,disease_duration_ENSG00000166823_ENSG00000026103,-0.441532,0.000019
1,disease_duration_ENSG00000256683_ENSG00000179776,-0.431253,0.000030
2,disease_duration_ENSG00000172939_ENSG00000213694,-0.410421,0.000079
3,disease_duration_ENSG00000198939_ENSG00000152778,-0.410330,0.000079
4,disease_duration_ENSG00000156925_ENSG00000005379,-0.409036,0.000084
...,...,...,...
118484,disease_duration_ENSG00000173404_ENSG00000170385,0.390100,0.000188
118485,disease_duration_ENSG00000156273_ENSG00000261325,0.399413,0.000127
118486,disease_duration_ENSG00000188227_ENSG00000189184,0.402821,0.000110
118487,disease_duration_ENSG00000196724_ENSG00000138629,0.407742,0.000089
118488,disease_duration_ENSG00000133740_ENSG00000141699,0.407852,0.000088

In [139]:
final_corr_df.to_csv('../../../data_preprocessed/correlation_output/ad_corr_disease_duration.csv', index = False)

In [140]:
final_corr_df

,0,AD_correlation_value,P_value_AD
0,disease_duration_ENSG00000166823_ENSG00000026103,-0.441532,0.000019
1,disease_duration_ENSG00000256683_ENSG00000179776,-0.431253,0.000030
2,disease_duration_ENSG00000172939_ENSG00000213694,-0.410421,0.000079
3,disease_duration_ENSG00000198939_ENSG00000152778,-0.410330,0.000079
4,disease_duration_ENSG00000156925_ENSG00000005379,-0.409036,0.000084
...,...,...,...
118484,disease_duration_ENSG00000173404_ENSG00000170385,0.390100,0.000188
118485,disease_duration_ENSG00000156273_ENSG00000261325,0.399413,0.000127
118486,disease_duration_ENSG00000188227_ENSG00000189184,0.402821,0.000110
118487,disease_duration_ENSG00000196724_ENSG00000138629,0.407742,0.000089
118488,disease_duration_ENSG00000133740_ENSG00000141699,0.407852,0.000088

In [141]:
final_corr_df

,0,AD_correlation_value,P_value_AD
0,disease_duration_ENSG00000166823_ENSG00000026103,-0.441532,0.000019
1,disease_duration_ENSG00000256683_ENSG00000179776,-0.431253,0.000030
2,disease_duration_ENSG00000172939_ENSG00000213694,-0.410421,0.000079
3,disease_duration_ENSG00000198939_ENSG00000152778,-0.410330,0.000079
4,disease_duration_ENSG00000156925_ENSG00000005379,-0.409036,0.000084
...,...,...,...
118484,disease_duration_ENSG00000173404_ENSG00000170385,0.390100,0.000188
118485,disease_duration_ENSG00000156273_ENSG00000261325,0.399413,0.000127
118486,disease_duration_ENSG00000188227_ENSG00000189184,0.402821,0.000110
118487,disease_duration_ENSG00000196724_ENSG00000138629,0.407742,0.000089
118488,disease_duration_ENSG00000133740_ENSG00000141699,0.407852,0.000088

In [148]:
final_corr_df[final_corr_df.P_value_AD<0.05]

,0,AD_correlation_value,P_value_AD
0,disease_duration_ENSG00000166823_ENSG00000026103,-0.441532,0.000019
1,disease_duration_ENSG00000256683_ENSG00000179776,-0.431253,0.000030
2,disease_duration_ENSG00000172939_ENSG00000213694,-0.410421,0.000079
3,disease_duration_ENSG00000198939_ENSG00000152778,-0.410330,0.000079
4,disease_duration_ENSG00000156925_ENSG00000005379,-0.409036,0.000084
...,...,...,...
118484,disease_duration_ENSG00000173404_ENSG00000170385,0.390100,0.000188
118485,disease_duration_ENSG00000156273_ENSG00000261325,0.399413,0.000127
118486,disease_duration_ENSG00000188227_ENSG00000189184,0.402821,0.000110
118487,disease_duration_ENSG00000196724_ENSG00000138629,0.407742,0.000089
118488,disease_duration_ENSG00000133740_ENSG00000141699,0.407852,0.000088

In [142]:
l = [
 'ENSG00000166823_ENSG00000178199',
 'ENSG00000157557_ENSG00000121903',

 'ENSG00000028277_ENSG00000039139',
 'ENSG00000081059_ENSG00000255561',
 'ENSG00000167981_ENSG00000143222',
 'ENSG00000198482_ENSG00000156219',
 'ENSG00000188786_ENSG00000083799',
 'ENSG00000168874_ENSG00000139197',
 'ENSG00000139800_ENSG00000150175',
 'ENSG00000079432_ENSG00000214425',
 'ENSG00000162992_ENSG00000139197',
 'ENSG00000256294_ENSG00000272576',
 'ENSG00000169635_ENSG00000234841',
 'ENSG00000125850_ENSG00000198783',
 'ENSG00000078900_ENSG00000062096',
 'ENSG00000120837_ENSG00000123179',
 'ENSG00000079432_ENSG00000188234',
 'ENSG00000188786_ENSG00000162384',
 'ENSG00000251369_ENSG00000265018',
 'ENSG00000234284_ENSG00000149089',
 'ENSG00000198429_ENSG00000107262',
 'ENSG00000188785_ENSG00000122641']

In [144]:
keep_corr = []

for i in tqdm(l):

    for k in final_corr_df[0].values.tolist():
        if i in k:
            if 'dis' in k:
               keep_corr.append(k)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 22/22 [00:00<00:00, 61.31it/s]

In [145]:
final_corr_df_important_edges  = final_corr_df[final_corr_df[0].isin(keep_corr)]

In [146]:
final_corr_df_important_edges.P_value_AD.min()

0.04871289646638031

In [147]:
final_corr_df_important_edges

,0,AD_correlation_value,P_value_AD
16437,disease_duration_ENSG00000234284_ENSG00000149089,-0.110757,0.307125
21338,disease_duration_ENSG00000139800_ENSG00000150175,-0.093442,0.389319
24261,disease_duration_ENSG00000078900_ENSG00000062096,-0.084293,0.437604
27517,disease_duration_ENSG00000198429_ENSG00000107262,-0.074652,0.491960
29343,disease_duration_ENSG00000188785_ENSG00000122641,-0.069640,0.521561
30288,disease_duration_ENSG00000188786_ENSG00000083799,-0.066888,0.538189
36409,disease_duration_ENSG00000157557_ENSG00000121903,-0.051360,0.636617
44479,disease_duration_ENSG00000120837_ENSG00000123179,-0.032733,0.763431
47036,disease_duration_ENSG00000198482_ENSG00000156219,-0.027029,0.803744
55095,disease_duration_ENSG00000256294_ENSG00000272576,-0.009787,0.928311
66616,disease_duration_ENSG00000125850_ENSG00000198783,0.014817,0.891651
69257,disease_duration_ENSG00000167981_ENSG00000143222,0.020486,0.850616
72932,disease_duration_ENSG00000079432_ENSG00000214425,0.028268,0.794938
81029,disease_duration_ENSG00000188786_ENSG00000162384,0.046785,0.666973
82664,disease_duration_ENSG00000079432_ENSG00000188234,0.050631,0.641416
88440,disease_duration_ENSG00000166823_ENSG00000178199,0.064847,0.550689
88926,disease_duration_ENSG00000251369_ENSG00000265018,0.066177,0.542526
97090,disease_duration_ENSG00000168874_ENSG00000139197,0.089597,0.409214
100255,disease_duration_ENSG00000162992_ENSG00000139197,0.099913,0.357181
101981,disease_duration_ENSG00000081059_ENSG00000255561,0.105909,0.328910
103759,disease_duration_ENSG00000169635_ENSG00000234841,0.112816,0.298161
116701,disease_duration_ENSG00000028277_ENSG00000039139,0.211981,0.048713

In [ ]:
final_corr_df_important_edges_significant = final_corr_df_important_edges[final_corr_df_important_edges.P_value_AD<0.05]