In [12]:
import pandas as pd
import os
from tqdm import tqdm

In [19]:
len(os.listdir('../../data_preprocessed/grn_output/ad_nci_one_network//lioness/'))

154

In [20]:
!pwd

/12tb_dsk2/danish/GRN_new_21_feb_2025/src/code_for_lioness_networks_analysis

In [21]:
os.listdir('../../data_preprocessed/grn_output/ad_nci_one_network//lioness/')

['lioness.429_120507.33.csv',
 'lioness.74_120417.56.csv',
 'lioness.104_120418.84.csv',
 'lioness.564_120517.143.csv',
 'lioness.567_120521.82.csv',
 'lioness.951_131107.128.csv',
 'lioness.72_120417.130.csv',
 'lioness.550_120517.74.csv',
 'lioness.531_120516.88.csv',
 'lioness.45_120416.50.csv',
 'lioness.482_120514.106.csv',
 'lioness.663_120530.18.csv',
 'lioness.456_120507.139.csv',
 'lioness.24_120411.17.csv',
 'lioness.274_120430.15.csv',
 'lioness.691_120605.2.csv',
 'lioness.617_120524.37.csv',
 'lioness.711_120531.8.csv',
 'lioness.649_120529.126.csv',
 'lioness.704_120605.79.csv',
 'lioness.628_120524.145.csv',
 'lioness.12_120410.114.csv',
 'lioness.812_130702.113.csv',
 'lioness.228_120425.34.csv',
 'lioness.481_120514.64.csv',
 'lioness.637_120524.19.csv',
 'lioness.606_120523.62.csv',
 'lioness.82_120417.136.csv',
 'lioness.689_120604.129.csv',
 'lioness.470_120514.133.csv',
 'lioness.505_120515.90.csv',
 'lioness.182_120424.127.csv',
 'lioness.331_120501.94.csv',
 'lioness.635_120524.70.csv',
 'lioness.483_120515.152.csv',
 'lioness.329_120501.138.csv',
 'lioness.314_120501.76.csv',
 'lioness.360_120502.102.csv',
 'lioness.202_120424.89.csv',
 'lioness.146_120419.46.csv',
 'lioness.537_120516.71.csv',
 'lioness.57_120417.92.csv',
 'lioness.11_120410.103.csv',
 'lioness.363_120502.47.csv',
 'lioness.364_120502.6.csv',
 'lioness.677_120604.149.csv',
 'lioness.352_120501.123.csv',
 'lioness.237_120426.96.csv',
 'lioness.554_120517.119.csv',
 'lioness.602_120523.9.csv',
 'lioness.286_120430.55.csv',
 'lioness.520_120515.49.csv',
 'lioness.605_120523.52.csv',
 'lioness.231_120425.68.csv',
 'lioness.829_130725.48.csv',
 'lioness.460_120514.23.csv',
 'lioness.647_120529.43.csv',
 'lioness.713_120531.21.csv',
 'lioness.461_120514.98.csv',
 'lioness.292_120430.22.csv',
 'lioness.705_120605.7.csv',
 'lioness.34_120416.35.csv',
 'lioness.534_120516.59.csv',
 'lioness.197_120424.117.csv',
 'lioness.638_120524.109.csv',
 'lioness.547_120516.122.csv',
 'lioness.384_120503.110.csv',
 'lioness.120_120418.151.csv',
 'lioness.469_120514.39.csv',
 'lioness.122_120418.140.csv',
 'lioness.508_120515.83.csv',
 'lioness.318_120501.105.csv',
 'lioness.420_120507.124.csv',
 'lioness.298_120430.134.csv',
 'lioness.633_120524.111.csv',
 'lioness.407_120503.101.csv',
 'lioness.952_131107.63.csv',
 'lioness.253_120426.120.csv',
 'lioness.494_120515.40.csv',
 'lioness.708_120531.11.csv',
 'lioness.173_120424.104.csv',
 'lioness.695_120605.81.csv',
 'lioness.604_120523.4.csv',
 'lioness.70_120417.93.csv',
 'lioness.152_120419.108.csv',
 'lioness.630_120524.30.csv',
 'lioness.498_120515.86.csv',
 'lioness.715_120531.29.csv',
 'lioness.787_130530.72.csv',
 'lioness.283_120430.147.csv',
 'lioness.77_120417.69.csv',
 'lioness.76_120417.87.csv',
 'lioness.04_120405.25.csv',
 'lioness.551_120517.135.csv',
 'lioness.02_120405.42.csv',
 'lioness.193_120424.125.csv',
 'lioness.626_120524.58.csv',
 'lioness.181_120424.67.csv',
 'lioness.229_120425.10.csv',
 'lioness.280_120430.16.csv',
 'lioness.587_120522.146.csv',
 'lioness.588_120522.3.csv',
 'lioness.350_120501.53.csv',
 'lioness.355_120501.27.csv',
 'lioness.721_120531.148.csv',
 'lioness.424_120507.121.csv',
 'lioness.386_120503.137.csv',
 'lioness.706_120605.14.csv',
 'lioness.340_120501.80.csv',
 'lioness.88_120417.85.csv',
 'lioness.703_120605.26.csv',
 'lioness.345_120501.112.csv',
 'lioness.323_120501.91.csv',
 'lioness.511_120515.32.csv',
 'lioness.408_120503.107.csv',
 'lioness.243_120426.61.csv',
 'lioness.568_120521.51.csv',
 'lioness.304_120430.118.csv',
 'lioness.607_120523.60.csv',
 'lioness.646_120524.54.csv',
 'lioness.545_120516.5.csv',
 'lioness.213_120425.142.csv',
 'lioness.142_120419.150.csv',
 'lioness.214_120425.31.csv',
 'lioness.502_120515.100.csv',
 'lioness.497_120515.77.csv',
 'lioness.591_120522.1.csv',
 'lioness.289_120430.57.csv',
 'lioness.28_120411.12.csv',
 'lioness.434_120507.78.csv',
 'lioness.418_120507.73.csv',
 'lioness.942_131101.131.csv',
 'lioness.459_120514.38.csv',
 'lioness.232_120425.41.csv',
 'lioness.326_120501.95.csv',
 'lioness.174_120424.153.csv',
 'lioness.196_120424.116.csv',
 'lioness.427_120507.44.csv',
 'lioness.309_120430.24.csv',
 'lioness.938_131101.115.csv',
 'lioness.290_120430.132.csv',
 'lioness.321_120501.66.csv',
 'lioness.501_120515.99.csv',
 'lioness.65_120417.144.csv',
 'lioness.285_120430.36.csv',
 'lioness.23_120411.0.csv',
 'lioness.553_120517.97.csv',
 'lioness.950_131107.45.csv',
 'lioness.36_120416.75.csv',
 'lioness.56_120417.65.csv',
 'lioness.680_120604.13.csv',
 'lioness.310_120430.28.csv',
 'lioness.444_120507.20.csv',
 'lioness.245_120426.141.csv']

In [22]:
!mkdir ../../data_preprocessed/grn_output/ad_nci_one_network//lioness/ad_nci_preprocessed

In [23]:
raw_single_sample_network_dir_path = '../../data_preprocessed/grn_output/ad_nci_one_network//lioness/'
preprocessed_single_sample_network_dir_path = '../../data_preprocessed/grn_output/ad_nci_one_network//lioness/ad_nci_preprocessed/'

In [24]:
for i in os.listdir(raw_single_sample_network_dir_path ):
  
    data = pd.read_csv(raw_single_sample_network_dir_path + i, index_col=0)
    break
data

,ENSG00000101901,ENSG00000174839,ENSG00000151466,ENSG00000168288,ENSG00000112343,ENSG00000172890,ENSG00000150991,ENSG00000100029,ENSG00000181894,ENSG00000206560,...,ENSG00000039560,ENSG00000223496,ENSG00000166681,ENSG00000078061,ENSG00000272143,ENSG00000120457,ENSG00000100528,ENSG00000116205,ENSG00000100603,ENSG00000114933
ENSG00000001167,2.721948,1.641659,-3.147184,2.536086,0.487893,-0.130612,1.916796,-4.183126,1.571247,1.594315,...,0.619611,-2.774473,-0.069338,2.219418,-2.521062,0.488159,1.478993,0.771232,-1.389271,-0.821675
ENSG00000004848,-0.262631,-0.369413,-0.610534,-0.378368,-0.179207,-0.560453,-0.128992,0.721518,-0.246436,-0.145454,...,-0.561203,-0.000157,-0.485209,-0.528159,-0.161222,-0.642632,-0.282792,-0.426463,-0.012737,-0.152018
ENSG00000005513,-0.043474,0.140771,-0.830799,-0.058137,0.183527,-0.510452,0.269341,0.585054,-0.036731,0.387743,...,-0.381906,-0.342026,-0.638477,-0.106396,-0.481559,-0.613827,-0.249770,-0.136973,-0.119507,-0.022299
ENSG00000005889,0.842255,0.258689,0.570119,0.375524,-0.461351,4.126061,-0.658893,-5.333430,-0.012651,-0.645081,...,0.407295,-1.512439,-0.281589,0.176809,-1.698413,0.163801,0.240709,0.392524,-1.196939,-0.836809
ENSG00000006047,-1.358335,-1.086162,1.157502,-1.679005,-0.649645,-0.622177,-1.102678,1.063350,-1.022324,-0.734379,...,-0.846737,0.650910,-0.332499,-0.778071,0.652022,-0.884676,-1.064086,-0.766497,0.317618,-0.303754
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSG00000267508,-0.012340,-0.052691,-1.106907,-0.142895,0.197678,-0.485114,0.218720,-0.159723,-0.099720,0.239673,...,-0.287965,-0.809737,-0.609494,0.415670,-0.403687,-0.497086,-0.242872,-0.040334,-0.233346,-0.109823
ENSG00000267680,-3.282900,-2.315974,2.588752,-2.648379,-1.509085,-0.471535,-2.871560,4.214481,-2.507165,-2.470247,...,-1.620709,3.071584,-0.611354,-3.651229,2.599246,-1.300230,-1.947252,-1.850605,1.043737,0.225296
ENSG00000272602,-0.106626,-0.056686,-0.570954,-0.340030,-0.049540,-0.607191,0.052677,0.218650,-0.064127,0.074441,...,-0.466002,-0.389705,-0.451947,-0.023618,-0.366964,-0.574070,-0.283237,-0.243955,-0.143684,-0.252813
ENSG00000275111,0.474475,0.076443,-0.094572,-0.011745,-0.105395,-0.185526,0.044915,-2.271318,0.078272,0.277304,...,0.079416,-1.415409,-0.260922,0.990492,-0.839544,-0.040361,-0.033498,0.102397,-0.518324,-0.567359
ENSG00000278129,-0.963929,-0.602174,-0.168370,-0.895256,-0.391431,-0.627470,-0.436086,1.419099,-0.534610,-0.540478,...,-0.687930,0.660600,-0.422618,-0.743677,0.178659,-0.753262,-0.678668,-0.613245,0.094721,-0.178149

In [25]:
from tqdm import tqdm
col_1 = []
col_2 = []
values = []
for i in tqdm(os.listdir(raw_single_sample_network_dir_path)):
    if i == 'panda_obj.pkl' or i == 'output_panda_df.csv':
        continue
    data = pd.read_csv(raw_single_sample_network_dir_path + i, index_col=0)
    
    for i in tqdm(data.iterrows()):
        col_1.extend([i[0] for l in range(len(data.columns))])
        col_2.extend(data.columns)
        values.extend(i[1].tolist())
    preprocessed_data = pd.DataFrame([col_1,col_2,values]).T
    break

  0%|                                                   | 0/155 [00:00<?, ?it/s]
0it [00:00, ?it/s]
89it [00:00, 888.22it/s]
178it [00:00, 775.66it/s]
257it [00:00, 747.97it/s]
334it [00:00, 755.58it/s]
413it [00:00, 764.37it/s]
492it [00:00, 771.15it/s]
570it [00:00, 709.72it/s]
715it [00:00, 746.29it/s]
  0%|                                                   | 0/155 [01:37<?, ?it/s]

In [26]:
preprocessed_data

                        0                1         2
0         ENSG00000001167  ENSG00000101901  2.721948
1         ENSG00000001167  ENSG00000174839  1.641659
2         ENSG00000001167  ENSG00000151466 -3.147184
3         ENSG00000001167  ENSG00000168288  2.536086
4         ENSG00000001167  ENSG00000112343  0.487893
...                   ...              ...       ...
12390945  ENSG00000278129  ENSG00000120457 -0.753262
12390946  ENSG00000278129  ENSG00000100528 -0.678668
12390947  ENSG00000278129  ENSG00000116205 -0.613245
12390948  ENSG00000278129  ENSG00000100603  0.094721
12390949  ENSG00000278129  ENSG00000114933 -0.178149

[12390950 rows x 3 columns]

In [27]:
list_of_genes = data.columns
list_of_tf = data.index.tolist()

In [28]:
for m in tqdm(os.listdir(raw_single_sample_network_dir_path)):
    col_1 = []
    col_2 = []
    values = []
    if m in os.listdir(preprocessed_single_sample_network_dir_path):
        continue
        
    
    if m == 'panda_obj.pkl' or m == 'output_panda_df.csv':
        continue
    if m == 'output_panda_df.csv':
        continue
    print(m)
    if 'csv' in m:
        data = pd.read_csv(raw_single_sample_network_dir_path + m, index_col=0)
        list_of_genes = data.columns
        list_of_tf = data.index.tolist()
        for i in list_of_tf:
            for j in list_of_genes:
                if data.loc[i,j] >= 3.69446:
                    col_1.append(i)
                    col_2.append(j)
                    values.append(data.loc[i,j])
                 
        preprocessed_data = pd.DataFrame([col_1, col_2, values]).T
        preprocessed_data.to_csv(preprocessed_single_sample_network_dir_path  + m, index= False)

  0%|                                                   | 0/155 [00:00<?, ?it/s]

lioness.429_120507.33.csv

  1%|▎                                        | 1/155 [00:48<2:04:55, 48.67s/it]

lioness.74_120417.56.csv

  1%|▌                                        | 2/155 [01:37<2:04:20, 48.76s/it]

lioness.104_120418.84.csv

  2%|▊                                        | 3/155 [02:26<2:03:33, 48.77s/it]

lioness.564_120517.143.csv

  3%|█                                        | 4/155 [03:15<2:03:24, 49.03s/it]

lioness.567_120521.82.csv

  3%|█▎                                       | 5/155 [04:03<2:01:26, 48.57s/it]

lioness.951_131107.128.csv

  4%|█▌                                       | 6/155 [04:51<2:00:04, 48.35s/it]

lioness.72_120417.130.csv

  5%|█▊                                       | 7/155 [05:39<1:58:46, 48.15s/it]

lioness.550_120517.74.csv

  5%|██                                       | 8/155 [06:26<1:57:03, 47.78s/it]

lioness.531_120516.88.csv

  6%|██▍                                      | 9/155 [07:14<1:56:35, 47.92s/it]

lioness.45_120416.50.csv

  6%|██▌                                     | 10/155 [08:02<1:55:44, 47.89s/it]

lioness.482_120514.106.csv

  7%|██▊                                     | 11/155 [08:51<1:56:07, 48.38s/it]

lioness.663_120530.18.csv

  8%|███                                     | 12/155 [09:40<1:55:24, 48.42s/it]

lioness.456_120507.139.csv

  8%|███▎                                    | 13/155 [10:29<1:55:09, 48.66s/it]

lioness.24_120411.17.csv

  9%|███▌                                    | 14/155 [11:18<1:54:45, 48.83s/it]

lioness.274_120430.15.csv

 10%|███▊                                    | 15/155 [12:06<1:52:58, 48.42s/it]

lioness.691_120605.2.csv

 10%|████▏                                   | 16/155 [12:53<1:51:43, 48.22s/it]

lioness.617_120524.37.csv

 11%|████▍                                   | 17/155 [13:40<1:50:06, 47.88s/it]

lioness.711_120531.8.csv

 12%|████▋                                   | 18/155 [14:26<1:47:42, 47.17s/it]

lioness.649_120529.126.csv

 12%|████▉                                   | 19/155 [15:12<1:46:07, 46.82s/it]

lioness.704_120605.79.csv

 13%|█████▏                                  | 20/155 [15:59<1:45:20, 46.82s/it]

lioness.628_120524.145.csv

 14%|█████▍                                  | 21/155 [16:45<1:44:07, 46.62s/it]

lioness.12_120410.114.csv

 14%|█████▋                                  | 22/155 [17:32<1:43:31, 46.70s/it]

lioness.812_130702.113.csv

 15%|█████▉                                  | 23/155 [18:18<1:42:41, 46.68s/it]

lioness.228_120425.34.csv

 15%|██████▏                                 | 24/155 [19:05<1:42:06, 46.76s/it]

lioness.481_120514.64.csv

 16%|██████▍                                 | 25/155 [19:54<1:42:32, 47.32s/it]

ad_nci_preprocessed
lioness.637_120524.19.csv

 17%|██████▉                                 | 27/155 [20:44<1:18:44, 36.91s/it]

lioness.606_120523.62.csv

 18%|███████▏                                | 28/155 [21:33<1:24:44, 40.04s/it]

lioness.82_120417.136.csv

 19%|███████▍                                | 29/155 [22:20<1:27:40, 41.75s/it]

lioness.689_120604.129.csv

 19%|███████▋                                | 30/155 [23:08<1:30:56, 43.65s/it]

lioness.470_120514.133.csv

 20%|████████                                | 31/155 [23:55<1:31:53, 44.46s/it]

lioness.505_120515.90.csv

 21%|████████▎                               | 32/155 [24:42<1:32:23, 45.07s/it]

lioness.182_120424.127.csv

 21%|████████▌                               | 33/155 [25:28<1:32:16, 45.39s/it]

lioness.331_120501.94.csv

 22%|████████▊                               | 34/155 [26:14<1:31:59, 45.62s/it]

lioness.635_120524.70.csv

 23%|█████████                               | 35/155 [27:01<1:31:57, 45.98s/it]

lioness.483_120515.152.csv

 23%|█████████▎                              | 36/155 [27:47<1:31:26, 46.10s/it]

lioness.329_120501.138.csv

 24%|█████████▌                              | 37/155 [28:34<1:31:07, 46.34s/it]

lioness.314_120501.76.csv

 25%|█████████▊                              | 38/155 [29:21<1:30:41, 46.51s/it]

lioness.360_120502.102.csv

 25%|██████████                              | 39/155 [30:08<1:30:09, 46.63s/it]

lioness.202_120424.89.csv

 26%|██████████▎                             | 40/155 [30:55<1:29:29, 46.69s/it]

lioness.146_120419.46.csv

 26%|██████████▌                             | 41/155 [31:41<1:28:46, 46.72s/it]

lioness.537_120516.71.csv

 27%|██████████▊                             | 42/155 [32:28<1:28:02, 46.75s/it]

lioness.57_120417.92.csv

 28%|███████████                             | 43/155 [33:15<1:27:13, 46.73s/it]

lioness.11_120410.103.csv

 28%|███████████▎                            | 44/155 [34:02<1:26:25, 46.72s/it]

lioness.363_120502.47.csv

 29%|███████████▌                            | 45/155 [34:48<1:25:39, 46.72s/it]

lioness.364_120502.6.csv

 30%|███████████▊                            | 46/155 [35:35<1:24:42, 46.63s/it]

lioness.677_120604.149.csv

 30%|████████████▏                           | 47/155 [36:21<1:23:53, 46.61s/it]

lioness.352_120501.123.csv

 31%|████████████▍                           | 48/155 [37:09<1:23:50, 47.02s/it]

lioness.237_120426.96.csv

 32%|████████████▋                           | 49/155 [37:57<1:23:39, 47.35s/it]

lioness.554_120517.119.csv

 32%|████████████▉                           | 50/155 [38:46<1:23:31, 47.73s/it]

lioness.602_120523.9.csv

 33%|█████████████▏                          | 51/155 [39:33<1:22:26, 47.56s/it]

lioness.286_120430.55.csv

 34%|█████████████▍                          | 52/155 [40:21<1:22:00, 47.77s/it]

lioness.520_120515.49.csv

 34%|█████████████▋                          | 53/155 [41:10<1:21:33, 47.97s/it]

lioness.605_120523.52.csv

 35%|█████████████▉                          | 54/155 [42:10<1:26:49, 51.58s/it]

lioness.231_120425.68.csv

 35%|██████████████▏                         | 55/155 [42:59<1:24:32, 50.72s/it]

lioness.829_130725.48.csv

 36%|██████████████▍                         | 56/155 [43:46<1:22:04, 49.74s/it]

lioness.460_120514.23.csv

 37%|██████████████▋                         | 57/155 [44:35<1:20:37, 49.36s/it]

lioness.647_120529.43.csv

 37%|██████████████▉                         | 58/155 [45:24<1:19:55, 49.43s/it]

lioness.713_120531.21.csv

 38%|███████████████▏                        | 59/155 [46:15<1:19:48, 49.88s/it]

lioness.461_120514.98.csv

 39%|███████████████▍                        | 60/155 [47:11<1:21:55, 51.74s/it]

lioness.292_120430.22.csv

 39%|███████████████▋                        | 61/155 [48:06<1:22:38, 52.76s/it]

lioness.705_120605.7.csv

 40%|████████████████                        | 62/155 [49:07<1:25:40, 55.27s/it]

lioness.34_120416.35.csv

 41%|████████████████▎                       | 63/155 [49:55<1:21:17, 53.02s/it]

lioness.534_120516.59.csv

 41%|████████████████▌                       | 64/155 [50:44<1:18:29, 51.75s/it]

lioness.197_120424.117.csv

 42%|████████████████▊                       | 65/155 [51:33<1:16:17, 50.86s/it]

lioness.638_120524.109.csv

 43%|█████████████████                       | 66/155 [52:20<1:13:54, 49.83s/it]

lioness.547_120516.122.csv

 43%|█████████████████▎                      | 67/155 [53:09<1:12:32, 49.46s/it]

lioness.384_120503.110.csv

 44%|█████████████████▌                      | 68/155 [54:01<1:12:52, 50.25s/it]

lioness.120_120418.151.csv

 45%|█████████████████▊                      | 69/155 [54:51<1:11:45, 50.07s/it]

lioness.469_120514.39.csv

 45%|██████████████████                      | 70/155 [55:39<1:10:04, 49.46s/it]

lioness.122_120418.140.csv

 46%|██████████████████▎                     | 71/155 [56:28<1:09:14, 49.46s/it]

lioness.508_120515.83.csv

 46%|██████████████████▌                     | 72/155 [57:17<1:08:22, 49.43s/it]

lioness.318_120501.105.csv

 47%|██████████████████▊                     | 73/155 [58:06<1:07:11, 49.16s/it]

lioness.420_120507.124.csv

 48%|███████████████████                     | 74/155 [58:55<1:06:23, 49.18s/it]

lioness.298_120430.134.csv

 48%|███████████████████▎                    | 75/155 [59:43<1:05:09, 48.87s/it]

lioness.633_120524.111.csv

 49%|██████████████████▋                   | 76/155 [1:00:32<1:04:18, 48.85s/it]

lioness.407_120503.101.csv

 50%|██████████████████▉                   | 77/155 [1:01:20<1:03:02, 48.49s/it]

lioness.952_131107.63.csv

 50%|███████████████████                   | 78/155 [1:02:08<1:02:15, 48.51s/it]

lioness.253_120426.120.csv

 51%|███████████████████▎                  | 79/155 [1:02:58<1:01:46, 48.77s/it]

lioness.494_120515.40.csv

 52%|███████████████████▌                  | 80/155 [1:03:47<1:01:02, 48.83s/it]

lioness.708_120531.11.csv

 52%|████████████████████▉                   | 81/155 [1:04:35<59:59, 48.64s/it]

lioness.173_120424.104.csv

 53%|█████████████████████▏                  | 82/155 [1:05:24<59:28, 48.88s/it]

lioness.695_120605.81.csv

 54%|█████████████████████▍                  | 83/155 [1:06:13<58:37, 48.86s/it]

lioness.604_120523.4.csv

 54%|█████████████████████▋                  | 84/155 [1:07:02<57:40, 48.75s/it]

lioness.70_120417.93.csv

 55%|█████████████████████▉                  | 85/155 [1:07:51<57:02, 48.89s/it]

lioness.152_120419.108.csv

 55%|██████████████████████▏                 | 86/155 [1:08:48<59:07, 51.41s/it]

lioness.630_120524.30.csv

 56%|██████████████████████▍                 | 87/155 [1:09:37<57:23, 50.64s/it]

lioness.498_120515.86.csv

 57%|██████████████████████▋                 | 88/155 [1:10:26<55:53, 50.05s/it]

lioness.715_120531.29.csv

 57%|██████████████████████▉                 | 89/155 [1:11:14<54:31, 49.57s/it]

lioness.787_130530.72.csv

 58%|███████████████████████▏                | 90/155 [1:12:01<52:44, 48.69s/it]

lioness.283_120430.147.csv

 59%|███████████████████████▍                | 91/155 [1:12:48<51:29, 48.27s/it]

lioness.77_120417.69.csv

 59%|███████████████████████▋                | 92/155 [1:13:38<51:08, 48.70s/it]

lioness.76_120417.87.csv

 60%|████████████████████████                | 93/155 [1:14:27<50:24, 48.78s/it]

lioness.04_120405.25.csv

 61%|████████████████████████▎               | 94/155 [1:15:15<49:34, 48.76s/it]

lioness.551_120517.135.csv

 61%|████████████████████████▌               | 95/155 [1:16:04<48:39, 48.67s/it]

lioness.02_120405.42.csv

 62%|████████████████████████▊               | 96/155 [1:16:52<47:50, 48.65s/it]

lioness.193_120424.125.csv

 63%|█████████████████████████               | 97/155 [1:17:40<46:47, 48.40s/it]

lioness.626_120524.58.csv

 63%|█████████████████████████▎              | 98/155 [1:18:29<46:10, 48.60s/it]

lioness.181_120424.67.csv

 64%|█████████████████████████▌              | 99/155 [1:19:19<45:32, 48.80s/it]

lioness.229_120425.10.csv

 65%|█████████████████████████▏             | 100/155 [1:20:07<44:36, 48.66s/it]

lioness.280_120430.16.csv

 65%|█████████████████████████▍             | 101/155 [1:20:56<43:50, 48.71s/it]

lioness.587_120522.146.csv

 66%|█████████████████████████▋             | 102/155 [1:21:44<43:00, 48.70s/it]

lioness.588_120522.3.csv

 66%|█████████████████████████▉             | 103/155 [1:22:33<42:06, 48.59s/it]

lioness.350_120501.53.csv

 67%|██████████████████████████▏            | 104/155 [1:23:21<41:13, 48.50s/it]

lioness.355_120501.27.csv

 68%|██████████████████████████▍            | 105/155 [1:24:09<40:24, 48.48s/it]

lioness.721_120531.148.csv

 68%|██████████████████████████▋            | 106/155 [1:24:58<39:37, 48.52s/it]

lioness.424_120507.121.csv

 69%|██████████████████████████▉            | 107/155 [1:25:47<38:52, 48.60s/it]

lioness.386_120503.137.csv

 70%|███████████████████████████▏           | 108/155 [1:26:36<38:13, 48.80s/it]

lioness.706_120605.14.csv

 70%|███████████████████████████▍           | 109/155 [1:27:25<37:22, 48.75s/it]

lioness.340_120501.80.csv

 71%|███████████████████████████▋           | 110/155 [1:28:13<36:32, 48.71s/it]

lioness.88_120417.85.csv

 72%|███████████████████████████▉           | 111/155 [1:29:02<35:45, 48.77s/it]

lioness.703_120605.26.csv

 72%|████████████████████████████▏          | 112/155 [1:29:51<34:52, 48.67s/it]

lioness.345_120501.112.csv

 73%|████████████████████████████▍          | 113/155 [1:30:39<34:04, 48.68s/it]

lioness.323_120501.91.csv

 74%|████████████████████████████▋          | 114/155 [1:31:28<33:12, 48.60s/it]

lioness.511_120515.32.csv

 74%|████████████████████████████▉          | 115/155 [1:32:17<32:27, 48.70s/it]

lioness.408_120503.107.csv

 75%|█████████████████████████████▏         | 116/155 [1:33:06<31:45, 48.87s/it]

lioness.243_120426.61.csv

 75%|█████████████████████████████▍         | 117/155 [1:33:54<30:47, 48.62s/it]

lioness.568_120521.51.csv

 76%|█████████████████████████████▋         | 118/155 [1:34:43<29:58, 48.60s/it]

lioness.304_120430.118.csv

 77%|█████████████████████████████▉         | 119/155 [1:35:32<29:15, 48.77s/it]

lioness.607_120523.60.csv

 77%|██████████████████████████████▏        | 120/155 [1:36:20<28:22, 48.63s/it]

lioness.646_120524.54.csv

 78%|██████████████████████████████▍        | 121/155 [1:37:09<27:39, 48.82s/it]

lioness.545_120516.5.csv

 79%|██████████████████████████████▋        | 122/155 [1:37:58<26:45, 48.66s/it]

lioness.213_120425.142.csv

 79%|██████████████████████████████▉        | 123/155 [1:38:47<26:02, 48.82s/it]

lioness.142_120419.150.csv

 80%|███████████████████████████████▏       | 124/155 [1:39:36<25:17, 48.96s/it]

lioness.214_120425.31.csv

 81%|███████████████████████████████▍       | 125/155 [1:40:32<25:33, 51.10s/it]

lioness.502_120515.100.csv

 81%|███████████████████████████████▋       | 126/155 [1:41:34<26:18, 54.44s/it]

lioness.497_120515.77.csv

 82%|███████████████████████████████▉       | 127/155 [1:42:22<24:27, 52.40s/it]

lioness.591_120522.1.csv

 83%|████████████████████████████████▏      | 128/155 [1:43:09<22:50, 50.77s/it]

lioness.289_120430.57.csv

 83%|████████████████████████████████▍      | 129/155 [1:43:56<21:27, 49.51s/it]

lioness.28_120411.12.csv

 84%|████████████████████████████████▋      | 130/155 [1:44:55<21:52, 52.52s/it]

lioness.434_120507.78.csv

 85%|████████████████████████████████▉      | 131/155 [1:45:43<20:24, 51.03s/it]

lioness.418_120507.73.csv

 85%|█████████████████████████████████▏     | 132/155 [1:46:30<19:09, 49.96s/it]

lioness.942_131101.131.csv

 86%|█████████████████████████████████▍     | 133/155 [1:47:18<18:06, 49.41s/it]

lioness.459_120514.38.csv

 86%|█████████████████████████████████▋     | 134/155 [1:48:06<17:04, 48.78s/it]

lioness.232_120425.41.csv

 87%|█████████████████████████████████▉     | 135/155 [1:48:53<16:07, 48.35s/it]

lioness.326_120501.95.csv

 88%|██████████████████████████████████▏    | 136/155 [1:49:41<15:14, 48.13s/it]

lioness.174_120424.153.csv

 88%|██████████████████████████████████▍    | 137/155 [1:50:29<14:26, 48.13s/it]

lioness.196_120424.116.csv

 89%|██████████████████████████████████▋    | 138/155 [1:51:17<13:37, 48.07s/it]

lioness.427_120507.44.csv

 90%|██████████████████████████████████▉    | 139/155 [1:52:03<12:40, 47.53s/it]

lioness.309_120430.24.csv

 90%|███████████████████████████████████▏   | 140/155 [1:52:50<11:52, 47.52s/it]

lioness.938_131101.115.csv

 91%|███████████████████████████████████▍   | 141/155 [1:53:38<11:04, 47.49s/it]

lioness.290_120430.132.csv

 92%|███████████████████████████████████▋   | 142/155 [1:54:26<10:18, 47.61s/it]

lioness.321_120501.66.csv

 92%|███████████████████████████████████▉   | 143/155 [1:55:13<09:29, 47.47s/it]

lioness.501_120515.99.csv

 93%|████████████████████████████████████▏  | 144/155 [1:56:00<08:42, 47.48s/it]

lioness.65_120417.144.csv

 94%|████████████████████████████████████▍  | 145/155 [1:56:48<07:55, 47.55s/it]

lioness.285_120430.36.csv

 94%|████████████████████████████████████▋  | 146/155 [1:57:36<07:09, 47.77s/it]

lioness.23_120411.0.csv

 95%|████████████████████████████████████▉  | 147/155 [1:58:25<06:23, 48.00s/it]

lioness.553_120517.97.csv

 95%|█████████████████████████████████████▏ | 148/155 [1:59:14<05:37, 48.22s/it]

lioness.950_131107.45.csv

 96%|█████████████████████████████████████▍ | 149/155 [2:00:02<04:50, 48.38s/it]

lioness.36_120416.75.csv

 97%|█████████████████████████████████████▋ | 150/155 [2:00:51<04:01, 48.33s/it]

lioness.56_120417.65.csv

 97%|█████████████████████████████████████▉ | 151/155 [2:01:38<03:12, 48.08s/it]

lioness.680_120604.13.csv

 98%|██████████████████████████████████████▏| 152/155 [2:02:26<02:24, 48.09s/it]

lioness.310_120430.28.csv

 99%|██████████████████████████████████████▍| 153/155 [2:03:15<01:36, 48.36s/it]

lioness.444_120507.20.csv

 99%|██████████████████████████████████████▋| 154/155 [2:04:04<00:48, 48.43s/it]

lioness.245_120426.141.csv

100%|███████████████████████████████████████| 155/155 [2:04:51<00:00, 48.33s/it]